### ISSUE TITLE
Tag a release including fixes for 0.6

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#100]
Could you please tag a release including the fixes for 0.6?

**Comment by SimonDanisch** [comment]
Sure! @andyferris @c42f, anything I could be overlooking that would speak against a tag?

**Comment by c42f** [comment]
From here it looks like we should be pretty much good to go, but I vaguely remember @andyferris wanted to tweak something from #67 (which is why I didn't tag master last time I made a release, but merely the bugfix from #92).

By the way Simon, I've set up @attobot on this repository, so all you need to do to make a new release is create a new tag and release at https://github.com/JuliaArrays/StaticArrays.jl/releases/new

**Comment by andyferris** [comment]
Right, it was removing the tuple indexing stuff.

Was that done? This doesn't have to hold back a release.

**Comment by andyferris** [comment]
OK, so AFAICT the current tuple indexing behavior is the way it always is. (I was afraid of tagging new behavior that we would just need to deprecate.)

I think we can just tag as-is. It's nice that we don't need compat. The one thing that needs to be done before a new tag is removing the "-" from REQUIRE in `julia 0.5-` (Tony keeps bugging me about this one).

**Comment by c42f** [comment]
REQUIRE fixed.

**Comment by c42f** [comment]
@SimonDanisch I have a feeling we had some API changes here, at least to some lesser used parts of the package?  Should this be 0.2.0?

**Comment by SimonDanisch** [comment]
Yeah maybe ;) I don't care about it right now, since 0.6 is breaking for me anyways!

**Comment by SimonDanisch** [comment]
The plan is to bring it back, whenever I take the step to clean everything up for 0.6

**Comment by c42f** [comment]
Hah, I see that the include of `StaticArrays.FixedSizeArrays` depends on the main julia version, so in some sense this is breaking for 0.6 but not for 0.5. I don't think the semver spec knows *what* to do with that, as julia-0.6 is in dev anyway :-)

On balance I guess this is a minor number change to 0.1.5.

**Comment by c42f** [comment]
Ok, I went ahead did this:

https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.1.5
https://github.com/JuliaLang/METADATA.jl/pull/7934
