### ISSUE TITLE
`ismutable` gives incorrect results

### ISSUE THREAD

**Issue by cscherrer** [JuliaArrays/StaticArrays.jl#1005]
As I understand, a `SizedVector` is mutable exactly when its parent ("`x.data`") is mutable. This currently gives incorrect results. Here's an example mutating a `SizedVector` despite `ismutable(x) == false`.

```julia
julia> x = SizedVector{3}([1,2,3])
3-element SizedVector{3, Int64, Vector{Int64}} with indices SOneTo(3):
 1
 2
 3

julia> x[1] = 10
10

julia> x
3-element SizedVector{3, Int64, Vector{Int64}} with indices SOneTo(3):
 10
  2
  3

julia> ismutable(x)
false
```

**Comment by fredrikekre** [comment]
But isn't `ismutable` just for anwering if the struct is `mutable struct`? In this case `StaticVector` is immutable:
```julia
julia> x = SizedVector{3}([1,2,3]);

julia> x.data = [3, 2, 1];
ERROR: setfield!: immutable struct of type SizedArray cannot be changed
Stacktrace:
 [1] setproperty!(x::SizedVector{3, Int64, Vector{Int64}}, f::Symbol, v::Vector{Int64})
   @ Base ./Base.jl:43
 [2] top-level scope
   @ REPL[11]:1
```

**Comment by cscherrer** [comment]
Hmm, I hadn't thought of mutability having different meanings. A `SizedVector` wrapping a mutable vector is a mutable array, in the sense that `setindex!` changes values in-place. How would you test for "can be mutated in place"?

**Comment by cscherrer** [comment]
I started a Zulip discussion on this ("Querying in-place mutability"), so I'll close this now. Thanks @fredrikekre
