### ISSUE TITLE
"Tuple indexing into AbstractArray" methods are not okay

### ISSUE THREAD

**Issue by tkelman** [JuliaArrays/StaticArrays.jl#101]
You need to remove these immediately, or make them specific to your own types. Packages should not change the behavior of all other array code when they're imported. If I had seen these sooner I wouldn't have allowed this package to be registered.

**Comment by andyferris** [comment]
Yes, agreed - these are being replaced by `getindex(::AbstractArray, ::StaticArray) -> StaticArray`.
