### ISSUE TITLE
default-constructor of FieldVector leads to StackOverflowError when used with different types

### ISSUE THREAD

**Issue by bjuergens** [JuliaArrays/StaticArrays.jl#1026]
i followed the [example for FieldVectors](https://juliaarrays.github.io/StaticArrays.jl/stable/pages/api/#StaticArrays.FieldVector) and was surprised to find that calling the default-construct with a mix of float64 and float32 causes it to crash in a stackoverflowerror

```julia
using StaticArrays

struct Vec3D{T} <: FieldVector{3, T}
    x::T
    y::T
    z::T
end

@info "this works" Vec3D(1,2,3)
@info "this works" Vec3D(Float32(1), Float32(2),Float32(3))
@info "this works" Vec3D(Float64(1), Float64(2),Float64(3))
@info "this fails" Vec3D(Float32(1), Float32(2),Float64(3))
 ```

I think requiring the same type within a vector is a reasonable limitation (especially considering the performance impact that mixed-types would have, I guess). But since this is some rather unexpected behavior, I would suggest making this limitation explicit. 

I think a good solution would change the FieldVector (or at least the example in documentation of it) in a way that it crashes gracefully with a descriptive error-message when used with mixed types. 

An ok solution would just update the documentation to explicitly state this limitation. 

#968 is very related, exept it is about a custom constructor and not the default-one

**Comment by hyrodium** [comment]
This issue will be fixed by #1016.

```julia
julia> using StaticArrays

julia> struct Vec3D{T} <: FieldVector{3, T}
           x::T
           y::T
           z::T
       end

julia> @info "this works" Vec3D(1,2,3)
┌ Info: this works
│   Vec3D(1, 2, 3) =
│    3-element Vec3D{Int64} with indices SOneTo(3):
│     1
│     2
└     3

julia> @info "this works" Vec3D(Float32(1), Float32(2),Float32(3))
┌ Info: this works
│   Vec3D(Float32(1), Float32(2), Float32(3)) =
│    3-element Vec3D{Float32} with indices SOneTo(3):
│     1.0
│     2.0
└     3.0

julia> @info "this works" Vec3D(Float64(1), Float64(2),Float64(3))
┌ Info: this works
│   Vec3D(Float64(1), Float64(2), Float64(3)) =
│    3-element Vec3D{Float64} with indices SOneTo(3):
│     1.0
│     2.0
└     3.0

julia> @info "this fails" Vec3D(Float32(1), Float32(2),Float64(3))
┌ Info: this fails
│   Vec3D(Float32(1), Float32(2), Float64(3)) =
│    3-element Vec3D{Float64} with indices SOneTo(3):
│     1.0
│     2.0
└     3.0
```
