### ISSUE TITLE
Size bug in + (introduced in 0.1.5)

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#103]
``` julia
julia> a = rand(SMatrix{1, 2})
1×2 StaticArrays.SMatrix{1,2,Float64,2}:
 0.964606  0.400012

julia> b = rand(SMatrix{1, 2})
1×2 StaticArrays.SMatrix{1,2,Float64,2}:
 0.134356  0.179786

julia> c = a + b
2×1 StaticArrays.SMatrix{2,1,Float64,2}:
 1.09896 
 0.579798
```

**Comment by tkoolen** [comment]
Actually, this bug is present in 0.1.5 as well. 0.1.4 is OK. Changing title.

**Comment by tkoolen** [comment]
Seems to be a bug in `promote_op`:
```julia
julia> StaticArrays.promote_op(+, SMatrix{1, 2, Float64, 2}, SMatrix{1, 2, Float64, 2})
StaticArrays.SMatrix{2,1,Float64,2}
```

**Comment by SimonDanisch** [comment]
seems like a typo in here:
https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/SMatrix.jl#L119

**Comment by SimonDanisch** [comment]
How do we not have tests for this case?! :D

![image](https://cloud.githubusercontent.com/assets/1010467/22895453/9183472a-f1ea-11e6-83dc-a95cfe1ebbb5.png)

**Comment by andyferris** [comment]
Yes, test coverage is a thing that needs work. I did spend some evenings for a few weeks adding tests, but I discovered you can only do that for so long without getting bored...
