### ISSUE TITLE
`setindex` isn't compatible with ArrayInterfaceCore `setindex`

### ISSUE THREAD

**Issue by nhz2** [JuliaArrays/StaticArrays.jl#1039]
```julia-repl
julia> using StaticArrays

julia> import ArrayInterfaceCore

julia> a = @SMatrix ones(2, 2);

julia> setindex(a,0.0,1,1)
ERROR: MethodError: setindex(::SMatrix{2, 2, Float64, 4}, ::Float64, ::Int64, ::Int64) is ambiguous. Candidates:
  setindex(a::StaticArray, x, inds...) in StaticArrays at /home/nathan/.julia/packages/StaticArrays/6D1fn/src/deque.jl:198
  setindex(x::AbstractMatrix, v, i::Int64, j::Int64) in ArrayInterfaceCore at /home/nathan/.julia/packages/ArrayInterfaceCore/wwYvJ/src/ArrayInterfaceCore.jl:129
Possible fix, define
  setindex(::StaticArray{S, T, 2} where {T, S<:Tuple}, ::Any, ::Int64, ::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[12]:1
```

Here are links to the code referenced in the error:

https://github.com/JuliaArrays/StaticArrays.jl/blob/dcc75659edb23cc68526966c9971d1e02f49dfca/src/deque.jl#L198

https://github.com/JuliaArrays/ArrayInterface.jl/blob/b1ce7bb443eb82fc281be2989ee2fa5e364fe1d9/lib/ArrayInterfaceCore/src/ArrayInterfaceCore.jl#L129-L132

Would adding the following code solve the issue?
```julia
@propagate_inbounds setindex(a::StaticMatrix, x,  i::Int, j::Int) = setindex(a, x, LinearIndices(a)[i,j])
```

**Comment by mateuszbaran** [comment]
First of all, why does ArrayInterface need to do that type piracy?

**Comment by nhz2** [comment]
I'm not sure. I only noticed the issue because I'm also using https://github.com/JuliaDiff/FiniteDiff.jl which has both ArrayInterfaceCore and StaticArrays as dependencies.

**Comment by hyrodium** [comment]
The ambiguity was introduced after https://github.com/JuliaArrays/StaticArrays.jl/pull/1034 is merged.

>why does ArrayInterface need to do that type piracy?

I'm not sure why they need it, but it expands `Base.setindex`.

```julia
julia> a = [1,2,3]
3-element Vector{Int64}:
 1
 2
 3

julia> Base.setindex(a,5,1)
ERROR: MethodError: no method matching setindex(::Vector{Int64}, ::Int64, ::Int64)
Closest candidates are:
  setindex(::Tuple, ::Any, ::Integer) at ~/julia/julia-1.7.3/share/julia/base/tuple.jl:52
  setindex(::CartesianIndex, ::Any, ::Any) at ~/julia/julia-1.7.3/share/julia/base/multidimensional.jl:100
  setindex(::NamedTuple, ::Any, ::Symbol) at ~/julia/julia-1.7.3/share/julia/base/namedtuple.jl:367
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

julia> using ArrayInterface

julia> Base.setindex(a,5,1)
3-element Vector{Int64}:
 5
 2
 3
```

**Comment by hyrodium** [comment]
If we need `setindex(::AbstractArray, v, i...)`, I think we have the following choices:

* Define `setindex(::AbstactArray, v, i...)` in `Base` to avoid piracy
* Fix the definition in `ArrayInterfaceCore` (maybe, we can just remove lines https://github.com/JuliaArrays/ArrayInterface.jl/blob/b1ce7bb443eb82fc281be2989ee2fa5e364fe1d9/lib/ArrayInterfaceCore/src/ArrayInterfaceCore.jl#L124-L132.)

In any case, this issue should be solved outside of StaticArrays.jl, I guess.

**Comment by mateuszbaran** [comment]
I'm closing this because it's quite clear that it's an issue with `ArrayInterfaceCore`, not `StaticArrays`.

**Comment by clouds56** [comment]
Possible workaround (before ArrayInterfaceCore fixes)
```julia
import StaticArrays
Base.setindex(a::StaticArrays.SMatrix, x, i::Int64, j::Int64) = Base.setindex(a, x, LinearIndices(a)[i, j])
# Base.setindex(StaticArrays.@SMatrix(fill("a",2,3)), "b", 2, 1)
```
