### ISSUE TITLE
Linear system solve promotes Float32 to Float64

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaArrays/StaticArrays.jl#1041]
```
using StaticArrays
A = @SMatrix([1 0 0;0 1 0; 0 0 1])
b = SVector(1.f0, 1.f0, 1.f0)
A\b
```
gives Float64. This is because solve calls `det`, which returns Float64 in this case. I'm guessing this is because `det` is intended to match julia's, which returns Float64 on Int inputs (as far as I understand, because it would be too expensive to do the "right thing" and compute it as int). Not sure how to fix it properly, though...

**Comment by thchr** [comment]
It's tricky to get right in general: e.g., `A\b` has `Float32` element type for 1×1 and 2×2 sizes of `A`, but not for 3×3 and beyond. Above 3×3, the culprit is not `det` but `lu`.

**Comment by antoine-levitt** [comment]
I don't understand your comment?
```
A = @SMatrix([1 0;0 1])
b = SVector(1.f0, 1.f0)
display(A\b)
```
gives `2-element SVector{2, Float64} with indices SOneTo(2):`.

But now I think about it, even plain arrays return Float64 here, so it makes sense that static arrays mimics base, I'm closing this issue. It would be possible for staticarrays to do the right thing for some sizes (those for which explicit division-free algorithms are feasible) in a type-stable manner, which would be cool but perhaps too confusing?

**Comment by thchr** [comment]
Argh, had an accidental left-over conversion to `Float32` in my 2×2 check - sorry. The 1×1 check does really give `Float32` though:

![image](https://user-images.githubusercontent.com/26799210/173910035-0731eb1c-ee5c-4079-9a75-173e36fa311e.png)

**Comment by antoine-levitt** [comment]
Yes, the 1x1 doesn't call det. Base julia does the same - which, incidentally, makes it type unstable.

**Comment by thchr** [comment]
> [...] which, incidentally, makes it type unstable.

That's not great, yeah...
