### ISSUE TITLE
SVector type printing changed?

### ISSUE THREAD

**Issue by nhz2** [JuliaArrays/StaticArrays.jl#1049]
For some reason `string(SVector)` is longer in version 1.5.0.

With StaticArrays 1.4.7
```julia
julia> string(SVector)
"SVector"
```

With StaticArrays 1.5.0
``` julia
julia> string(SVector)
"SArray{Tuple{S}, T, 1, S} where {S, T}"
```

**Comment by mateuszbaran** [comment]
That's because currently `SVector` is not exported from StaticArraysCore.jl. I will fix that.

**Comment by mateuszbaran** [comment]
I don't know why it was designed that way. Relevant PR: https://github.com/JuliaLang/julia/pull/36107.
