### ISSUE TITLE
inner constructors for custom types derived from Field*

### ISSUE THREAD

**Issue by mfiano** [JuliaArrays/StaticArrays.jl#1055]
I'm a Julia beginner, and I've been playing around with StaticArrays for a couple weeks and I'm loving it, so thanks for this great library. 

One issue I ran into, was in defining inner constructors for a `FieldVector` derived type. In my case, I wanted a custom `Vector4` type (so I could document its functionality differently without type piracy, among other reasons), and one of the things I wanted to be able to do was to be able to construct this type with a collection of variadic constructors. For example, given:

```julia
import StaticArrays: FieldVector

abstract type BaseVector{N,T<:Real} <: FieldVector{N,T} end

struct Vector4{T<:Real} <: BaseVector{4,T}
    x::T
    y::T
    z::T
    w::T
end
```

an inner constructor such as something like: `Vector4(x::T, y::T,  z::T=zero(T), w::T=zero(T)) ...`, will fail to be invoked, due to some deep macrology I can't yet understand (even migrating from Lisp) checking that the argument length is 4. Outer constructors work fine. Is this intended?

**Comment by mateuszbaran** [comment]
Seems to work fine:
```julia
julia> import StaticArrays: FieldVector


julia> abstract type BaseVector{N,T<:Real} <: FieldVector{N,T} end

julia> struct Vector4{T<:Real} <: BaseVector{4,T}
           x::T
           y::T
           z::T
           w::T
           Vector4(x::T, y::T, z::T=zero(T), w::T=zero(T)) where {T} = new{T}(x, y, z, w)
       end

julia> 

julia> Vector4(1, 3, 12)
4-element Vector4{Int64} with indices SOneTo(4):
  1
  3
 12
  0
```That works 
(though I'd make that an outer constructor).

**Comment by mfiano** [comment]
Maybe it is just my misunderstanding. It does not work with `Vector4(1.0, 3.0, 12.0)`

**Comment by mateuszbaran** [comment]
What's your error? It does work for me:
```julia
julia> import StaticArrays: FieldVector

julia> abstract type BaseVector{N,T<:Real} <: FieldVector{N,T} end

julia> struct Vector4{T<:Real} <: BaseVector{4,T}
           x::T
           y::T
           z::T
           w::T
           Vector4(x::T, y::T, z::T=zero(T), w::T=zero(T)) where {T} = new{T}(x, y, z, w)
       end

julia> Vector4(1.0, 3.0, 12.0)
4-element Vector4{Float64} with indices SOneTo(4):
  1.0
  3.0
 12.0
  0.0
```

**Comment by mfiano** [comment]
I think I see what I was doing wrong, after not being able to reproduce with your example. The inner constructor doesn't have a type parameter `Vector4{...}(...), and so things like:

```julia
(Practice) julia> Vector4{Float64}(1.0, 3.0, 12.0)
ERROR: DimensionMismatch: No precise constructor for Vector4{Float64} found. Length of input was 3.
Stacktrace:
 [1] _no_precise_size(SA::Type, x::Tuple{Float64, Float64, Float64})
   @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:148
 [2] _no_precise_size(SA::Type, x::StaticArrays.Args{Tuple{Float64, Float64, Float64}})
   @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:147
 [3] length_match_size
   @ ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:117 [inlined]
 [4] construct_type
   @ ~/.data/julia/packages/StaticArrays/5bAMi/src/FieldArray.jl:117 [inlined]
 [5] Vector4{Float64}(::Float64, ::Vararg{Any})
   @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:152
 [6] top-level scope
   @ REPL[11]:1
```

will fail. This is my mistake. I'm sorry for the noise.

**Comment by mfiano** [comment]
Interestingly, though:

```julia
(Practice) julia> Vector4{Float64}(1.0, 3.0, 12.0, 0.0)
ERROR: StackOverflowError:
Stacktrace:
     [1] Vector4{Float64}(::Float64, ::Vararg{Float64})
       @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:152
     [2] Vector4{Float64}(x::NTuple{4, Float64})
       @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/FieldArray.jl:113
--- the last 2 lines are repeated 13771 more times ---
 [27545] Vector4{Float64}(::Float64, ::Vararg{Any})
       @ StaticArrays ~/.data/julia/packages/StaticArrays/5bAMi/src/convert.jl:152
```

**Comment by mfiano** [comment]
Yes, this is all my fault it seems, and things make more sense today with a clear mind. Thanks for maintaining this library! And again, I'm sorry for the noise.

**Comment by mateuszbaran** [comment]
No problem, constructors are sometimes hard to get right and it's possible StaticArrays.jl has a related issue in some corner case so feel free to write here if you have issues related to StaticArrays.jl.
