### ISSUE TITLE
problem with pinv

### ISSUE THREAD

**Issue by daanhb** [JuliaArrays/StaticArrays.jl#1080]
I have on StaticArrays v1.5.5:
```
julia> using StaticArrays, LinearAlgebra

julia> pinv([-1 0; 0 -1])
2×2 Matrix{Float64}:
 -1.0   0.0
  0.0  -1.0

julia> pinv(SA[-1 0; 0 -1])
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 0.0  0.0
 0.0  0.0
```
Found because one of our tests was [failing](https://github.com/JuliaApproximation/DomainSets.jl/issues/110)

**Comment by hyrodium** [comment]
Maybe `A[$i,$i] > tol` should be `abs(A[$i,$i]) > tol`.

https://github.com/JuliaArrays/StaticArrays.jl/blob/8d709a4b3c543c73ad0b8b7b8a47074f8ddd2f7d/src/pinv.jl#L36

This is my mistake introduced in #873, and I can open a PR in the next few days.

**Comment by daanhb** [comment]
Thanks and no worries, we have a workaround

**Comment by daanhb** [comment]
Hmm, it seems I was unlucky to hit this (or lucky?). With a tiny perturbation it is fine:
```julia
julia> pinv(SA[-1. 1e-16; 0 -1.])
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 -1.0  -0.0
 -0.0  -1.0

julia> pinv(SA[-1. 0; -1e-16 -1.])
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 -1.0      -1.0e-16
  1.0e-16  -1.0
```
We had that test for a while, perhaps this is why it went unnoticed.
