### ISSUE TITLE
`hypot` for StaticVectors?

### ISSUE THREAD

**Issue by JaydevSR** [JuliaArrays/StaticArrays.jl#1085]
It is normal for coordinates/vectors to be stored in `StaticVectors`, so I think `hypot` should be supported as it aids in easily calculating the length of the vectors.

**Comment by martinholters** [comment]
What exactly should it do? "Easily calculating the length of the vectors" sounds like a job for `norm`. Could you provide a clarifying example?

**Comment by JaydevSR** [comment]
I missed something about `hypot`, that it is supposed to be used with variable number of arguments but not with vectors (like `norm`). Due to this I was unpacking the vector to use `hypot` where I should be using `norm`. I guess there is no issue.
