### ISSUE TITLE
StackOverflowError on FieldVector introduced in v1.4.5

### ISSUE THREAD

**Issue by tamasgal** [JuliaArrays/StaticArrays.jl#1088]
I have the following code which has worked fine until 1.4.4 and started to produce a StackOverflowError in 1.4.5. I have not done a bisect yet but I guess it's coming from https://github.com/JuliaArrays/StaticArrays.jl/issues/1026

This is the code, which ought to prevent a construction of the `FieldVector` subtype with different types:

```julia
struct Position{T} <: FieldVector{3, T}
    x::T
    y::T
    z::T

    Position(x::T, y::T, z::T) where {T} = new{T}(x, y, z)
end
```

The offending line is the inner constructor. It works with individual errors but gives a `StackOverflowError ` when e.g. a tuple is passed:

```
julia> Position(1,2,3)
3-element Position{Int64} with indices SOneTo(3):
 1
 2
 3

julia> Position((1,2,3))
ERROR: StackOverflowError:
Stacktrace:
     [1] Position{Int64}(::Int64, ::Vararg{Int64})
       @ StaticArrays ~/.julia/packages/StaticArrays/G7IlJ/src/convert.jl:152
     [2] Position{Int64}(x::Tuple{Int64, Int64, Int64})
       @ StaticArrays ~/.julia/packages/StaticArrays/G7IlJ/src/FieldArray.jl:113
--- the last 2 lines are repeated 18647 more times ---
 [37297] StaticArray
       @ ~/.julia/packages/StaticArrays/G7IlJ/src/convert.jl:152 [inlined]
```

If I remove that line, it works but then segfaults on v1.4.4 and below 😉 see here: 

```julia
julia> Position(1,2,3.0)
ERROR: StackOverflowError:
Stacktrace:
     [1] Position(::Int64, ::Vararg{Any})
       @ StaticArrays ~/.julia/packages/StaticArrays/58yy1/src/convert.jl:4
     [2] Position(x::Tuple{Int64, Int64, Float64})
       @ StaticArrays ~/.julia/packages/StaticArrays/58yy1/src/FieldArray.jl:117--- the last 2 lines are repeated 18646 more times ---
```

I guess the solution is to tag a version and limit the StaticArrays version to max 1.4.4 and then create a new one with the removed inner constructor and require at least 1.4.5. Or is there a better way?

**Comment by mateuszbaran** [comment]
This is a small intended change introduced by #1016 to fix some issues.

**Comment by tamasgal** [comment]
Alright, thanks! Let's close this...

**Comment by N5N3** [comment]
Al the error was intended, but the current error message is really bad.
I think we'd better add
```julia
function (::Type{FA})(x...) where {FA <: FieldArray}
    has_size(FA) || error("$FA has no static size!")
    length_match_size(FA, x)
    has_eltype(FA) && error("the constructor for $FA is missing!")
    return FA(x)
end
```
and make this throw a "ERROR: the constructor for Position{Int64} is missing!" instead?
