### ISSUE TITLE
Missing convert method to facilitate initialisation of fields of type SArray

### ISSUE THREAD

**Issue by krcools** [JuliaArrays/StaticArrays.jl#110]
The following attempt to construct a Polly fails

```
using StaticArrays

type Polly{N,T}
    data::SVector{N,T}
end

p = Polly{2,Float64}((1.0, 0.0))
```

As @andyferris pointed out on [discourse](https://discourse.julialang.org/t/strange-error-message-when-trying-to-initialise-field-of-type-svector/2222) this can be fixed by adding a conversion method from a tuple to an SVector.

**Comment by andyferris** [comment]
I was hoping to address these constructors for Julia v0.6. I'm hoping the new subtyping algorithm (or perhaps just a better understanding of dispatch rules) will help make reasoning about these things a bit easier...

**Comment by c42f** [comment]
This works on the latest version, so I assume Andy did get around to fixing it.
