### ISSUE TITLE
Recently discovered faster matrix multiplication algorithms

### ISSUE THREAD

**Issue by mvsoom** [JuliaArrays/StaticArrays.jl#1100]
(Not an issue, just FYI.)

https://www.nature.com/articles/s41586-022-05172-4

;)

**Comment by thchr** [comment]
It's an impressive paper with a very interesting perspective - one of the most fun papers I've read this year - but their results do not really translate to the small-matrix setting of StaticArrays (see e.g. this nice [summary](https://fgiesen.wordpress.com/2022/10/06/on-alphatensors-new-matrix-multiplication-algorithms/)), so I don't believe there is anything actionable to do here; closing.

**Comment by mvsoom** [comment]
I see! That's a nice blog post, thanks for sharing.
