### ISSUE TITLE
Inverse of Upper Triangular using Static Matrix for storage UpperTriangular{Float64, SMatrix{3, 3, Float64, 9}} converts to Matrix

### ISSUE THREAD

**Issue by prittjam** [JuliaArrays/StaticArrays.jl#1103]
```
K₁

 3×3 UpperTriangular{Float64, SMatrix{3, 3, Float64, 9}}:
 600.0    0.0  300.0
    ⋅   600.0  300.0
    ⋅      ⋅     1.0

 inv(K₁)

 3×3 UpperTriangular{Float64, Matrix{Float64}}:
 0.00166667  0.0         -0.5
  ⋅          0.00166667  -0.5
  ⋅           ⋅           1.0
```

**Comment by prittjam** [comment]
The same holds for the 
```
\
```
operator.

**Comment by thchr** [comment]
This is not really a StaticArrays issue: we are just dispatching to `inv(A::UpperTriangular{T, S} where S<:AbstractMatrix{T})` from the LinearAlgebra stdlib (same story for `\`).

Note that this method doesn't preserve wrapper information of other matrix types either, e.g.:
```
julia> A = UpperTriangular(SMatrix{3,3}(rand(3,3)))
3×3 UpperTriangular{Float64, SMatrix{3, 3, Float64, 9}}:
 0.920842  0.998008  0.125781
  ⋅        0.241672  0.332007
  ⋅         ⋅        0.506598

julia> inv(A)
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.08596  -4.48459   2.66942
  ⋅        4.13784  -2.7118
  ⋅         ⋅        1.97395
  ```
  
In practice, it's just very unlikely to find StaticArrays-specific methods for wrappers over StaticArrays: it's just too many possible things to implement. With this in mind, I'll close this issue.
