### ISSUE TITLE
Is it possible to map enumeration to `SVector`?

### ISSUE THREAD

**Issue by drelatgithub** [JuliaArrays/StaticArrays.jl#1106]
When I do the following:
```julia
v = SA[10, 20, 30]
map(x -> x[1] + x[2], enumerate(v))
```
The result is a 3-element `Vector{Int64}` of values 11, 22 and 33. Is it possible to get the result in `SVector` since the length is known at compile time (assuming that the codes above is inside a function, and that `v` has fixed but unknown length)?

Other methods I tried but not did not work:
1. I tried to use comprehension and macro `@SVector`, but it seems that in this case I need `length(v)` but its value is unknown during macro expansion.
2. I also tried `eachindex(v)` but it seems that the result is converted to `MVector` instead of `SVector`. This part seems to have been covered in https://github.com/JuliaArrays/StaticArrays.jl/issues/1032

**Comment by mateuszbaran** [comment]
Yes, mapping such an enumeration should give an `SVector`. I will take a look, maybe it won't be hard to implement.

**Comment by mateuszbaran** [comment]
Since StaticArrays 1.5.10 it is possible to do static mapping of enumeration using `enumerate_static` (instead of `enumerate`):
```julia
julia> using StaticArrays

julia> v = SA[10, 20, 30]
3-element SVector{3, Int64} with indices SOneTo(3):
 10
 20
 30

julia> map(x -> x[1] + x[2], enumerate_static(v))
3-element SVector{3, Int64} with indices SOneTo(3):
 11
 22
 33
```
