### ISSUE TITLE
Conversion from Tuple to a FixedVector is broken

### ISSUE THREAD

**Issue by ajkeller34** [JuliaArrays/StaticArrays.jl#111]
Suppose we have the following defined:
```
julia> immutable Point{T} <: StaticArrays.FixedVector{T}
    x::T
    y::T
end
```

Now, constructing a Point from a tuple works as expected:
```
julia> Point((2,3))
2-element Devices.Points.Point{Int64}:
 2
 3
```

However, converting a tuple to a Point does not:
```
julia> convert(Point{Int}, (2,3))
ERROR: No precise constructor found. Length of input was 2 while length of Devices.Points.Point{Int64} is 2.
 in convert(::Type{Devices.Points.Point{Int64}}, ::Tuple{Int64,Int64}) at /Users/ajkeller/.julia/v0.5/StaticArrays/src/core.jl:39

julia> convert(Point{Int}, 2,3)
2-element Devices.Points.Point{Int64}:
 2
 3
```

Conversion from a tuple used to work a while ago, but I think probably [this commit](https://github.com/JuliaArrays/StaticArrays.jl/commit/997e5dd1e671f7c2e792d0f2b76f488aa8f63fc4) broke it.

**Comment by andyferris** [comment]
Is this a duplicate of #110?

I was hoping to address these constructors for Julia v0.6. I'm hoping the new subtyping algorithm (or perhaps just a better understanding of dispatch rules) will help make reasoning about these things a bit easier...

**Comment by ajkeller34** [comment]
Yep, it's a duplicate. Just when I think I've found a new bug...

Thanks for the reply.
