### ISSUE TITLE
How can I use `SMatrix` from Python

### ISSUE THREAD

**Issue by BolunDai0216** [JuliaArrays/StaticArrays.jl#1113]
Hi,

I am trying to run Julia code from Python. I am confused on how should I run 

```julia
mat = SMatrix{2, 2}([1 2; 3 4])
```

in Python? I was trying 

```python
from julia import StaticArrays as sa

mat = sa.SMatrix{2, 2}([1 2; 3 4])
```

and as I expected, I get the error

```console
*** SyntaxError: invalid syntax
```

Any idea what I should do? 

Thanks in advance!

**Comment by mateuszbaran** [comment]
As far as I know the Julia-Python interface doesn't work particularly well with custom array types. When I need to call Julia from Python and use StaticArrays.jl, then I convert from normal arrays to static arrays in Julia, after it receives data from Python.

**Comment by BolunDai0216** [comment]
Thanks for the response! Would it be possible to add a code snippet on how to do this?

**Comment by mateuszbaran** [comment]
On the Python side, you'd just use a numpy array. On the Julia side, you'd just convert an `Array` to `SArray` like in the readme of StaticArrays.jl. Which part do you have trouble with?

**Comment by BolunDai0216** [comment]
Can you show how to load numpy arrays as `Array` in Julia?

**Comment by mateuszbaran** [comment]
There is plenty of examples online, for example here: https://discourse.julialang.org/t/pyjulia-passing-numpy-array-from-python-side/45894/4 .

**Comment by BolunDai0216** [comment]
Thanks for the information!
