### ISSUE TITLE
Docs are a bit ambiguous about size() vs. Size() for user types

### ISSUE THREAD

**Issue by rdeits** [JuliaArrays/StaticArrays.jl#112]
Prior to StaticArrays v0.3.0, it seemed like the right thing to do for a user-defined StaticArray subtype was to define `Base.size()` for that type. Now, it looks like the `StaticArrays.Size()` trait is the right thing to define instead. But the docs still mention defining `size()`: https://github.com/JuliaArrays/StaticArrays.jl#implementing-your-own-types 

Would you like me to open a PR to update the docs? Or is this something that will shake out after the big 0.6 updates come through? 

Just as an example of what used to work pre-0.3:

```julia
julia> Pkg.installed("StaticArrays")
v"0.3.0"

julia> using StaticArrays

julia> immutable Foo <: StaticArray{Int, 1}
       end

julia> Base.size(::Type{Foo}) = (1,)

julia> f = Foo()
Error showing value of type Foo:
ERROR: The size of type `Foo` is not known.
```

**Comment by andyferris** [comment]
I just updated the README with an example of the method you need to define. Does this seem sufficient?

**Comment by andyferris** [comment]
(Otherwise, yes, PR's are *always* welcome :smile:)

**Comment by rdeits** [comment]
yes, that's perfect, thanks!
