### ISSUE TITLE
Performance regression in #master

### ISSUE THREAD

**Issue by ufechner7** [JuliaArrays/StaticArrays.jl#1132]
I see a performance regression in #master of 12 to 15%. Part of it is probably due to the new implementation of norm, but that cannot be the only reason for this regression.

For my benchmarks in KiteModels.jl I see:

```
StaticArrays 1.5.12   540ns (3point model) and 1256 ns (4point model)
StaticArrays master   621ns                and 1394 ns
```
I use the following setting in my code:
```julia
set_zero_subnormals(true)           # required to avoid drastic slow down on Intel CPUs when numbers become very small
```

**Comment by hyrodium** [comment]
This issue has been well discussed in https://github.com/JuliaArrays/StaticArrays.jl/pull/975#issuecomment-1436115140 and there seems to be nothing new to discuss (at least there were no responses for a week).
Feel free to comment on this issue if you have any additional comments.
