### ISSUE TITLE
Automatic functionality a la FixedSizeArrays

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#114]
With `FixedSizeArrays`, writing
```julia
immutable IntervalBox{N, T} <: FixedVector{N, Interval{T}}
    _ :: NTuple{N, Interval{T}}
end
```
generated a type that had a lot of functionality already generated.

It would be great to have this functionality also in `StaticArrays`.

**Comment by andyferris** [comment]
This is a tough one. There are three methods that we require.

1. `Size` is put into the supertype `FixedVector{N}` and similarly `FixedArray{Tuple{N}}`. I'm not sure if using `Tuple` types in this way is a good idea or not. In `AbstractArray` you define a `size` method and for `StaticArray` you define a `Size` method.
2. It assumes `_` for the data so you don't have provide a `getindex` method yourself. 
3. There is some magic going on with `FixedVector` constructors. Perhaps we could try replicate this. ("magic" that relies on interpretting the type tree and so-on seemed unpopular more recently...)

Note that these methods are required by new `AbstractArray`s which are not `StaticArray`s.

**Comment by SimonDanisch** [comment]
I've been working around this by creating a macro to construct the type!
With the recent changes of generated functions, I have the feeling that this macro needs to turn into an almost complete implementation of the fixed size array though :D

2.) shouldn't be correct for FixedSizeArrays anymore ;)

**Comment by SimonDanisch** [comment]
The macro:
https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/FixedSizeArrays.jl#L86
Not enabled on 0.6 right now:
https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/StaticArrays.jl#L57
In use:
https://github.com/JuliaGeometry/GeometryTypes.jl/blob/sd/staticarrays/src/types.jl#L51

**Comment by andyferris** [comment]
What is missing from `FieldVector` that stops it being awesome?

**Comment by andyferris** [comment]
BTW, after #127 merges we may be putting the size parameter into `StaticArray`.

This means at the very least `Size` won't ever need to be defined by the user, except in the `struct` definition itself.

**Comment by SimonDanisch** [comment]
Cool!
Also BTW, I think i got the FixedSizeArray port back to work locally :)

**Comment by c42f** [comment]
Seems like this issue is a relic of times past, so I'll close this.

However, if there's anything actionable we can do to make `FieldVector` more usable please do tell :-)
