### ISSUE TITLE
map! doesn't return dest MVector

### ISSUE THREAD

**Issue by wheeheee** [JuliaArrays/StaticArrays.jl#1141]
Say we use `map(f, a, b)` on two `MVector`s. This returns another `MVector`.
However, when the in-place `map!(f, a, a, b)` is used, then it returns the last element of a.
Is this the intended behaviour?
For example:
```
julia> a = MVector(1,2,3,4)
4-element MVector{4, Int64} with indices SOneTo(4):
 1
 2
 3
 4

julia> b = -a
4-element MVector{4, Int64} with indices SOneTo(4):
 -1
 -2
 -3
 -4

julia> map(+, a, b)
4-element MVector{4, Int64} with indices SOneTo(4):
 0
 0
 0
 0

julia> map!(+, a, a, b)
0
```

**Comment by fredrikekre** [comment]
Missing `return dest` after https://github.com/JuliaArrays/StaticArrays.jl/blob/3fcfa44bd7b7c063cdecddf54cc354a971d18415/src/mapreduce.jl#L132 I believe.
