### ISSUE TITLE
Help with backport to pre-v1.0

### ISSUE THREAD

**Issue by dkarrasch** [JuliaArrays/StaticArrays.jl#1145]
To finalize https://github.com/JuliaLang/julia/pull/26307, we need to backport the recent changes from #1136, since many packages still haven't bumped their compat entries to v1 and higher, see https://github.com/JuliaLang/julia/pull/26307#issuecomment-1477523631. So, I have a branch that does the backport, but I need a place to make a PR, from where a version v0.12.6 could be released. Could someone please help me with that?

**Comment by mateuszbaran** [comment]
I can help but I have never registered a patch to an older version yet. Is there a description of how that should be done somewhere?

**Comment by dkarrasch** [comment]
I believe it goes like this (@KristofferC ?):

1. You create a branch called `release-0.12`, branching off of the commit that is tagged with v0.12.5.
2. I make a PR against it. If all is correct, it should only have about 20 changed lines.
3. You merge that PR.
4. You call the JuliaRegistrator on that commit as usual.

**Comment by mateuszbaran** [comment]
OK, I've made the branch then: https://github.com/JuliaArrays/StaticArrays.jl/tree/release-0.12 .

**Comment by mateuszbaran** [comment]
I think this is solved now by #1146 and can be closed.
