### ISSUE TITLE
Potentially address performance regression with Julia 1.9

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaArrays/StaticArrays.jl#1148]
There's a performance issue with Julia 1.9-rc. When using the constructors with a length determined at runtime, Julia falls back on dynamic dispatch.

```
using BenchmarkTools
using StaticArrays
const xx = [1; 2]
@noinline function e(x)
    k = length(x)
    SVector{k}(x)
end

@btime e(xx) 
# 1.9-rc1: 27.898 μs (31 allocations: 2.66 KiB)
# 1.8.5: 762.239 ns (10 allocations: 544 bytes)
```

According to https://github.com/JuliaLang/julia/issues/49145, there may be changes in StaticArrays that would work around this issue.

**Comment by N5N3** [comment]
It should be noticed that this is caused by the `@propagate_inbounds` macro, which makes the constuctor inlined unstablely.
I tried some other constructor in `convert.jl`. Looks like `construct_type` is heavy enough to block the inliner so perhaps we only need this specific fix.
