### ISSUE TITLE
isassigned is slow for out-of-range indices

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaArrays/StaticArrays.jl#1152]
MWE:
```
using StaticArrays, BenchmarkTools

arr = SA[1, 2, 3]

@btime isassigned(arr, 4) # 17 μs
```
This is because Base's fallback implementation uses a try/catch, which is slow in the catch case:
https://github.com/JuliaLang/julia/blob/def2ddacc9a9b064d06c24d12885427fb0502465/base/abstractarray.jl#L605-L616

This really hurts performance when `isassigned` is being used in a case where the index is really expected to be out-of-range sometimes. I even wonder if Base's fallback implementation is just a bad idea, because it will always be slow in this case: something like `i in eachindex(arr)` would at least be faster for static arrays.

Using Julia 1.9 and StaticArrays v.1.5.12

**Comment by thchr** [comment]
There used to be a (faulty) `isassigned` specialization for StaticArrays but it was removed recently (https://github.com/JuliaArrays/StaticArrays.jl/pull/1096), partly due to incorrectness, invalidations, and because it was not clear why performance would matter here.

What do you need a performant `isassigned` for?

**Comment by gaurav-arya** [comment]
The logic was something like "given an array and an index, see if index + 1 is a valid index and access array there if so". I was using it in my package here:

https://github.com/gaurav-arya/StochasticAD.jl/blob/892486bec7bb0757a2fef6e6e8afd12374d4ebe4/src/general_rules.jl#L260

Although I've since replaced it with `i in eachindex(arr)` because of this issue

**Comment by thchr** [comment]
Yeah, that seems better: `isassigned` is intended for more than just bounds checking (i.e., it also returns false if the index is `#undef`).

See also `checkbounds`.

**Comment by gaurav-arya** [comment]
Thanks, that makes sense, `checkbounds` seems like the right thing to use indeed. 

(Although note that Base's `Array` does have its own specialization: https://github.com/JuliaLang/julia/blob/1aa65c33f24e7a6c7a341ce4a13202bfb6ac4811/base/array.jl#L258)
