### ISSUE TITLE
Extend `getproperty` overloads for vectors

### ISSUE THREAD

**Issue by serenity4** [JuliaArrays/StaticArrays.jl#1159]
It is currently possible to extract a value from a static vector using `v.x`, `v.y`, `v.z` and `v.w`.

In computer graphics, it is ubiquitous to have even more syntax to select vector components, either individually (extracting scalars) or to select a subset of them to create a new vector (swizzling). Features that may be of interest would be:
- Swizzling to create vectors out of existing ones, such as `v.xy` returning a 2-dimensional vector, or more exotic swizzles (`v.yzx`, `v.xyw`, `v.wyzx`...).
- Extracting values from the perspective of a vector representing a color, i.e. `v.r`, `v.g`, `v.b` (and the fourth component, which is then considered to be the alpha value, `v.a`).

Swizzling is the most useful feature that I think would be great to have. It is generally quite helpful to compactly and clearly index vectors with nontrivial accesses. It can be extended to `setproperty!`, e.g. `v.zyx = @SVector rand(3)`, for mutable vectors.

Viewing vectors as colors is fairly useful too, but is less important.

Here is an example implementation: https://github.com/serenity4/SPIRV.jl/blob/d527ae5069c503d910b14c1528ba091f017a2f99/src/frontend/types/vector.jl#L43-L113, which may also be defined in an `@eval` loop similar to what is done in this package.

If there is agreement on adding these features (1. swizzling and 2. adding color extraction), I'd be happy to submit a PR for either or both.

**Comment by jishnub** [comment]
Regarding your color access example, perhaps this is already provided by `LabelledArrays.jl`?

**Comment by serenity4** [comment]
I didn't know about LabelledArrays.jl, thanks. It looks nice, but using it is a bit too much given that it woudl be for a very minor convenience feature really. Taking on an extra dependency and relying on using a new wrapper type and propagating it in the right ways throughout a package would be hardly worth it.

**Comment by serenity4** [comment]
Closing in favor of an external package that defines this functionality and convenient syntax for it via a macro. See https://github.com/JuliaArrays/StaticArrays.jl/pull/1221#issuecomment-1826301732.
