### ISSUE TITLE
What is the preferred way to evoke `similar` on MArrays?

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaArrays/StaticArrays.jl#1160]
I am 99% sure someone has posted about this before but I couldn't find it. Please link if you know.

I wrote generic code for `AbstractArray`s in my library, and use `similar` to construct arrays of the same container and eltype. All of the arrays I deal with are mutable.

However, it seems that there is weird behavior for `MArray`:

```julia
X = MMatrix{5,100}(rand(5, 100));
```

We can use `similar` just fine if we want the same array shape:

```julia
julia> typeof(similar(X))
MMatrix{5, 100, Float64, 500}
```

however, if I want a similar array to a **slice** of `X`, it gives me a regular `Vector`:

```julia
julia> typeof(similar(X, 100))
Vector{Float64}
```

If I try to use `@view` instead:

```julia
julia> typeof(similar(@view X[1, :]))
SizedVector{100, Float64, Vector{Float64}}
```

rather than an `MArray`. (Creating a copy with `X[1, :]` is too slow)

Why is this?

Thanks,
Miles

**Comment by MilesCranmer** [comment]
Okay it looks like I am able to get away with:
```
similar(X, axes(X, 2))
```
is this the right way to do it?

**Comment by mateuszbaran** [comment]
Yes, using axes is the preferred way to get a similar array of a different shape.

**Comment by MilesCranmer** [comment]
Thanks!
