### ISSUE TITLE
`Vec` not actually in `StaticArrays.FixedSizeArrays`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/StaticArrays.jl#118]
The docs claim falsely that `Vec` is in `StaticArrays.FixedSizeArrays`

**Comment by andyferris** [comment]
Which version of Julia and StaticArrays is this?

**Comment by dlfivefifty** [comment]
It's the actual code: https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/FixedSizeArrays.jl

No mention of `Vec`.

I noticed it in 0.5.1,  on master branch of StaticArrays

**Comment by SimonDanisch** [comment]
Woops, I might be the one to blame here!
Sorry, will get it back!

**Comment by SimonDanisch** [comment]
https://github.com/JuliaArrays/StaticArrays.jl/pull/119

**Comment by andyferris** [comment]
Resolved.
