### ISSUE TITLE
Move to PrecompileTools.jl ?

### ISSUE THREAD

**Issue by IanButterworth** [JuliaArrays/StaticArrays.jl#1184]
There are a few hardcoded precompile directives, 3 of which just broke on julia v1.11 (#1182) and disabled in #1183 

Perhaps PrecompileTools should be used instead?

**Comment by timholy** [comment]
Might be a good idea. Those might never have been functional, just deleting them altogether could be fine. As I'm sure you suspect, they were generated using the older `SnoopCompile.parcel` approach.

**Comment by IanButterworth** [comment]
See https://github.com/JuliaArrays/StaticArrays.jl/pull/1187
