### ISSUE TITLE
JET report_call issue

### ISSUE THREAD

**Issue by mestinso** [JuliaArrays/StaticArrays.jl#1225]
I ran into an issue found by JET.jl in some of my personal code when using StaticArrays. I asked about it on discourse (https://discourse.julialang.org/t/help-on-reported-jet-issue-when-using-staticarrays/107444) and the main feedback given was to report here.

Here is a minimum working example:
```
using JET
using StaticArrays

a=MVector(1,2,3,4,5)
b=MVector(6,7,8,9,10)
@report_call b[a.==2]
```
Gives the following:
![image](https://github.com/JuliaArrays/StaticArrays.jl/assets/11094799/a70c5f3c-e9e5-4897-b9f3-fa1fac973002)

Note that there are no issues with equivalent non static array code:
```
using JET

a=[1,2,3,4,5]
b=[6,7,8,9,10]
@report_call b[a.==2]
```

**Comment by jishnub** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/53015
