### ISSUE TITLE
Force specialization of `dimension_mismatch_fail()` on type parameter? 

### ISSUE THREAD

**Issue by trahflow** [JuliaArrays/StaticArrays.jl#1244]
Currently the function [`dimension_mismatch_fail(SA::Type, a::AbstractArray)`](https://github.com/JuliaArrays/StaticArrays.jl/blob/ff8ed9b64f41833fe22af81bd2859d5a0b9c3d18/src/convert.jl#L195C1-L197C4) does not specialize on the `SA` parameter, which makes code that uses StaticArrays inside GPU kernels incompatible (unless @inbounds is used in front of the constructor/convert statements).
See the discussion here: https://discourse.julialang.org/t/problems-with-linearalgebra-functions-within-kernelabstractions-and-cuda/97566/5

Would it be ok to force specialization on the `SA` parameter? I could provide a quick PR.

**Comment by mateuszbaran** [comment]
Resolved by #1245
