### ISSUE TITLE
LoladError: InterruptException

### ISSUE THREAD

**Issue by iajzenszmi** [JuliaArrays/StaticArrays.jl#1249]
(@v1.10) pkg> ERROR: LoadError: InterruptException:
Stacktrace:
 [1] include
   @ ./client.jl:489 [inlined]
 [2] addtests(fname::String)
   @ Main ~/.julia/packages/StaticArrays/EHHaF/test/runtests.jl:23
 [3] top-level scope
   @ ~/.julia/packages/StaticArrays/EHHaF/test/runtests.jl:45
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [5] top-level scope
   @ none:6
in expression starting at /home/ian/.julia/packages/StaticArrays/EHHaF/test/SDiagonal.jl:3
in expression starting at /home/ian/.julia/packages/StaticArrays/EHHaF/test/runtests.jl:33

**Comment by hyrodium** [comment]
Did you type ctrl+c? Did you get the error on clean environment? What's the output of `versioninfo()`?

**Comment by iajzenszmi** [comment]
_
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.2 (2024-03-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.10) pkg> add UpdateJulia
   Resolving package versions...
   Installed UpdateJulia ─ v0.4.4
    Updating `~/.julia/environments/v1.10/Project.toml`
  [770da0de] + UpdateJulia v0.4.4
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [682c06a0] + JSON v0.21.4
  [fd094767] + Suppressor v0.2.7
  [770da0de] + UpdateJulia v0.4.4
Precompiling project...
  3 dependencies successfully precompiled in 4 seconds. 192 already precompiled.

(@v1.10) pkg> using UpdateJulia
ERROR: `using` is not a recognized command. Type ? for help with available commands

(@v1.10) pkg> ^C

julia> update_julia()
ERROR: UndefVarError: `update_julia` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1

julia> using UpdateJulia

julia> update_julia()
installing the latest version of julia: 1.10.2
Success! `julia` & `julia-1.10` & `julia-1.10.2` now to point to 1.10.2
v"1.10.2"

julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, haswell)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

(@v1.10) pkg> add StaticArrays
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`

(@v1.10) pkg> test StaticArrays
     Testing StaticArrays
      Status `/tmp/jl_gsoagy/Project.toml`
  [4c88cf16] Aqua v0.8.4
  [6e4b80f9] BenchmarkTools v1.5.0
  [d360d2e6] ChainRulesCore v1.23.0
  [cdddcdb0] ChainRulesTestUtils v1.12.0
  [27aeb0d3] JLArrays v0.1.4
  [6fe1bfb0] OffsetArrays v1.13.0
  [aea7be01] PrecompileTools v1.2.1
  [90137ffa] StaticArrays v1.9.3
  [1e83bf80] StaticArraysCore v1.4.2
  [1986cc42] Unitful v1.19.0
  [b77e0a4c] InteractiveUtils
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [10745b16] Statistics v1.10.0
  [8dfed614] Test
      Status `/tmp/jl_gsoagy/Manifest.toml`
  [79e6a3ab] Adapt v4.0.4
  [4c88cf16] Aqua v0.8.4
  [6e4b80f9] BenchmarkTools v1.5.0
  [fa961155] CEnum v0.5.0
  [d360d2e6] ChainRulesCore v1.23.0
  [cdddcdb0] ChainRulesTestUtils v1.12.0
  [34da2185] Compat v4.14.0
  [26cc04aa] FiniteDifferences v0.12.31
  [0c68f7d7] GPUArrays v10.0.2
  [46192b85] GPUArraysCore v0.1.6
  [27aeb0d3] JLArrays v0.1.4
  [692b3bcd] JLLWrappers v1.5.0
  [682c06a0] JSON v0.21.4
  [929cbde3] LLVM v6.6.2
  [6fe1bfb0] OffsetArrays v1.13.0
  [69de0a69] Parsers v2.8.1
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [708f8203] Richardson v1.4.2
  [90137ffa] StaticArrays v1.9.3
  [1e83bf80] StaticArraysCore v1.4.2
  [fd094767] Suppressor v0.2.7
  [1986cc42] Unitful v1.19.0
  [dad2f222] LLVMExtra_jll v0.0.29+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [9abbd945] Profile
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.0+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.8.0+1
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
     Testing Running tests...
Test Summary: | Pass  Total  Time
test utils    |    6      6  0.3s
┌ Warning: macroexpand no longer throws a LoadError so `@test_throws LoadError ...` is deprecated and passed without checking the error type!
│   caller = test_expand_error(ex::Expr) at testutil.jl:30
└ @ Main ~/.julia/packages/StaticArrays/EHHaF/test/testutil.jl:30
Test Summary: | Pass  Broken  Total  Time
SVector       |  134       2    136  4.2s
Test Summary: | Pass  Broken  Total  Time
MVector       |  138       2    140  1.1s
Test Summary: | Pass  Broken  Total  Time
SMatrix       |  138       2    140  2.6s
Test Summary: | Pass  Broken  Total  Time
MMatrix       |  143       2    145  2.4s
Test Summary: | Pass  Broken  Total  Time
SArray        |  276       4    280  7.2s
Test Summary:     | Pass  Total  Time
some special case |   13     13  0.2s
Test Summary: | Pass  Broken  Total  Time
MArray        |  284       4    288  5.4s
Test Summary:     | Pass  Total  Time
some special case |   12     12  0.1s
Test Summary: | Pass  Total  Time
FieldVector   |   40     40  0.8s
Test Summary: | Pass  Total  Time
FieldMatrix   |   33     33  0.4s
Test Summary: | Pass  Total  Time
Scalar        |   11     11  0.8s
Test Summary: | Pass  Total  Time
issue #809    |    1      1  0.0s
Test Summary: | Pass  Total  Time
SUnitRange    |   13     13  0.2s
Test Summary: | Pass  Total  Time
SizedArray    |  133    133  4.4s
Test Summary:     | Pass  Total  Time
some special case |   12     12  0.3s
Test Summary: | Pass  Total  Time
SDiagonal     |   74     74  0.4s
Test Summary:     | Pass  Total   Time
SHermitianCompact |  907    907  12.1s
Test Summary: | Pass  Total  Time
[;;;;;]       |    8      8  0.1s
Skipping Base.active_repl
Skipping Base.active_repl_backend
Test Summary:    | Pass  Total  Time
Method ambiguity |    1      1  3.1s
Test Summary:           | Pass  Total  Time
Unbound type parameters |    1      1  0.1s
Test Summary:     | Pass  Total  Time
Undefined exports |    1      1  0.0s
Test Summary:                              | Pass  Total  Time
Compare Project.toml and test/Project.toml |    1      1  0.0s
Test Summary:      | Pass  Total  Time
Stale dependencies |    1      1  2.1s
Test Summary: | Pass  Total  Time
Compat bounds |    4      4  0.6s
Test Summary: |Time
Piracy        | None  0.0s
Test Summary:    | Pass  Total  Time
Persistent tasks |    1      1  5.9s
Possible type-piracy detected:
[1] similar(::Type{A}, shape::Tuple{Vararg{Union{Integer, Base.OneTo, SOneTo}}}) where A<:AbstractArray @ StaticArrays ~/.julia/packages/StaticArrays/EHHaF/src/abstractarray.jl:146
[2] similar(A::AbstractArray, ::Type{T}, shape::Tuple{Vararg{Union{Integer, Base.OneTo, SOneTo}}}) where T @ StaticArrays ~/.julia/packages/StaticArrays/EHHaF/src/abstractarray.jl:145
[3] to_indices(A, I::Tuple{Vararg{Union{Integer, CartesianIndex, StaticArray{<:Tuple, Int64}}}}) @ StaticArrays ~/.julia/packages/StaticArrays/EHHaF/src/indexing.jl:218
Test Summary: | Pass  Total  Time
Custom types  |    2      2  0.0s
Test Summary:     | Pass  Total  Time
Copy constructors |    1      1  0.0s
Test Summary:                    | Pass  Total  Time
Constructors of zero size arrays |    6      6  0.3s
Test Summary:                       | Pass  Total  Time
`real` and `float` of SArray/MArray |   17     17  0.1s
Test Summary:                   | Pass  Total  Time
convert with missing/wrong size |    3      3  0.0s
Test Summary:      | Pass  Total  Time
Unknow StaticArray |    2      2  0.0s
Test Summary:                        | Pass  Total  Time
constructor/convert from OffsetArray |    2      2  0.3s
Test Summary:                     | Pass  Total  Time
Core definitions and constructors |   98     98  0.8s
Test Summary:           | Pass  Total  Time
AbstractArray interface |  154    154  3.4s
Test Summary: | Pass  Total  Time
permutedims   |   11     11  0.6s
Test Summary:     | Pass  Total  Time
vcat() and hcat() |   30     30  0.0s
Test Summary: | Pass  Total  Time
Base.rest     |   22     22  0.5s
Test Summary:   | Pass  Total  Time
zeros/ones/fill |   12     12  0.2s
Test Summary: | Pass  Total  Time
Indexing      |  114    114  3.1s
Test Summary:          | Pass  Total  Time
Initialization with SA |   36     36  1.1s
Test Summary:                     | Pass  Total   Time
Map, reduce, mapreduce, broadcast |  119    119  14.2s
Test Summary: | Pass  Total  Time
sort          |   86     86  9.1s
Test Summary: | Pass  Total  Time
accumulate    |   64     64  6.9s
Test Summary: | Pass  Total  Time
Array math    |  445    445  4.4s
Test Summary:    | Pass  Total  Time
Scalar Broadcast |    9      9  0.4s
Test Summary:   | Pass  Total  Time
Broadcast sizes |   31     31  0.1s
Test Summary: | Pass  Total   Time
Broadcast     |  499    499  13.7s
Test Summary:                  | Pass  Total  Time
Broadcast with unknown wrapper |   24     24  0.4s
Test Summary:                 | Pass  Total  Time
instantiate with axes updated |    7      7  0.2s
Test Summary:           | Pass  Total  Time
`broadcast`'s stability |    6      6  1.7s
Test Summary:                       | Pass  Total  Time
broadcasting out-of-bounds getindex |    2      2  0.1s
Test Summary:  | Pass  Broken  Total   Time
Linear algebra |  266       1    267  17.2s
Test Summary:         | Pass  Total     Time
Matrix multiplication |  705    705  3m43.3s
Test Summary:       | Pass  Broken  Total     Time
matrix multiply-add |  276       3    279  2m40.3s
Test Summary:              | Pass  Total     Time
Testing different wrappers |  956    956  2m10.7s
Test Summary:                    | Pass  Total   Time
Triangular-matrix multiplication | 1392   1392  20.5s
Test Summary:                     | Pass  Total  Time
Triangular-Adjoint multiplication |  216    216  2.0s
Test Summary:                        | Pass  Total   Time
Triangular-triangular multiplication |  432    432  14.5s
Test Summary:              | Pass  Total   Time
Triangular-matrix division | 2592   2592  41.8s
Test Summary: | Pass  Total  Time
Determinant   |   48     48  6.8s
Test Summary:  | Pass  Total  Time
Matrix inverse |   10     10  4.0s
Test Summary:      | Pass  Total  Time
Matrix inverse 4x4 |    6      6  0.3s
Test Summary:      | Pass  Total  Time
Matrix inverse 5x5 |    3      3  0.3s
Test Summary:                 | Pass  Total  Time
Matrix inverse (Float64, 5×5) |    1      1  0.1s
Test Summary:                    | Pass  Total  Time
Matrix inverse (ComplexF64, 5×5) |    1      1  0.6s
Test Summary:                 | Pass  Total  Time
Matrix inverse (Float64, 8×8) |    1      1  0.9s
Test Summary:                    | Pass  Total  Time
Matrix inverse (ComplexF64, 8×8) |    1      1  1.6s
Test Summary:                   | Pass  Total  Time
Matrix inverse (Float64, 15×15) |    1      1  1.7s
Test Summary:                      | Pass  Total  Time
Matrix inverse (ComplexF64, 15×15) |    1      1  2.7s
Test Summary:                         | Pass  Total  Time
Moore–Penrose inverse (pseudoinverse) |   43     43  6.4s
Test Summary:         | Pass  Total     Time
Solving linear system |  132    132  3m09.2s
Test Summary:                        | Pass  Total   Time
Solving linear system (multiple RHS) |   48     48  13.7s
Test Summary: | Pass  Total  Time
Issue #1155   |    1      1  0.3s
Test Summary:            | Pass  Total  Time
Eigenvalue decomposition | 6980   6980  6.5s
Test Summary:      | Pass  Total  Time
Matrix exponential |   29     29  4.1s
Test Summary:      | Pass  Total  Time
Matrix square root |    7      7  0.3s
Test Summary:     | Pass  Total  Time
Lyapunov equation |    5      5  0.2s
Test Summary: | Pass  Total     Time
LU            | 2275   2275  1m00.4s
Test Summary:    | Pass  Total     Time
QR decomposition |  500    500  3m28.8s
Test Summary:       | Pass  Total  Time
QR method ambiguity |    3      3  0.1s
Test Summary:          | Pass  Broken  Total     Time
Cholesky decomposition | 3981      10   3991  2m14.8s
Test Summary:                       | Pass  Total  Time
Push, pop, pushfirst, popfirst, etc |   11     11  0.6s
Test Summary: | Pass  Total  Time
setindex!     |    1      1  0.2s
Test Summary: | Pass  Broken  Total  Time
setindex      |   26       2     28  0.2s
Test Summary:     | Pass  Total  Time
Iterators.flatten |   17     17  0.5s
Test Summary: | Pass  Total  Time
Binary IO     |   13     13  0.6s
Test Summary:     | Pass  Total   Time
SVD factorization |   60     60  30.7s
Test Summary: | Pass  Total  Time
Unitful       |    2      2  0.2s
Test Summary:          | Pass  Total   Time
ChainRules Integration |   79     79  12.2s
     Testing StaticArrays tests passed 

(@v1.10) pkg> 

ulia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, haswell)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

**Comment by hyrodium** [comment]
>(@v1.10) pkg> add UpdateJulia

[UpdateJulia.jl](https://github.com/LilithHafner/UpdateJulia.jl) is deprecated, so it seems better to avoid that installation.

I couldn't find a way to reproduce the `InterruptException` error from your comments, so I will close this issue. If you have any additional comments, please include a natural language description as well as logs.
