### ISSUE TITLE
Readme still contains an example of indexing using a tuple

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#129]
From the quickstart guide:
```julia
v1 = SVector(1, 2, 3)
v1[(3,2,1)] === @SVector [3, 2, 1]
```
now results in
```
ERROR: ArgumentError: invalid index: (3, 2, 1)
Stacktrace:
 [1] getindex(::StaticArrays.SVector{3,Int64}, ::Tuple{Int64,Int64,Int64}) at ./abstractarray.jl:875
```

**Comment by andyferris** [comment]
Oh bugger. The README is a bit disorganized, sometimes I forget to update things.

We've moved to indexing using static arrays `v1[SVector(3,2,1)]` rather than tuples. The method we used before could be considered (a) type piracy and (b) more suitable for constructing a tuple, not a static vector.
