### ISSUE TITLE
SVector + Vector: Julia 0.5 vs 0.6

### ISSUE THREAD

**Issue by krcools** [JuliaArrays/StaticArrays.jl#131]
Not sure if this is by design or not but I noticed that on julia-0.5 a `SVector` added to an `Array` results in an `SVector`, wheras on julia-0.6 it results in an `Array`.

**Comment by c42f** [comment]
Yes, these were dropped in #121 (see the description), but perhaps they should be reimplemented.

It should be very easy to implement the map-like operations again, I'll have a go at that first.

**Comment by andyferris** [comment]
I support reimplementing these.

**Comment by c42f** [comment]
Started in #136

**Comment by c42f** [comment]
Fixed in #136 (see also #140)
