### ISSUE TITLE
broadcast is ambiguous with base

### ISSUE THREAD

**Issue by Keno** [JuliaArrays/StaticArrays.jl#132]
This method: https://github.com/Keno/StaticArrays.jl/blob/master/src/broadcast.jl#L7
is ambiguous with base:

```
MethodError: broadcast(::Optim.UnivariateProblems.##1#3, ::Float64) is ambiguous. Candidates:
  broadcast(f, a::Union{Number, StaticArrays.StaticArray}, b::Union{Number, StaticArrays.StaticArray}...) in StaticArrays at /global/cscratch1/sd/kfischer/celeste-pkgs/v0.6/StaticArrays/src/broadcast.jl:8
  broadcast(f, x::Number...) in Base.Broadcast at broadcast.jl:16
```
that's bad form

**Comment by timholy** [comment]
The problem here is that Base broadcast requires zero or more arguments whereas here it requires one or more. Presumably just need to get rid of the `a` argument and start straight with `b`, since `Union{A,B}` should always be less specific than `A`.

Overall, `detect_ambiguities` picks up 72 ambiguities when `StaticArrays` is loaded. The good news is that `Base.Dates` seems to no longer be a source of trouble.

**Comment by andyferris** [comment]
This is due to a recent PR by @tkelman: https://github.com/JuliaArrays/StaticArrays.jl/pull/126/files

I suspect we should role back that particular change for `broadcast`?

**Comment by marius311** [comment]
Just ran into this also. Can't say I'm following closely enough to understand why the two separate `a,b` args were needed in the PR mentioned above, but if you want to keep that, you could use the following trick, 

```julia
function broadcast(f, a::Union{_, Number, StaticArray}, b::Union{_, Number, StaticArray}...) where {_<:StaticArray}
```

this will *only* match when there's at least one StaticArray present among the args, so there's not even a question of if its more specific.

**Comment by marius311** [comment]
(See also https://discourse.julialang.org/t/incorrect-ambiguity/2690 since this trick/hack doesn't always work, granted I just checked it does in this case)

**Comment by andyferris** [comment]
Thanks @marius311 - that's a very interesting observation.

**Comment by dlfivefifty** [comment]
Even `exp.(1.0+2.0im)` triggers this....

**Comment by dlfivefifty** [comment]
How would you feel about this (less than elegant) work around for low number of arguments:
``julia
@propagate_inbounds broadcast(f, a::StaticArray, b::Union{Number, StaticArray}...) = _broadcast(f, broadcast_sizes(a,b...), a, b...)
@propagate_inbounds broadcast(f, n1::Number, a::StaticArray, b::Union{Number, StaticArray}...) = _broadcast(f, broadcast_sizes(n1,a,b...), n1, a, b...)
@propagate_inbounds broadcast(f, n1::Number, n2::Number, a::StaticArray, b::Union{Number, StaticArray}...) = _broadcast(f, broadcast_sizes(n1,n2,a,b...), n1, n2, a, b...)
```

**Comment by andyferris** [comment]
Does #135 work for you @dlfivefifty?

**Comment by dlfivefifty** [comment]
Yep, it does!

**Comment by c42f** [comment]
I assume this is sorted now out via #135.

By the way @marius311 that's a really nice trick. I've used in #136 which would otherwise seem intractable in general.
