### ISSUE TITLE
hcat type promotion

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#155]
```julia
using StaticArrays
m1 = rand(SMatrix{1, 1, Float32})
m2 = rand(SMatrix{1, 1, Float64})
[m1 m2]
```
results in
```
1×2 StaticArrays.SArray{Tuple{1,2},Float32,2,2}:
 0.594061  0.283404
```
Should be a `Float64` matrix.

**Comment by andyferris** [comment]
So base uses `promote_type` for this purpose (not `typejoin`)?

**Comment by tkoolen** [comment]
https://github.com/JuliaLang/julia/blob/d7a5b5acffbe52f8221fd06b94908074abac5586/base/sparse/sparsevector.jl#L972 (for some reason it's in `sparsevector.jl`), uses `promote_eltype`, which calls `promote_type`, yes.

**Comment by andyferris** [comment]
OK I've got a fix for this
