### ISSUE TITLE
Matrix exponential

### ISSUE THREAD

**Issue by Godisemo** [JuliaArrays/StaticArrays.jl#159]
Is there any plan on adding support for matrix exponential in StaticArrays?

**Comment by Godisemo** [comment]
I guess for now it is possible to just add
```
@inline Base.expm{T<:StaticMatrix}(x::T) = T(expm(Array(x)))
```
for convenience, but I would assume it is possible to perform matrix exponential in a more efficient manner for very small matrices.

**Comment by andyferris** [comment]
We'd love to!

PRs welcome, of course :)

One holdup is on deciding on a viable algorithm. For small matrices, it's possible that the ideal approach is analytical, perhapshelped by some kind of decomposition like LU. We have eigenvalues for small hermitian matrices. Thoughts, anyone?

**Comment by Godisemo** [comment]
For 2x2 matrices you could do as described on http://mathworld.wolfram.com/MatrixExponential.html

```julia
function Base.expm(A::SMatrix{2,2})
  a, c, b, d = A.data
  Δ = sqrt((a-d)^2 + 4*b*c)
  m11 = exp((a+d)/2)*(Δ*cosh(Δ/2)+(a-d)*sinh(Δ/2))
  m12 = 2*b*exp((a+d)/2)*sinh(Δ/2)
  m21 = 2*c*exp((a+d)/2)*sinh(Δ/2)
  m22 = exp((a+d)/2)*(Δ*cosh(Δ/2)+(d-a)*sinh(Δ/2))
  SMatrix{2,2}(m11, m21, m12, m22) / Δ
end
```

It might not be optimal, but still 150x faster than using `expm(::Array)` in my benchmarks.

**Comment by Godisemo** [comment]
This version is slightly faster, about 230x faster than `expm(::Array)`

```julia
function my_expm(A::SMatrix{2,2})
  a, c, b, d = A.data
  Δ = sqrt((a-d)^2 + 4*b*c)
  C1 = exp(0.5*(a+d))
  C2 = sinh(0.5*Δ)
  C3 = cosh(0.5*Δ)
  m11 = C1*(Δ*C3+(a-d)*C2)
  m12 = 2*b*C1*C2
  m21 = 2*c*C1*C2
  m22 = C1*(Δ*C3+(d-a)*C2)
  SMatrix{2,2}(m11, m21, m12, m22) / Δ
end
```

Note that I did not consider the special case when Δ goes to 0, not sure how to handle this. Numerical stability and all that...

**Comment by cdsousa** [comment]
FYI, https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/30 and https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/677cc5540ce175f7bbb9f8fd05b539ba3bf52c39/src/expm.jl

**Comment by c42f** [comment]
Ah great, thanks a lot for the reminder that @mschauer already implemented these for 2x2 and 3x3 (and 1x1 :-) ) in FixedSizeArrays.  We should definitely port those over.

I wonder how it compares to the version above.  As usual in StaticArrays, I'm happy to go for a super-fast-and-moderately-stable option over slow-but-stable (it's always possible to call the Base `expm` for something slower and more reliable).

**Comment by Godisemo** [comment]
I did a PR (#160) for 1x1 and 2x2, don't know why it didn't show up automatically here.

**Comment by mschauer** [comment]
Let's keep this issue open to track 3x3 matrix exponential efforts. The 3x3 symmetric case is easily ported from FixedSizeArrays, for the 3x3 asymmetric maybe it is worthwhile to aim for a repeated squaring solution.
