### ISSUE TITLE
MVector allocates more memory then Vector in 0.6 inside a Struct

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaArrays/StaticArrays.jl#169]
Consider these two structs (immutable in 0.6):
```
struct Point1 #with native vectors
         state    :: Vector{Float64} 
         dstate   :: Vector{Float64} 
         ct       :: Vector{Float64} 
         id       :: Int64 
         ptype    :: Int64 
  end

struct Point1b # with MVector
         state    :: MVector{3,Float64} 
         dstate   :: MVector{3,Float64}
         ct       :: MVector{3,Float64} 
         id       :: Int64 
         ptype    :: Int64 
       end
```
Now upon benchmarking, I found that the MVector version allocated more memory and was slower. Am I doing something wrong here ? or is this due to Julia 0.6 ? I was expecting the MVector version to be faster and use less memory.

```
using BenchmarkTools
r = rand(3)
v = rand(3)
ct = rand(3) 

julia> @benchmark Point1(r,v,ct,1,1)
BenchmarkTools.Trial: 
  memory estimate:  48 bytes
  allocs estimate:  1
  --------------
  minimum time:     91.134 ns (0.00% GC)
  median time:      94.834 ns (0.00% GC)
  mean time:        99.265 ns (3.08% GC)
  maximum time:     1.890 μs (92.22% GC)
  --------------
  samples:          10000
  evals/sample:     925

julia> @benchmark Point1b(r,v,ct,1,1)
BenchmarkTools.Trial: 
  memory estimate:  144 bytes
  allocs estimate:  4
  --------------
  minimum time:     124.275 ns (0.00% GC)
  median time:      128.423 ns (0.00% GC)
  mean time:        146.278 ns (10.28% GC)
  maximum time:     3.302 μs (92.91% GC)
  --------------
  samples:          10000
  evals/sample:     825

```
My Versioninfo:

```
Julia Version 0.6.0-rc1.3
Commit c302d75 (2017-05-14 09:56 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

thanks

**Comment by KristofferC** [comment]
Firstly, use `$` to benchmark like:

```
julia> @btime Point1($r,$v,$ct,1,1);
  10.806 ns (1 allocation: 48 bytes)

julia> @btime Point1b($r,$v,$ct,1,1);
  35.084 ns (4 allocations: 144 bytes)
```

Secondly, why would `MVector` be faster here. All you do is wrapping existing arrays, not doing any computations.

**Comment by GravityAssisted** [comment]
I was actually doing some calculations too, which I did not show above. The slowdown seems to be coming because I am calling the constructor millions of time and then performing calculations. I am creating a large (~1 million) array of Points.

I am still little unsure as to why MVector need more memory ?  I am under the impression (possibly wrong one) that more memory allocation leads to slower performance.

I am trying to decide if using MVector is a good choice in this context. We are starting to develop a new software package in Julia and doing some benchmarking to make software architecture decisions.

**Comment by KristofferC** [comment]
You are converting from a normal `Vector` to an `MVector` which will cost one allocation per conversion. Why don't you use `MVector`s from the start?

**Comment by KristofferC** [comment]
Also for points in low dimensions you really should be using `SVector`s.

**Comment by GravityAssisted** [comment]
@KristofferC I see, you are correct. I was not using MVector for r, v and ct. It now gives the same allocation as the original Vector version.

From my understanding, I can't use SVector because, my calculations are changing the values in these points. r and v change during those calculations. The Point struct itself can be immutable. 

Do you have a way that I can make them SVector?

**Comment by andyferris** [comment]
You could do it the other way around - make the `Point` struct mutable, with immutable `SVector`s? This would make 1/3 allocations.

I often find you can always find an efficient way to use the immutable version of things like `Point`. Perhaps it would be a bit tricky to get optimal speed in this case...

**Comment by GravityAssisted** [comment]
Thanks @andyferris . Can you explain a little more on how that solution would work ? I am not seeing how making the Point mutable while making r,v ```SVector``` will solve the problem ? How would I change r,v field during my calculations ?

Pardon my noob'ness, I am experienced Fortran programmer, recent Julia user.

**Comment by andyferris** [comment]
So, to give you some information on how Julia handles memory, mutable structs and `MVector`s are implemented in Julia as a reference (i.e. a pointer that will be automatically garbage collected when necessary) to some other piece of memory. It gets even worse, because Julia is still not "finished", if you use `MVector` inside an (immutable) struct, then you get also get that struct *implemented* as another heap allocated object in its own right. So every `Point1` or `Point1b` you create means that 4 objects are allocated to the heap and 4 objects must be tracked and cleaned up by the garbage collector. Furthermore, as another arcane implementation detail, I think that the allocator has distinct behavior for `Array` (thus also `Vector`) which might make allocating `Vector` sometimes faster than `MVector` (even though it otherwise requires more run-time memory and logic).

**Comment by GravityAssisted** [comment]
@andyferris thanks a lot. Thats make is clear. Its tricky.
So If I make the Point mutable and r,v as ```SVector```s then, I would have to reallocate them every time I change them right?

**Comment by andyferris** [comment]
Noob'ness is fine; questions are welcome.

So I generally replace entire `SVector`s at a time, rather than worrying about their elements. For example, this displaces the `state` vector and doubles `dstate`, and is efficient:
```julia
mutable struct Point
    state::SVector{3,Float64} 
    dstate::SVector{3,Float64} 
    ...
end

# Get some data
p::Point

p.state = p.state + SVector(1.0, 2.0, 3.0)
p.dstate *= 2
```
You'll get much more succinct code by following a "functional" interface for `SVectors`, rather than trying to worry about their individual elements.

**Comment by andyferris** [comment]
> So If I make the Point mutable and r,v as SVectors then, I would have to reallocate them every time I change them right?

That's right - in my example above, `p.state` is brought to the stack (or registers) as 3 `Float64`s, added with some literals, and copied back to the heap. Often AVX/SSE is invoked so the copies are fast, and definitely the addition makes good use of vectorization, so it's pretty much optimal.

One unfortunate fact is that your 10^6 mutable points have to be individually heap allocated. So `Vector{Point}(1_000_000)` contains one million pointers (initialized as `#undef` in this case), and there is double indirection. 

(A way of replacing parts of immutable structs inside of arrays is being actively considered/developed by the core Julia guys *right now*, so this problem will disappear before Julia v1.0 letting `Point` also be `immutable` and fast.)

However, if you typically modify `state`, `dstate`, `ct`, etc all at once, then it is *perfectly* efficient right now to make `Point` also immutable, and do:
```julia
points::Vector{Point}

for i = 1:length(p)
    p = points[i]
    p2 = f(p) 
    points[i] = p2
end

# equivalent to `map(f, points)`
```
I think you'll find this will make things much faster.

**Comment by GravityAssisted** [comment]
Ah thanks @andyferris . This make it clear. I do update the whole point structure all at once. So your suggestion of making them both immutable should work. The only thing is if I make both point and and its field immutable, I need to use following syntax to update:

``` 
points[i] = Point1c(SVector(value,value,value),SVector(value,value,value),SVector(value,value,value),IntValue,IntValue)
```

But this should be efficient. Thanks a lot for your patience and help.

**Comment by andyferris** [comment]
No worries! With practice, this will seem natural. 

Do you consider this resolved?

**Comment by c42f** [comment]
> The only thing is if I make both point and and its field immutable, I need to use following syntax to update ...

It doesn't necessarily need to be that ugly, as (depending on the circumstances) you may be able to use very high level abstractions and not pay a performance hit.  For example:

```julia
s = points[i].state
ds = points[i].dstate

s += ds
ds = my_func(s, ds)
ct = 1 - ct.^2

state[i] = Point(s,ds,ct,state[i].id, state[i].ptype)
```

Of course, the detail here is just made up nonsense, but the the general idea is that you might be able to avoid working with the components of the state completely, depending on what you're doing.  At the moment, it is annoying to have to copy things like `id` back into the new mutated slot `points[i]`, but as Andy says, the core language devs are working on some new syntax right now to make this a lot smoother.

**Comment by GravityAssisted** [comment]
@c42f Thanks for the tip. From my past experience with Julia, I have always been afraid working with Vectors as a whole. My applications are very performance sensitive and previously working with vectors as a whole resulted in a ton of memory allocations. I think this may have improves in the Julia 0.6.

**Comment by GravityAssisted** [comment]
@andyferris Sure, I will close this now.
