### ISSUE TITLE
Broadcast inconsistency with Base

### ISSUE THREAD

**Issue by bshall** [JuliaArrays/StaticArrays.jl#197]
I was writing a few tests for `broadcast` and I noticed an inconstancy. In Base you can broadcast a 2x2 array with a 1x2 array as follows
```julia
broadcast(+, eye(2), [1  4])
```
But the equivalent in `StaticArrays` gives a `DimensionMismatch` error
```julia
broadcast(+, eye(SMatrix{2, 2}), @SMatrix([1  4]))
```

**Comment by andyferris** [comment]
Yes, lets fix that...
