### ISSUE TITLE
`sum(f, vs)` is slow

### ISSUE THREAD

**Issue by DNF2** [JuliaArrays/StaticArrays.jl#209]
I'm on 0.6.0-rc2.0, and the master version of `StaticArrays`. It seems that `sum(::Function, ::StaticArray)` calls the generic `mapreduce` instead of the `StaticArrays` one:

```
using StaticArrays, BenchmarkTools
vs = SVector(1.0, 2.0, 3.0);

julia> @btime sum($vs);
  1.457 ns (0 allocations: 0 bytes)

julia> @btime sum(abs2, $vs);
  38.537 ns (2 allocations: 48 bytes)

julia> @btime mapreduce(abs2, +, $vs);
  1.739 ns (0 allocations: 0 bytes)

julia> @btime sumabs2($vs);
  1.746 ns (0 allocations: 0 bytes)
```

**Comment by fredrikekre** [comment]
Seems like an issue for the [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl) repo.

**Comment by DNF2** [comment]
Is this not it?

**Comment by fredrikekre** [comment]
Yea sorry, misread.

**Comment by fredrikekre** [comment]
FWIW the correct method is called (finally), the issue is that [the metod in base](https://github.com/JuliaLang/julia/blob/ef9ab602b0307afb9fa21f2323e2abf4b244ad41/base/reduce.jl#L347) is not inlined.

**Comment by andyferris** [comment]
Yeah there is a few of those...
