### ISSUE TITLE
copy(::MMatrix) returns ::SMatrix

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#214]
on v0.5
```
J = rand(3,3); MJ = MMatrix{3,3}(J); test = copy(MJ)
```
Even though MJ is MMatrix, `test` is SMatrix

**Comment by c42f** [comment]
This is happening because `copy` now uses `similar_type` which is the tool used to deduce the output type in most circumstances in StaticArrays.  `similar_type` produces immutable types, because these are a lot more efficient (the mutable types necessarily perform memory allocation, at least in julia-0.6).

Whether this makes sense depends on what you're using it for. It is consistent with other functions, for example, adding to `MVectors` will produce an `SVector`.

**Comment by Datseris** [comment]
okay, did not know that. I thought it was an error, so my mistake. I know how to get around it for my usage.

**Comment by andyferris** [comment]
Is that `test = Marray(MJ)`?

Not sure about `copy` here - I guess it's useful for "defensive" copies but not the usual "make a copy that I want to mutate" sort. Note this is also an issue in `Base`.

**Comment by Datseris** [comment]
no the test is `test::SMatrix` (the immutable kind, on ForwardDiff 0.5)

**Comment by c42f** [comment]
> I thought it was an error, so my mistake

Having copy return an `SArray` is not exactly an error, but it might be an (API) mistake. It's definitely different from some earlier versions of StaticArrays where we preserved mutability through more of the operations.

For operations like `+` it makes sense to turn mutable into immutable, but maybe copy is different.

* There's no point calling `copy` when you know you have an immutable `StaticArray`, as the original and the copy will always be the same.
* If you have a mutable `StaticArray`, you might want to return a mutable or immutable copy, depending on how the algorithm is constructed.
* If an algorithm is written with `Base.Array` in mind, it may or may not work, depending again on how the algorithm is constructed.

It's quite common to see the following pattern for implementing an operation `foo` in terms of an in-place version `foo!`:

```julia
foo!(a) = #= ... =#
foo(a) = foo!(copy(a))
```

To the extent that we'd like `MArray` to work with this, I suppose we should be returning a mutable version from `copy()`?  Thoughts?

**Comment by Datseris** [comment]
I personally feel like `copy` should return the same Type...

**Comment by andyferris** [comment]
> I personally feel like `copy` should return the same `Type`...

This probably makes the most sense, after all this would be closer to the meaning in English (vs. say, `similar`). Also - easy to implement:

```julia
@inline copy(a::StaticArray) = typeof(a)(Tuple(a))
```

(hint - PRs with tests welcome :) )
