### ISSUE TITLE
inv not unrolled for Mat{4,4}

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaArrays/StaticArrays.jl#220]
Is there a reason that https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/f1b3ec2bfbf376345fa28c863a20301498f0e337/src/ops.jl#L234 didn't make it into StaticArrays?

I could open a PR. It's twice as fast and doesn't destroy my immutable only pipeline ;)

**Comment by c42f** [comment]
Not a reason I know about.  Did you check accuracy?

**Comment by andyferris** [comment]
Generally, it would be wonderful to have some more of this code from *FixedSizeArrays* :) I've been to lazy to do the porting myself...

**Comment by mschauer** [comment]
Close
