### ISSUE TITLE
Feature request: Allow syntax @SVector 2:N-1

### ISSUE THREAD

**Issue by DNF2** [JuliaArrays/StaticArrays.jl#223]
The `@SVector` macro currently supports functions like `rand`, `fill` and so on. Is it possible to support `StepRange`s? For example, could
```
ind = @SVector 2:2:N-1
```
where `N` is a type parameter, be allowed?

One use case would be convenient slicing of `SArray`s, as discussed [here](https://discourse.julialang.org/t/efficiently-selecting-parts-of-a-staticarray/4173), without the need for writing a custom function for each different slice.

This request might be a special case of the comprehension syntax, which cannot currently make use of type parameters.

**Comment by andyferris** [comment]
Yes, I think some way of doing this should be provided.

Unless we can find an easy shortcut, the roadmap in my head is:

 * Add a static unit range type, which is returned from e.g. `indices(::SVector)`. This would be a dataless "singleton"
 * Maybe add another static step range type. With a pure constructor we can have `SStepRange(2,2,N-1)` deal with type parameters at run-time. The biggest problem here is actually the `N-1`...
 * Define conversions from these to SVector
 * Make the macro do this / define a new `@SA` macro that does multiple things.

For now, I would define an extra pure function this way:

```julia
Base.@pure function myrange(N::Int)
    r = 2:2:N-1
    SVector((r...))
end

a[myrange(N)]
```

**Comment by c42f** [comment]
I think this is basically a dup of #97 / #26
