### ISSUE TITLE
`diag` does not produce SVector for SMatrix

### ISSUE THREAD

**Issue by wsshin** [JuliaArrays/StaticArrays.jl#224]
I think `diag(A)` (and also `diag(A, Val{n})`) can be written to produce an `SVector` for an `SMatrix` `A`.  Is there a plan for implementing this?  Currently it does not produce an `SVector`.

```julia
julia> VERSION
v"0.6.0-rc3.0"

julia> using StaticArrays

julia> A = @SMatrix rand(3,3)
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9}:
 0.982833  0.294026  0.107362
 0.537241  0.507196  0.859835
 0.932861  0.410198  0.0933879

julia> diag(A)
3-element Array{Float64,1}:
 0.982833
 0.507196
 0.0933879
```

**Comment by dpsanders** [comment]
It's currently using a generic fallback:
```
julia> @which diag(A)
diag(A::AbstractArray{T,2} where T) in Base.LinAlg at linalg/dense.jl:250
```

A possible implementation is the following, but I have no idea if it's performant:
```jl
julia> A = @SMatrix rand(3,3)
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9}:
 0.524023  0.561465  0.903208
 0.479735  0.461542  0.094898
 0.77266   0.535001  0.414256

julia> Base.diag(A::SMatrix) = @SVector [A[i,i] for i in 1:size(A, 1)]

julia> diag(A)
3-element SVector{3,Float64}:
 0.524023
 0.461542
 0.414256
```

**Comment by dpsanders** [comment]
Seems like it should be performant.

**Comment by wsshin** [comment]
Thanks, @dpsanders!  Inspired by your suggestion, I posted a PR implementing `diag(A, Val{k})`: https://github.com/JuliaArrays/StaticArrays.jl/pull/226.

**Comment by c42f** [comment]
Yes thanks! It's good to have yet one more expected feature from base in `StaticArrays` too :-)
