### ISSUE TITLE
a Diagonal of a SVector doesn't keep its type 

### ISSUE THREAD

**Issue by yakir12** [JuliaArrays/StaticArrays.jl#235]
First seen [here](https://discourse.julialang.org/t/how-to-scale-coordinates-in-coordinatetransformations-jl/4394?u=yakir12):
```julia
julia> m = SVector(1,2,3)
3-element SVector{3,Int64}:
 1
 2
 3

julia> x = Diagonal(m)
3×3 Diagonal{Int64}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

julia> x.diag
3-element Array{Int64,1}:
 1
 2
 3
```

**Comment by fredrikekre** [comment]
Thats by definition of [`Diagonal` in `Base`](https://github.com/JuliaLang/julia/blob/8915d9b3384d5ffbafeb83974c267d983f4cb07d/base/linalg/diagonal.jl#L5-L7), it is always a `Vector`.

**Comment by yakir12** [comment]
I see.

**Comment by fredrikekre** [comment]
Could perhaps define an unexported `Diagonal` in `StaticArrays`. Something like:
```julia
struct Diagonal{T, N}
    diag::SVector{N, T}
end
Base.Diagonal(v::SVector) = Diagonal(v)
```

```julia
julia> m = SVector(1,2,3)
3-element SVector{3,Int64}:
 1
 2
 3

julia> Diagonal(m)
StaticArrays.Diagonal{Int64,3}([1, 2, 3])
```
Perhaps too many additional methods are needed to make this usable though.

**Comment by c42f** [comment]
Oh, thanks for pointing this out.  It's another of many places in `Base.LinAlg` where things don't work quite right if you're using `StaticArrays`.

Obviously it's best to fix Base for 0.7, though I guess as a rather nasty hack, we could overload `Diagonal(::StaticArray)` to return our own special `StaticArrays.Diagonal`.  Hmm.

**Comment by c42f** [comment]
Or we could just define `SDiagonal` for now.

**Comment by yakir12** [comment]
The only objective I'd care about, as a user, is the performance and ease of use. So aesthetics aside, `SDiagonal` sounds great.

**Comment by c42f** [comment]
Yes, `SDiagonal` is probably the best option for clarity, until `Base.Diagonal` can support a static vector. Hijacking the `Diagonal` constructor might still be worth it: it's a bit evil, but probably less of a surprise to users than silently allocating data.  If they really want a normal `Diagonal`, they can get it explicitly with `Diagonal(collect(sa))` for some static array `sa`.  It will require reimplementing a bunch of stuff from Base, as usual, but it's probably not that hard if we just go through and port the required pices from `base/linalg/diagonal.jl` (PR's welcome ;-))

**Comment by yakir12** [comment]
The only objective I'd care about, as a user, is the performance and ease of use. So aesthetics aside, `SDiagonal` sounds great.

**Comment by mschauer** [comment]
@getzdan is working on a port of https://github.com/mschauer/Bridge.jl to use StaticArrays and added relevant code, see
https://github.com/getzdan/Bridge.jl/blob/390c6cd9f3adc9abb16b4b8e3b3abb0ec3fd35f7/src/diagonal.jl

**Comment by andyferris** [comment]
`SDiagonal` now exists.
