### ISSUE TITLE
enfolding away much of a frequent conversion

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaArrays/StaticArrays.jl#236]
Is there any reason *not* to use this approach?

```julia
# unfold the parameter `S` just-in-time (this should precede runtime)

@inline function (::Type{SVector})(x::A) where A<:AbstractVector{T} where T =    
    SVector{length(x)}(x)

@inline function (::Type{SArray})(x::A) where A<:AbstractArray{T,N} where T where N =    
    SArray{Tuple{size(x)...}}(x)
```

**Comment by andyferris** [comment]
Yes, this is very much done on purpose. :)

I do agree that this is annoying. However, if it were this easy at the REPL almost everyone who was starting out with *StaticArrays* would begin to use this in their code, and the resulting type instabilities would render it significantly slower than just using `Base.Array` (and of course the whole point of using this library is for speed).

(I think there might be a section of the README discussing this also).

**Comment by JeffreySarnoff** [comment]
This runs fast and requires remembering less.
Is it type foolproof? If so, is it a good idea?

```
@inline function svector(vec::V) where V<:AbstractVector{T} where T
    return @SVector V[vec]
end

# a belt and suspenders approach

@inline function svector(vec::V) where V<:AbstractVector{T} where T
    V <: SVector && return vec  
    return @SVector V[vec]
end
```
