### ISSUE TITLE
element-wise `isequal` on SArray of non-numeric entries does not produce SArray of Bool.

### ISSUE THREAD

**Issue by wsshin** [JuliaArrays/StaticArrays.jl#239]
When `isequal` is applied element-wise to `SArray`s of numeric entries, we get `SArray`s of `Bool`
```julia
julia> VERSION
v"0.6.1-pre.0"

julia> v_int = @SVector([1,2,3])
3-element SVector{3,Int64}:
 1
 2
 3

julia> v_int .== 1
3-element SVector{3,Bool}:
  true
 false
 false
```

However, when `isequal` is applied element-wise to `SArray`s of non-numeric entries, we do not get `SArray`s of `Bool`, as shown in the following example with enumeration:
```julia
julia> @enum Axis X Y Z

julia> v_enum = @SVector([X,Y,Z])
3-element SVector{3,Axis}:
 X
 Y
 Z

julia> v_enum .== X
3-element BitArray{1}:
  true
 false
 false
```

Another example with a custom type:
```julia
julia> immutable MyType
           n::Int
       end

julia> m1 = MyType(1); m2 = MyType(2); m3 = MyType(3);

julia> v_mytype = @SVector([m1,m2,m3])
3-element SVector{3,MyType}:
 MyType(1)
 MyType(2)
 MyType(3)

julia> v_mytype .== m1
3-element BitArray{1}:
  true
 false
 false
```

Is this fixable?  If it is, where?  Probably in `src/broadcast.jl`?

**Comment by andyferris** [comment]
Yeah, I'm using the "old" way of overloading broadcast, where scalars are `Number`.

`Base` now has some generic way of hooking into broadcasting via a bunch of methods - but I don't really understand it very well! You're welcome to look into it, of course (and yes our implementation is in `src/broadcast.jl`).

**Comment by wsshin** [comment]
Thanks.  Currently this is not urgent for my project.  If the support for this feature becomes critical to my project, I will look into it!

**Comment by c42f** [comment]
Base has `Broadcast.containertype()` and `Broadcast.promote_containertype()` which tries to figure out the correct container type. They're probably technically not public interfaces, but I guess we should hook into these.
