### ISSUE TITLE
Broadcast assignment for Mutable Vectors/Arrays

### ISSUE THREAD

**Issue by chriselrod** [JuliaArrays/StaticArrays.jl#249]
Tested on both v0.6.1 and master:
```julia
using StaticArrays
mv = MVector{50}(randn(50));
ma = MMatrix{5,5}(randn(5,5));
x = rand(50);
y = randn(5,5);
mv .= log.(x);
ma .= exp.(y);
all(mv .== log(x[1]))
all(ma .== exp(y[1]))
```
Returns (and is) true, while
```julia
all(mv .== log.(x))
all(ma .== exp.(y))
```
Returns (and is) false.

**Comment by c42f** [comment]
This seems to be specific to the particular case of mixing static arrays with dynamically sized arrays:

```julia
julia> mv = zeros(MVector{2})
2-element MVector{2,Float64}:
 0.0
 0.0

julia> mv .= 1:2 # yikes, what.
2-element MVector{2,Float64}:
 1.0
 1.0

julia> mv .= SVector(1,2) # works
2-element MVector{2,Float64}:
 1.0
 2.0
```

**Comment by c42f** [comment]
Does #252 do the trick for you?

**Comment by chriselrod** [comment]
Indeed! Thanks.
I already went in and replaced all the broadcasts with loops, but it broadcasting is normally faster.
Perhaps the advantage will be much smaller with the lazy solution, but for a MVector{10} the advantage of broadcasting (using a static array instead of a dynamically sized array) vs a loop is about 4 fold (24 vs 6 ns). Even if smaller, and certainly not the bottleneck in my code, nice to see a fix!
(More importantly to patch things for other users not aware of the current need to avoid broadcasts in this circumstance.)

**Comment by c42f** [comment]
Great, the fix I've got there is not a perfect solution, but it prevents other people from encountering this rather nasty bug.  If you know the sizes of your non-static arrays on the right hand side, you can go the StaticArrays fast path by wrapping them in SizedArray:

```
mv = zeros(MVector{2})
mv .= Size(2)([1,2])

# Compare the generated code:
foo(mv, A) = (mv .= A)
@code_native foo(mv, Size(2)([1,2]))
# vs
@code_native foo(mv, [1,2])
```

It should be possible to achieve better codegen in the second case, but this isn't addressed by #252 (hence the TODO in that PR)

**Comment by c42f** [comment]
Thanks for the bug report, and sorry for the nasty surprise!

**Comment by c42f** [comment]
(ie, that the bug crept through testing.  I've added test cases so this shouldn't happen again.)
