### ISSUE TITLE
Surprising behaviour of `rand(SVector(1,2))`

### ISSUE THREAD

**Issue by DNF2** [JuliaArrays/StaticArrays.jl#277]
I was surprised by this behaviour:
```
julia> rand(SVector(1,2))
2-element SVector{2,Int64}:
  3088619120667732393
 -1551417525745515306
```
From the documentation of `rand`:

> Pick a random element or array of random elements from the set of values specified by S; S can be
> 
>     •    an indexable collection (for example 1:n or ['x','y','z'])

I had expected the output to be either equal to A):
```
julia> rand([1, 2])
2
```
or perhaps B):
```
julia> rand((1, 2))
1×2 Array{Float64,2}:
 0.788846  0.302817
```
Instead it seems I am getting C):
```
julia> rand(typeof(SVector(1,2)))
2-element SVector{2,Int64}:
 4251809197651799824
 3934010639117562646
```
I would have really liked it to produce a fast random selection, for example `rand(s::SVector{4})` could compile to `s[1+rand(Int8)&3]` which is ~5 times as fast as `rand(1:4)`.

**Comment by SimonDanisch** [comment]
Mirroring Base seems like a sensible choice here. Care to make a PR? :)

**Comment by DNF2** [comment]
It would be fun, but I would have to go through the whole process of 'learning how to contribute', with all the git stuff and so on. Might take a while.

**Comment by SimonDanisch** [comment]
You could test it locally... And if git is too annoying, just copy and paste it in the Github web interface ;)
There is an edit button for every file in a repository!

**Comment by c42f** [comment]
This is a bug: the function at https://github.com/JuliaArrays/StaticArrays.jl/blob/f30509beb8ea52aa0124a3a246bf7a87b467db12/src/arraymath.jl#L45 is just incorrect, as it dispatches to the version of rand for the `SVector` type, rather than taking elements of the `SVector`.
