### ISSUE TITLE
sizeof not defined for SMatrix

### ISSUE THREAD

**Issue by albop** [JuliaArrays/StaticArrays.jl#293]
From the README, one get the impression an `SMatrix` object should have a predetermined memory size, like `SVector`. But
```
sizeof(SMatrix{3,3,Float64})
```
raises:
```
argument is an abstract type; size is indeterminate
sizeof(::Type{T} where T) at essentials.jl:160
```
Also, maybe for the same reason it is not possible to do `reinterpret(SMatrix{2,2,Float64},rand(2,2,10),10)`

**Comment by c42f** [comment]
The problem here is that `SMatrix{N,M,T}` is an abstract type.  To write the full type you need `SMatrix{N,M,T,L}`, where `L = N*M` is the number of elements.

This is a bit of a pain, but due to technical reasons we couldn't avoid having `L` in the type parameters.

Here's what you want:
```julia
julia> sizeof(SMatrix{3,3,Float64,9})
72

julia> reinterpret(SMatrix{2,2,Float64,4}, rand(2,2,10), (10,))
10-element Array{StaticArrays.SArray{Tuple{2,2},Float64,2,4},1}:
 [0.587377 0.863366; 0.723625 0.718368]
 [0.510936 0.146172; 0.848018 0.142164]
...
```

**Comment by albop** [comment]
Thanks @c42f

**Comment by mschauer** [comment]
Still, letting `Base.sizeof(::Type{SMatrix{n,m, T}}) where {n,m,T}  = sizeof(SMatrix{n,m,T,n*m})` etc. would make sense.

**Comment by c42f** [comment]
True.  We could do that with `reinterpret` as well I suppose.  The question is, how far do we want to go with allowing people to treat `SMatrix{N,M,T}` as a concrete type?  We could add some methods to fix the confusion reported here and that might be nice, but I'm sure there's other functions which we will miss.

**Comment by c42f** [comment]
By the way, this issue may eventually be solved properly by language changes allowing some type parameters to be computable in a type alias like `SMatrix`.  IIRC Jeff seemed open to this, but I don't think it's really on the roadmap for julia-1.0.

**Comment by mschauer** [comment]
That would be so cool.
