### ISSUE TITLE
version 0.6.3 is not showing in MetaData

### ISSUE THREAD

**Issue by TsurHerman** [JuliaArrays/StaticArrays.jl#309]
Hi, 
for some reason the latest tagged version of static arrays is 0.6.2 with the faulty inv and det
for 4x4 matrices.

ver 0.6.3 fixes that issues but is not yet available through Pkg.update()

**Comment by mschauer** [comment]
This is a two-step procedure: First a new version is tagged and a pull request is created at METADATA.jl, see https://github.com/JuliaLang/METADATA.jl/pull/11374

After the pull request is merged it 0.6.3 becomes available through Pkg.update().

**Comment by mschauer** [comment]
Merged.
