### ISSUE TITLE
inv bugged for 3*3 complex matrices

### ISSUE THREAD

**Issue by Kirbod** [JuliaArrays/StaticArrays.jl#310]
Hello,

There is a problem with inv that does not return the correct result for complex 3*3 matrices.
e.g.
```
julia> A = im * @SMatrix eye(3);

julia> inv(A)*A
3×3 StaticArrays.SArray{Tuple{3,3},Complex{Float64},2,9}:
 -1.0+0.0im   0.0+0.0im   0.0+0.0im
  0.0+0.0im  -1.0+0.0im   0.0+0.0im
  0.0+0.0im   0.0+0.0im  -1.0+0.0im

julia> inv(im*eye(3))
3×3 Array{Complex{Float64},2}:
 0.0-1.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0-1.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0-1.0im

julia> inv(im*@SMatrix eye(3))
3×3 StaticArrays.SArray{Tuple{3,3},Complex{Float64},2,9}:
 0.0+1.0im  0.0-0.0im  0.0-0.0im
 0.0+0.0im  0.0+1.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+1.0im
```

Can you have a look at this please ?

**Comment by mschauer** [comment]
The inverse should not use `vecdot` in https://github.com/JuliaArrays/StaticArrays.jl/blob/ee371127cdf82d29ec7bf446bed946aa13ee231b/src/inv.jl#L24 but something like `bilinear_vecdot` which can be written analog to `vecdot` https://github.com/JuliaArrays/StaticArrays.jl/blob/7630a92f550db11a405665a2ea151746a6f15e6c/src/linalg.jl#L223 without the `conj`s

Similarly wrong: 
```
julia> det(SMatrix{3,3}(im*eye(3)))
0.0 + 1.0im

julia> det(im*eye(3))
-0.0 - 1.0im
```
