### ISSUE TITLE
Use of `one` in generator causing world age issues for ForwardDiff

### ISSUE THREAD

**Issue by jrevels** [JuliaArrays/StaticArrays.jl#316]
ref https://github.com/JuliaDiff/ForwardDiff.jl/issues/277

MWE (expected output is an empty `SVector`):

```julia
julia> using ForwardDiff, StaticArrays

julia> StaticArrays.diff(SVector(ForwardDiff.Dual(1)))
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type ForwardDiff.Dual{Void,Int64,0}
The applicable method may be too new: running in world age 21813, while current world is 21817.
This may have arisen from a call to the constructor ForwardDiff.Dual{Void,Int64,0}(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] one(::Type{ForwardDiff.Dual{Void,Int64,0}}) at ./number.jl:163
 [2] _diff(...) at /Users/jarrettrevels/.julia/v0.6/StaticArrays/src/mapreduce.jl:245
 [3] diff(::SVector{1,ForwardDiff.Dual{Void,Int64,0}}) at /Users/jarrettrevels/.julia/v0.6/StaticArrays/src/mapreduce.jl:238
```

AFAICT this is caused by the use of `one` (which ForwardDiff overloads for `Dual` numbers) within the generator [here](https://github.com/JuliaArrays/StaticArrays.jl/blob/0c21db3239242fe65bf21a60d43a06c4e979d3d5/src/mapreduce.jl#L241).

**Comment by mschauer** [comment]
Probably you should explain, how the resulting eltype `T = typeof(one(eltype(a)) - one(eltype(a)))` can be computed for Dual numbers.

**Comment by timholy** [comment]
Is there clear evidence that this line couldn't be moved into the "body" (the quoted expression)? Inference is getting better and better at static evaluation...

**Comment by c42f** [comment]
Yes, moving the type computation into the body should fix this up.  We do the same thing elsewhere in StaticArrays.

**Comment by c42f** [comment]
Does #317 do it for you?  I found quite a lot of other places where this same problem exists.

**Comment by mschauer** [comment]
Addresses the MWE. Please bump if there are remaining issues.

**Comment by jrevels** [comment]
This fixes the broken ForwardDiff tests. Can you tag a new release containing #317? Thanks!
