### ISSUE TITLE
Restriction on sizes in matrix-matrix multiplication.

### ISSUE THREAD

**Issue by denius** [JuliaArrays/StaticArrays.jl#323]
```julia
sa99 = rand(SMatrix{9,9,Float64,9*9})
sa99'*sa99
```
all ok, but
```julia
sa98 = rand(SMatrix{9,8,Float64,9*8})
sa98'*sa98
```
gives
`ERROR: No precise constructor for SVector{8,Float64} found. Length of input was 9.`

**Comment by c42f** [comment]
Oops, the medium sized non-square case wasn't covered in the tests.  I think I've got a fix.
