### ISSUE TITLE
work with ArrayViews

### ISSUE THREAD

**Issue by goretkin** [JuliaArrays/StaticArrays.jl#333]
I am interested in having https://github.com/JuliaArrays/ArrayViews.jl work for `MArray`s, which I think would have just worked before https://github.com/JuliaArrays/StaticArrays.jl/issues/55.

Any suggestions for how to do this without defining specific methods for `MArray` inside of `ArrayViews`? `ArrayViews` works for any mutable array with a regular memory layout, so I thought this was exactly what `DenseArray` was for.

**Comment by andyferris** [comment]
The pointer stuff never worked out, partially because it interacted badly with Julia's GC, so yeah we dropped `DenseArray`.

But more importantly, that package was an old prototype for Julia v0.3 users. Doesn't `view` and `SubArray` (now in `Base`) work for you?

```julia
julia> using StaticArrays

julia> v = MVector(1,2,3)
3-element MVector{3,Int64}:
 1
 2
 3

julia> view(v, 1:2)
2-element SubArray{Int64,1,MVector{3,Int64},Tuple{UnitRange{Int64}},true}:
 1
 2
```

**Comment by andyferris** [comment]
Also, instead of worrying about memory layout, the focus shifted to "linear" vs "Cartesian" indexing, and linear indexing is supported by static arrays.

Additionally, in the future we may improve the design such the the indices of a static array are static unit ranges. In that sense, a `SubArray` of a `StaticArray` may become more-or-less just like any other `StaticArray`.

**Comment by goretkin** [comment]
I was trying (unreasonably) hard to get zero allocations in v0.6, and when I last checked, constructing a `SubArray` allocates (the `SubArray` object has a field referring to a heap-allocated object, so it itself is heap allocated, if I understand correctly). That's why I was trying to use `ArrayViews`, because it has an `unsafe_aview`, which doesn't keep a reference, but just a pointer.

**Comment by andyferris** [comment]
I see.

Out of curiosity, have you tried v0.7? They have eliminated a great many useless GC allocations for things like `SubArray` wrappers.

**Comment by c42f** [comment]
Looks like this issue is probably solved by using `SubArray` and `view` in Base. If allocations are still present there's probably not a lot we can do in this package though; we'll need to wait for further upstream compiler improvements.
