### ISSUE TITLE
SizedArray of SubArray isn't a view

### ISSUE THREAD

**Issue by goretkin** [JuliaArrays/StaticArrays.jl#334]
(on StaticArrays 0.6.4)

```
using StaticArrays
m = eye(3)
vm = view(m, 3, : )
svm = SizedArray{Tuple{size(vm)...}}(vm)

julia> svm.data === vm
false
```

this means that mutating `svm` does not mutate `vm` nor `m`.

**Comment by andyferris** [comment]
`SizedArray` is currently only compatible with `Array` internally.

In principle we can change this to be any `AbstractArray` but it hasn't been done yet.
