### ISSUE TITLE
MArray Constructor should make copy

### ISSUE THREAD

**Issue by garrison** [JuliaArrays/StaticArrays.jl#335]
As [discussed on discourse](https://discourse.julialang.org/t/convert-or-copy-to-staticarrays-marray/7001/2) (and following the conclusion in JuliaLang/julia#23107), the `MArray` constructor should return a copy if an `MArray` is passed to it, but it does not in StaticArrays v0.6.4:

```julia
julia> a = @MVector [1,2,3]
3-element MVector{3,Int64}:
 1
 2
 3

julia> MVector(a) === a
true
```

**Comment by c42f** [comment]
Thanks for the bug report. This should be fixed now in master.

**Comment by garrison** [comment]
Thank you!
