### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/StaticArrays.jl#337]
Request from @Datseris for the QR

**Comment by Datseris** [comment]
Oh thanks! I didn't think this was worthy of an issue...

Yeah please tag the new juice qr, my body needs it!!!

**Comment by c42f** [comment]
Yes actually I think we probably should do a release.  There's been several bug fixes since the previous one as well.

**Comment by c42f** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11968

**Comment by ChrisRackauckas** [comment]
Thanks.
