### ISSUE TITLE
Conversion to Static arrays

### ISSUE THREAD

**Issue by jw3126** [JuliaArrays/StaticArrays.jl#36]
Currently there is no conversion from Base Arrays to static arrays:
```
julia> using StaticArrays

julia> SVector([1,2,3])
ERROR: MethodError: no method matching size(::Type{StaticArrays.SVector})
Closest candidates are:
  size{T<:StaticArrays.StaticArray{T,N}}(::Union{T<:StaticArrays.StaticArray{T,N},Type{T<:StaticArrays.StaticArray}}, ::Integer) at /home/admin/.julia/v0.5/StaticArrays/src/abstractarray.jl:4
  size{N}(::Any, ::Integer, ::Integer, ::Integer...) at abstractarray.jl:48
  size(::BitArray{1}) at bitarray.jl:39
  ...
 in StaticArrays.SVector{S,T}(::Array{Int64,1}) at ./sysimg.jl:53
```
Is there a good reason not to have such conversion?

**Comment by c42f** [comment]
This is unimplemented because it work would lead to a performance trap - the output shape (and hence type) of `SVector{A<:AbstractArray}(a::A)` cannot be inferred in general.  See #31 for discussion.

**Comment by andyferris** [comment]
Is this covered in the read me? Might be a good idea. 

@jw3126 try `SVector{3}([1,2,3])`. Don't think of a static array type as a complete type until its size is specified or is inferrable.

**Comment by jw3126** [comment]
Yeah, I understand the type instability trap. I was porting some code from `FixedSizeArrays` to `StaticArrays` and not having this conversion gone broke some of my tests. 
I agree its reasonable design for `StaticArrays` to make it inconvenient writing slow code. Btw StaticArrays is really awesome!

**Comment by c42f** [comment]
> Is this covered in the read me?

Is now: https://github.com/JuliaArrays/StaticArrays.jl#conversions-from-array

**Comment by andyferris** [comment]
Thanks Chris; looks good. :)

**Comment by andyferris** [comment]
There are now also docstrings and the "quick start" part of the README explaining this, as well as a decent error message. Hopefully this will reduce the volume of this request somewhat.

**Comment by c42f** [comment]
Nice @andyferris, this is a lot better.
