### ISSUE TITLE
eigvec of Complex Hermitian matrix want to be put in a Real Matrix

### ISSUE THREAD

**Issue by louisponet** [JuliaArrays/StaticArrays.jl#364]
https://github.com/JuliaArrays/StaticArrays.jl/blob/d3c5662aa8a8a65ab391dbb3bc58441dac3a1461/src/eigen.jl#L135

I think the `SMatrix` type should be `Complex{T}`

**Comment by andyferris** [comment]
I guess we need to separate the real symmetric / Hermitian from the complex Hermitian case.

I had originally developed StaticArrays for geometry stuff and the correctness of complex linear algebra has very low test coverage, which is something we should definitely improve on.

@louisponet If you have the appetite, a PR to fix this is very welcome. Like I said we'll want one method for `Hermitian{T} where T <: Complex` and another for `Union{Symmetric{T}, Hermitian{T}} where T <: Real`. The comment on that line about SizedArray is also out-of-date and should be removed.

**Comment by louisponet** [comment]
I see, It does seem that there are some instabilities with the complex algebra indeed, when I used a `SMatrix{Complex}` (Hermitian one), some random fluctuations in the eigval decomposition occur. I will think about doing a PR about this stuff, but I'm only jsut starting to use the package extensively in my code, so I'm not sure how qualified I am. But if I find the time I will have a look at it!
