### ISSUE TITLE
SVector(1, 2, 3)[1:2] isa Array

### ISSUE THREAD

**Issue by tkf** [JuliaArrays/StaticArrays.jl#372]
It seems that indexing with `UnitRange` and `StepRange` turns a `SArray` to an `Array`.

```julia
julia> SVector(1, 2, 3)[1:2]
2-element Array{Int64,1}:
 1
 2

julia> SVector(1, 2, 3)[1:2:2]
1-element Array{Int64,1}:
 1
```

Tried it with current master (b454bc9131333da153f49182c7829c385fb2a6f5) and Julia 0.6.2 and 0.7 (3a47cd4b2e).

**Comment by andyferris** [comment]
That’s intentional, because we can’t statically determine the size of the output matrix it is fastest to treat it as a dynamically allocates array. 

You can index with another static array, if that helps.

**Comment by tkf** [comment]
Thanks. But how about dynamically calculate the length and then use the same code as in `inds::StaticVector`?  Is it still slower than going to `Array`?

```julia
import Base: getindex
import StaticArrays: _getindex
using Base: @propagate_inbounds, @_propagate_inbounds_meta
using StaticArrays

const Indexer = Union{StaticVector{<:Any, Int},
                      OrdinalRange{<:Int, <:Int}}

@propagate_inbounds function getindex(a::StaticArray, inds::OrdinalRange{<:Int, <:Int})
    _getindex(a, Length(length(inds)), inds)
end

# getindex for inds::StaticVector is the same as in the current master:
@propagate_inbounds function getindex(a::StaticArray, inds::StaticVector{<:Any, Int})
    _getindex(a, Length(inds), inds)
end

@generated function _getindex(a::StaticArray, ::Length{L}, inds::Indexer) where {L}
    exprs = [:(a[inds[$i]]) for i = 1:L]
    return quote
        @_propagate_inbounds_meta
        similar_type(a, Size(L))(tuple($(exprs...)))
    end
end


@assert SVector(1, 2, 3)[1:2] == SVector(1, 2)
@assert SVector(1, 2, 3)[end:-1:1] == SVector(3, 2, 1)
```

**Comment by tkf** [comment]
OK.  I run a quick benchmark and going to the standard array is a lot faster, even though it takes some time to do GC.  But I guess actually it makes sense since each `inds[$i]` call is done separately without utilizing any kind of continuity.

But I suppose range-based indexing to SArray will come once you define static ranges, as mentioned here?:
https://github.com/JuliaArrays/StaticArrays.jl/issues/223#issuecomment-307595512

Anyway, I'm closing it since it was just my luck of understanding of StaticArrays.
