### ISSUE TITLE
floor, ceil, round called with (::Type{T}, ::SArray) return SArray of Any

### ISSUE THREAD

**Issue by wsshin** [JuliaArrays/StaticArrays.jl#390]
This is a very weird bug.  Consider the following function:
```julia
julia> VERSION
v"0.6.3-pre.0"

julia> function test_r_dotmult_sv()
           sv = @SVector rand(3)
           r = 1.0
           round.(Int, r.*sv)
       end
test_r_dotmult_sv (generic function with 1 method)
```
This returns an instance of not `SVector{3,Int}`, but `SVector{3,Any}`:
```julia
julia> test_r_dotmult_sv()
3-element StaticArrays.SArray{Tuple{3},Any,1,3}:
 0
 0
 0
```

If `r` is either not multiplied or multiplied without dot, then an instance of `SVector{3,Int}` is correctly returned:
```julia
julia> function test_sv()
           sv = @SVector rand(3)
           round.(Int, sv)
       end
test_sv (generic function with 1 method)

julia> test_sv()
3-element StaticArrays.SArray{Tuple{3},Int64,1,3}:
 0
 0
 0

julia> function test_r_mult_sv()
           sv = @SVector rand(3)
           r = 1.0
           round.(Int, r*sv)
       end
test_r_mult_sv (generic function with 1 method)
```

Of course, if we use `Vector` instead of `SVector`, then we get an instance of `Vector{Int}` as expected, even if `r` is dot-multiplied:
```julia
julia> function test_r_dotmult_v()
           v = rand(3)
           r = 1.0
           round.(Int, r.*v)
       end
test_r_dotmult_v (generic function with 1 method)

julia> test_r_dotmult_v()
3-element Array{Int64,1}:
 1
 0
 0
```

Not sure why this is happening.  This erroneous behavior does not occur in Julia 0.7.

**Comment by andyferris** [comment]
Might have something to do with the way we overload `broadcast`, I suppose. IIRC correctly there was meant to be some special handling of types in `broadcast`. Possibly we need some sort of `::Type{T}` signature or something (sorry I haven't had time to look into it).

FWIW you can do `map(x -> round(Int, x), v)` which should (I hope) be safe and fast.

**Comment by wsshin** [comment]
Oh, I forgot to mention something really weird about this error: if we call floor directly (not inside some other function), then this error does not occur.
```julia
julia> sv = @SVector rand(3)
3-element StaticArrays.SArray{Tuple{3},Float64,1,3}:
 0.314069
 0.297509
 0.135407

julia> r = 1.0
1.0

julia> round.(Int, r.*sv)
3-element StaticArrays.SArray{Tuple{3},Int64,1,3}:
 0
 0
 0
```
See that the return type is correctly set `SVector{3,Int}`.

**Comment by andyferris** [comment]
OK, thanks. Given that, we'll now need to check if we're doing something naughty in a "pure" context (like invoking inference from a generated function's generator).

Did you check what happens on Julia master?

**Comment by wsshin** [comment]
This is what I got on Julia master:
```julia
julia> VERSION
v"0.7.0-DEV.4465"

julia> function test_r_dotmult_sv()
           sv = @SVector rand(3)
           r = 1.0
           round.(Int, r.*sv)
       end
test_r_dotmult_sv (generic function with 1 method)

julia> test_r_dotmult_sv()
┌ Warning: `sub2ind(dims::DimsInteger, I::Integer...)` is deprecated, use `(LinearIndices(dims))[I...]` instead.
│   caller = broadcasted_index(::Tuple{Int64}, ::Array{Int64,1}) at broadcast.jl:92
└ @ StaticArrays broadcast.jl:92
3-element SArray{Tuple{3},Int64,1,3}:
 1
 1
 1
```

**Comment by c42f** [comment]
Yep, seems Base inference has improved and this is no longer an issue.
