### ISSUE TITLE
@SVector rand and randn don't work with rng argument

### ISSUE THREAD

**Issue by tpapp** [JuliaArrays/StaticArrays.jl#391]
Eg
```julia
julia> @SVector randn(Base.Random.GLOBAL_RNG, 5)
ERROR: TypeError: Type: in parameter, expected Type, got MersenneTwister
```
I looked at the macro and realized it may be tricky to do make this work, but a performant workaround would also help.

**Comment by andyferris** [comment]
True, the macros by there nature are a bit of a "hack" and it's hard to cover every use case.

IIRC you can do `randn(GLOBAL_RNG, SVector{5})`. We should be able to support `randn(GLOBAL_RNG, Size(5))` or something along those lines.

**Comment by c42f** [comment]
I don't think we'll fix this with the macros; there's just no way to make the macro interface generalize to the many expressions people might want to use with it. In fact, we might eventually deprecate the macro interface entirely.
