### ISSUE TITLE
StaticArrays is missing `kron` for two `SVectors` or `MVectors`

### ISSUE THREAD

**Issue by zygmuntszpak** [JuliaArrays/StaticArrays.jl#400]
The Kronecker product of two StaticVectors does not return a StaticArray. The current workaround is to represent each vector explicitly as a static single column matrix, since the Kronecker product of two static matrices does return another static matrix. However, I would like to inherit from `FieldVector`, so this workaround is not ideal for me. 

See [this discussion](https://discourse.julialang.org/t/request-guidance-in-optimising-the-performance-of-my-implementation-running-time-and-allocation/10528) for a pertinent use-case of the Kronecker product of two static vectors.

**Comment by fredrikekre** [comment]
See also #257

**Comment by andyferris** [comment]
Yes, let’s get this fixed. Anyone planning to look into it?

**Comment by zygmuntszpak** [comment]
I'm working on it now.

**Comment by andyferris** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/14798#pullrequestreview-122392064
