### ISSUE TITLE
Broadcast with `Scalar` broken on Julia master

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#414]
```julia
julia> Scalar(2) .* [1, 2, 3]
ERROR: MethodError: convert(::Type{Scalar{T}}, ::Scalar{T}) is ambiguous. Candidates:
  convert(::Type{SA}, a::AbstractArray) where SA<:(Scalar{T} where T) in StaticArrays at /Users/twan/.julia/dev/StaticArrays/src/Scalar.jl:13
  convert(::Type{SA}, sa::SA) where SA<:StaticArray in StaticArrays at /Users/twan/.julia/dev/StaticArrays/src/convert.jl:9
Possible fix, define
  convert(::Type{SA<:(Scalar{T} where T)}, ::SA<:(Scalar{T} where T))
```

I think the main question is whether `Scalar` still has any use in 0.7. The convention in Base is to use `Ref` to signify that an argument should be treated as a scalar during broadcasting, so maybe usages of `Scalar` should be replaced by `Ref`. Thoughts?

**Comment by andyferris** [comment]
Thanks for noting and fixing this.

There's still a minor distinction that `Scalar` is a `struct` and `RefValue` is a `mutable struct`, so in certain circumstances we could end up with fewer allocations? I suspect with time we'll get a feeling for the answer to this question.

**Comment by tkoolen** [comment]
Sounds good.
