### ISSUE TITLE
Assessment of the use of `RowVector` / `ConjVector` / `Transpose` / `Adjoint`

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#416]
Just for context, on 0.6 we have

```julia
julia> for x in ([1 2; 3 4], [1, 2], [im, im])
              @show typeof(x) typeof(transpose(x)) typeof(adjoint(x)) typeof(x')
              println()
          end
typeof(x) = Array{Int64,2}
typeof(transpose(x)) = Array{Int64,2}
typeof(adjoint(x)) = Array{Int64,2}
typeof(x') = Array{Int64,2}

typeof(x) = Array{Int64,1}
typeof(transpose(x)) = RowVector{Int64,Array{Int64,1}}
typeof(adjoint(x)) = RowVector{Int64,Array{Int64,1}}
typeof(x') = RowVector{Int64,Array{Int64,1}}

typeof(x) = Array{Complex{Bool},1}
typeof(transpose(x)) = RowVector{Complex{Bool},Array{Complex{Bool},1}}
typeof(adjoint(x)) = RowVector{Complex{Int64},ConjArray{Complex{Int64},1,Array{Complex{Bool},1}}}
typeof(x') = RowVector{Complex{Int64},ConjArray{Complex{Int64},1,Array{Complex{Bool},1}}}
```

while on 0.7:

```julia
julia> for x in ([1 2; 3 4], [1, 2])
           @show typeof(x) typeof(transpose(x)) typeof(adjoint(x)) typeof(x')
           println()
       end
typeof(x) = Array{Int64,2}
typeof(transpose(x)) = Transpose{Int64,Array{Int64,2}}
typeof(adjoint(x)) = Adjoint{Int64,Array{Int64,2}}
typeof(x') = Adjoint{Int64,Array{Int64,2}}

typeof(x) = Array{Int64,1}
typeof(transpose(x)) = Transpose{Int64,Array{Int64,1}}
typeof(adjoint(x)) = Adjoint{Int64,Array{Int64,1}}
typeof(x') = Adjoint{Int64,Array{Int64,1}}

typeof(x) = Array{Complex{Bool},1}
typeof(transpose(x)) = Transpose{Complex{Bool},Array{Complex{Bool},1}}
typeof(adjoint(x)) = Adjoint{Complex{Int64},Array{Complex{Bool},1}}
typeof(x') = Adjoint{Complex{Int64},Array{Complex{Bool},1}}
```

Right now, StaticArrays defines

https://github.com/JuliaArrays/StaticArrays.jl/blob/96bf39c4b723538f2f92e6ad34ce075623e9e9fb/src/StaticArrays.jl#L27

for 0.7, which, while it resolves a lot of test cases using `'`, is arguably not really the right thing to do.

In addition, there are still usages of `RowVector` in the `kron` code and in `triangular.jl` and `util.jl`. This currently results in test failures on Julia master.

Furthermore, there are a lot of cases where methods are defined only for `Adjoint` or `RowVector`, but arguably they should be defined for both `Adjoint` and `Transpose` (on 0.7 at least). For example in the broadcasting code we have (only):

https://github.com/JuliaArrays/StaticArrays.jl/blob/96bf39c4b723538f2f92e6ad34ce075623e9e9fb/src/broadcast.jl#L56-L58

which means that `Transpose(zeros(SMatrix{2, 2})) .+ zeros(SMatrix{2, 2})` just calls the generic broadcast code.

I'll try to improve the situation in a PR when I have the time, but I just wanted to assess the status quo first.

**Comment by andyferris** [comment]
Thanks @tkoolen, yes we definitely should make everything work nicely with `Transpose`. I had a bit of a hard time making the code work on v0.6 and v0.7 - in previous iterations I've just forked StaticArrays but we're trying to play nicely and provide a nice upgrade path for users so we didn't do that.

**Comment by tkoolen** [comment]
> we're trying to play nicely and provide a nice upgrade path for users

I *very* much appreciate that. We'll make it work.
