### ISSUE TITLE
Incorrect output type for zero function

### ISSUE THREAD

**Issue by danielmatz** [JuliaArrays/StaticArrays.jl#42]
Similar to #6, the `zero` function returns an MVector when the input is an SVector.  For example:

```julia
julia> zero(SVector(1, 2))
2-element StaticArrays.MVector{2,Int64}:
 0
 0
```

**Comment by danielmatz** [comment]
I think the following will fix it:

```julia
@generated function Base.zero{SA <: StaticArray}(::Union{SA, Type{SA}})
    s = size(SA)
    T = eltype(SA)
    if T == Any
        T = Float64
    end
    v = ntuple((i)->zero(T), prod(s))
    return quote
        $(Expr(:meta, :inline))
        $(Expr(:call, SA, Expr(:tuple, v...)))
    end
end
```

I'd be happy to make a pull request if this looks OK.  I could also add similar code for the `one` function.

**Comment by danielmatz** [comment]
I just realized that `zero` will have the same behavior as the single argument `zeros`.  Likewise for one.  So I'll make the simpler change and add some tests.

**Comment by andyferris** [comment]
Good point - we should fix `zero()`. (but not `one()` as it is meant to be the multiplicative identity, *not* an array filled with ones, which is what `ones()` is for).
