### ISSUE TITLE
zeros and ones shouldn't use _fill

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#428]
https://github.com/JuliaArrays/StaticArrays.jl/blob/8a2ea499644900651a6cf8901a303526309d0eab/src/arraymath.jl#L12

results in problems with non-isbits types:

```julia
julia> v = zeros(SVector{2, BigInt})
2-element StaticArrays.SArray{Tuple{2},BigInt,1,2}:
 0
 0

julia> v[1] === v[2]
true
```

**Comment by andyferris** [comment]
Agreed. Good catch.
