### ISSUE TITLE
Tests take too long

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#430]
We're getting timeouts on Travis. Could work around the problem using `travis_wait`, but I think it would be better to just reduce the time it takes to run the tests.

**Comment by tkoolen** [comment]
Started investigating this a bit. I thought I'd just get rid of the `N = 14` case in some of the new tests, but:

```julia
julia> using StaticArrays, Compat.Test

julia> @time @testset "Matrix inverse NxN, N > 14" begin
           for sz in (15, 50), typ in (Float64, Complex{Float64})
               A = rand(typ, sz, sz)
               SA = SMatrix{sz,sz,typ}(A)
               @test inv(A) ≈ inv(SA)
           end
       end
Test Summary:              | Pass  Total
Matrix inverse NxN, N > 14 |    4      4
182.003208 seconds (296.32 M allocations: 8.784 GiB, 0.85% gc time)
Base.Test.DefaultTestSet("Matrix inverse NxN, N > 14", Any[], 4, false)
```
182 seconds _for cases where the generic fallback is called_.

**Comment by andyferris** [comment]
There's always the technique of having test code of different lengths, and have CI only run faster tests. If you wanted to split out a bunch of tests into a `longtests` directory or something where we can do extensive fuzz testing, that might solve our problem.

**Comment by tkoolen** [comment]
The bigger issue is just that lots of functions currently don't have cutoffs for when to fall back to Base methods. I think a quick fix where we just avoid testing such big matrices is appropriate for now.
