### ISSUE TITLE
Some linalg.jl generated functions return values, not expressions, in some cases

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#435]
https://github.com/JuliaArrays/StaticArrays.jl/blob/8a2ea499644900651a6cf8901a303526309d0eab/src/linalg.jl#L283

https://github.com/JuliaArrays/StaticArrays.jl/blob/8a2ea499644900651a6cf8901a303526309d0eab/src/linalg.jl#L302

https://github.com/JuliaArrays/StaticArrays.jl/blob/8a2ea499644900651a6cf8901a303526309d0eab/src/linalg.jl#L344

**Comment by andyferris** [comment]
Right... I guess that while `eltype` is 'hyperpure", `zero` and `real` are not. It would be good to fix this.

**Comment by c42f** [comment]
I believe this has been sorted out for a while now :-)
