### ISSUE TITLE
Don't commit type piracy in test/qr.jl

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#437]
https://github.com/JuliaArrays/StaticArrays.jl/blob/77d051fe474e582398e62971742d4562fb57f232/test/qr.jl#L3-L8

**Comment by andyferris** [comment]
Fair enough.

Does anyone actually execute the test set in a Julia instance, and continue using that instance? (Honest question - I've never wanted to do this and it seems convenient to be able to have an isolated environment to test in).

**Comment by tkoolen** [comment]
> Does anyone actually execute the test set in a Julia instance, and continue using that instance? 

I do, to iterate quickly using Revise.

**Comment by c42f** [comment]
Fixed in #640
