### ISSUE TITLE
Appveyor isn't working

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#44]
Does anyone know how I can restart Appveyor since the move to JuliaArrays?

I can log into Appveyor through github credentials as myself (but can't see this new repository) and JuliaGeo (can't see this repository, obviously) but not as JuliaArrays. So I can't see where/how to activate things. @timholy was it you that enabled Appveyor for JuliaArrays? Do you understand how this works?

**Comment by c42f** [comment]
I don't really understand how this works, but if I log into appveyor as c42f, I do have StaticArrays on the list and I seem to be able to enable it.  I'm not sure that's the right thing to do though.

**Comment by andyferris** [comment]
Well if the URL is the new one, go for it! My one shows the old `andyferris` URL. Probably just a little too confusing for Appveyor.

**Comment by c42f** [comment]
https://ci.appveyor.com/project/c42f/staticarrays-jl

**Comment by c42f** [comment]
Ok, seems to be working after a small fix to the appveyor script. Does it do what you wanted?

**Comment by c42f** [comment]
Does this work for you Andy?  If so we can just close this I guess.

**Comment by andyferris** [comment]
Yes it seems to work on your account, but could I ask you to update the README with the correct badge? (I think you find it under appveyer settings)

**Comment by c42f** [comment]
@JuliaArrays/core I have created an appveyor account and JuliaArrays team specifically to let everyone get at the CI setup if you so please - you should all be admins.  Sorry for the spam if you don't care :-)

**Comment by timholy** [comment]
That's great. Do you have a link for how you did this? I'll want to do the same for JuliaImages, most likely.

**Comment by c42f** [comment]
@timholy the pages I found were somewhat confusing.  Short story:

* Create a github team in JuliaImages who should have access to the CI admin panel
* Create a new appveyor account at appveyor.com (username can be called anything, but obviously naming it JuliaImages is sensible).  Alas you'll have to supply a *unique* email different to your personal appveyor email for this, but for gmail you can get a fake "unique" email which goes to your normal address by appending something after a `+`, eg, `you+JuliaImages@gmail.com`.  This is just for the initial setup.
* Add your personal account to the JuliaImages account as a collaborator with admin privileges for convenience.
* Add the github team to the new appveyor account manually.
