### ISSUE TITLE
Use new 0.7 interface for QR and co?

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#445]
In current version `0.7.1` of StaticArrays something like e.g. 
```
s = SMatrix{4,4}(rand(4,4))
qr(s)
```
returns a tuple of `(Q, R)`. Should this be updated to reflect the new approach followed by ~`Base`~ `LinearAlgebra`?

*ps in addition there of course the well-known deprecation warnings from using `Base` instead of `LinearAlgebra`*

**Comment by c42f** [comment]
This has been done and we now return a factorization object from `qr`.
