### ISSUE TITLE
Introduce a `Point` type?

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#469]
I've been doing more-and-more geometry and I notice I often dispatch on points in 2D space as `StaticVector{2, <:Real}` and points in 3D space as `StaticVector{3, <:Real}`.

I wonder if we would benefit from some type aliases like
```julia
Point{N, T <: Real} = SVector{N, T}
AbstractPoint{N, T <: Real} = StaticVector{N, T}
```

or whatever so that I could dispatch on `Point{2}` or `AbstractPoint{3}` or whatever.

cc @SimonDanisch I know you like to use `Point` to distinguish your geometric positions so I was wondering your opinion in particular.

**Comment by KristofferC** [comment]
Feels like this is easily solved in your own code by just defining the typealias.

**Comment by ryanelandt** [comment]
[`GeometryTypes`](https://github.com/JuliaGeometry/GeometryTypes.jl) currently exports `Point` so it might  be suboptimal if someone needs to import both modules.

**Comment by c42f** [comment]
In hindsight I think this will never go in `StaticArrays` per se. Rather, `GeometryTypes` or the successor `GeometryBasics`, or some other related package should have that functionality.
