### ISSUE TITLE
Performance regression for initializing particular sizes of `SVector{N, SVector{M, Float64}}` on Julia master

### ISSUE THREAD

**Issue by rdeits** [JuliaArrays/StaticArrays.jl#470]
I'm getting some very strange and uneven performance when trying to initialize a zero SVector of SVectors. Certain combinations of `N` and `M` are slow and allocate, while others are fast. 

But by far the weirdest part is that which combinations are fast or slow depends on which ones I evaluate first in a given Julia session. 

Here's an example session: 

```julia
julia> using StaticArrays, BenchmarkTools

julia> @btime zeros(SVector{5, SVector{1, Float64}});
  166.792 ns (6 allocations: 128 bytes)

julia> @btime zeros(SVector{6, SVector{1, Float64}});
  2.095 ns (0 allocations: 0 bytes)

julia> @btime zeros(SVector{7, SVector{1, Float64}});
  1.961 ns (0 allocations: 0 bytes)
```

Evaluating in a different order gives a different result: 

```julia
julia> using StaticArrays, BenchmarkTools

julia> @btime zeros(SVector{7, SVector{1, Float64}});
  200.651 ns (8 allocations: 176 bytes)

julia> @btime zeros(SVector{6, SVector{1, Float64}});
  1.753 ns (0 allocations: 0 bytes)

julia> @btime zeros(SVector{5, SVector{1, Float64}});
  1.694 ns (0 allocations: 0 bytes)
```

So, one might imagine that this is just BenchmarkTools failing to omit the `@generated` function overhead, but benchmarking the same type (that is, whatever the *first* type I tried in the given session), continues to give the "slow" result: 

```julia
julia> using StaticArrays, BenchmarkTools

julia> @btime zeros(SVector{5, SVector{1, Float64}});
  167.785 ns (6 allocations: 128 bytes)

julia> @btime zeros(SVector{5, SVector{1, Float64}});
  180.150 ns (6 allocations: 128 bytes)

julia> @btime zeros(SVector{5, SVector{1, Float64}});
  167.913 ns (6 allocations: 128 bytes)
```

Tested on:

```
Julia Version 0.7.0-beta2.167
Commit 505f71925d (2018-07-28 17:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

with StaticArrays.jl master. 

Any ideas? This seems like it might just be a Julia bug.

**Comment by andyferris** [comment]
These order dependent things are typically either Julia bugs, or else when we (or BenchmarkTools) evaluate impure code in pure (`@pure`, `@generated`, ...) contexts which tends to screw with internal compiler assumptions. 

In any case I think we’ll need help from
elsewhere on this one. 

FYI @jameson (in case this interests you)

**Comment by rdeits** [comment]
This is reproducible without StaticArrays.jl, so i'm closing this in favor of https://github.com/JuliaLang/julia/issues/28342
