### ISSUE TITLE
Add Vector/Matrix/Array  constructors that match Base

### ISSUE THREAD

**Issue by musm** [JuliaArrays/StaticArrays.jl#481]
Any reason why the following does not work

`SMatrix(undef,10,2)`

it would parallel the default way to create an uninitialized  matrix in julia

`Matrix(undef,10,2)`

**Comment by fredrikekre** [comment]
What is that useful for?

**Comment by mschauer** [comment]
Could theoretically be useful for initialising say a Vector of SVectors.

**Comment by petar-andrejic** [comment]
The point of the undef initialiser is that sometimes you want to have the array memory allocated, but you're going to fill the entries later, and you don't want to waste compute time on filling entries that are going to be overwritten anyhow.

**Comment by c42f** [comment]
I don't see any need or possible use for this in the `SArray` case. I don't think it's even possible to implement.

Could you provide an example use case?

**Comment by petar-andrejic** [comment]
I think there’s confusion on the naming going on here. Because SArrays are read only, this type of constructor doesn’t have a purpose, however for the MArrays it definitely does.

**Comment by c42f** [comment]
Yes
https://github.com/JuliaArrays/StaticArrays.jl/blob/5afb0c11a21dc2da8d52117ea97f36dfd219f153/src/MArray.jl#L33-L36

**Comment by c42f** [comment]
I'll close this because I don't think there's much actionable here.  The `SMatrix` case really isn't useful.
