### ISSUE TITLE
Mutating fields of immutables

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaArrays/StaticArrays.jl#490]
I haven't been following this lately, but this finally gives fast code on 1.0:
```Julia
struct Test2
    x::Int64
    y::Float32
end
@inline Base.@propagate_inbounds function mutate!(x::T, val, fieldidx::Integer) where T
    ref = Base.RefValue{T}(x)
    FT = fieldtype(T, fieldidx)
    val_conv = convert(FT, val)
    GC.@preserve ref begin
        ptr = Ptr{UInt8}(Base.unsafe_convert(Ref{T}, ref))
        fieldo = fieldoffset(T, fieldidx)
        ptro = ptr + fieldo
        unsafe_store!(Ptr{FT}(ptro), val)
    end
    ref[]
end
function test()
    x = Test2(1, 1f0)
    mutate!(x, 22f0, 2) # field 2 -> y
end
using BenchmarkTools
@btime test()
```
Is it time to just add this, or is this already here in some form?

**Comment by c42f** [comment]
I think you could get `fieldidx` to be replaced by a symbol and this would probably work even better.

But really I think the whole "mutating immutables" thing is an issue for Base (or a package built specifically for such hacks on non-array types like `Test2`). Not so much something we should have in StaticArrays itself ;-)
