### ISSUE TITLE
A segfault with member functions

### ISSUE THREAD

**Issue by akels** [JuliaArrays/StaticArrays.jl#493]
Hello. When I tried to execute [example notebook](https://github.com/rdeits/RegionTrees.jl/blob/master/examples/adaptive_distances.ipynb) of RegionTrees.jl package I found a segfault on my system (Ubuntu 18.04). Purifying the crashing code I came up with this one:
```julia
SEGFAULT = true
using StaticArrays

struct TwosArray{N, T, L} <: StaticArray{NTuple{N, 2}, T, N}
    data::NTuple{L, T}
end
Base.getindex(b::TwosArray, i::Int) = b.data[i]

struct SignedDistanceRefinery{F <: Function} # <: AbstractRefinery 
    signed_distance_func::F
end

function refine_data(refinery::SignedDistanceRefinery, v) 
    refinery.signed_distance_func.(v)
end

signed_distance(x) = sqrt(sum(x.^2))
refinery = SignedDistanceRefinery(signed_distance)

vp = TwosArray{1,SArray{Tuple{2},Float64,1,2},2}((SVector(1.,2.),SVector(3.,1.)))

!SEGFAULT || refinery.signed_distance_func.(vp)
refine_data(refinery,vp)
```
Interestingly to cause a segfault both last two lines need to be present which also commute with themselves.

**Comment by andyferris** [comment]
Any ideas what is going wrong here? 

> Interestingly to cause a segfault both last two lines need to be present which also commute with themselves.

Is this likely to be a Julia bug, then?

**Comment by schmrlng** [comment]
Potentially related to #482 and https://github.com/JuliaLang/julia/issues/28981 (the core issue there seems to be nested broadcasting which appears here too).

**Comment by c42f** [comment]
Hmm. Seems Jameson has suggested at https://github.com/JuliaLang/julia/issues/28981#issuecomment-418202205 that we can't be using `return_type` the way we do.
