### ISSUE TITLE
reinterpret of Arrays of static arrays failed

### ISSUE THREAD

**Issue by Hong-Xiang** [JuliaArrays/StaticArrays.jl#501]
[`reinterpret` Arrays of static arrays](https://juliaarrays.github.io/StaticArrays.jl/stable/pages/api.html#Arrays-of-static-arrays-1) failed.

steps to reproduce:
```
using StaticArrays
function svectors(x::Matrix{Float64})
    @assert size(x,1) == 3
    reinterpret(SVector{3,Float64}, x, (size(x,2),))
end
m = zeros(3, 10)
svectors(m)
```
outputs:
```
ERROR: MethodError: no method matching reinterpret(::Type{SArray{Tuple{3},Float64,1,3}}, ::Array{Float64,2}, ::Tuple{Int64})
Closest candidates are:
  reinterpret(::Type{T}, ::Base.ReshapedArray, ::Tuple{Vararg{Int64,N}} where N) where T at reshapedarray.jl:191
  reinterpret(::Type{T}, ::A<:AbstractArray{S,N}) where {T, N, S, A<:AbstractArray{S,N}} at reinterpretarray.jl:14
  reinterpret(::Type{T}, ::Any) where T at essentials.jl:370
  ...
Stacktrace:
 [1] svectors(::Array{Float64,2}) at ./REPL[2]:3
 [2] top-level scope at none:0
```

**Comment by chethega** [comment]
@andyferris It appears that this is a documentation bug. Do we need a docfix before merging some variant of [https://github.com/JuliaArrays/StaticArrays.jl/pull/496](https://github.com/JuliaArrays/StaticArrays.jl/pull/496)?

**Comment by andyferris** [comment]
Yes - perhaps clearly documenting the *current* behavior on Julia 1.0 would be the best first step.

**Comment by dmbates** [comment]
Bump.  The old, failing, function `svectors` is still in the documentation as of v0.11.0
