### ISSUE TITLE
roundtrip SMatrix from cholesky decomposition of SMatrix

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaArrays/StaticArrays.jl#508]
I'd like to be able to recover an SMatrix from it's cholesky decomposition, but it doesn't survive the roundtrip:

```
julia> x = @SMatrix [1. .7; .7 .5]
2×2 SArray{Tuple{2,2},Float64,2,4}:
 1.0  0.7
 0.7  0.5

julia> xchol = cholesky(x)
Cholesky{Float64,SArray{Tuple{2,2},Float64,2,4}}
U factor:
2×2 UpperTriangular{Float64,SArray{Tuple{2,2},Float64,2,4}}:
 1.0  0.7
  ⋅   0.1

julia> xchol.U'xchol.U
2×2 Array{Float64,2}:
 1.0  0.7
 0.7  0.5
```

@simonbyrne suggested that adding an `SMatrix` method for `Cholesky{T,SMatrix}` would fix this.

**Comment by mschauer** [comment]
I think this has nothing to do with Choleskies and is a problem of Triangular: 
```

julia> x
2×2 SArray{Tuple{2,2},Float64,2,4}:
 1.0  0.7
 0.7  0.5

julia> UpperTriangular(x)*UpperTriangular(x)
2×2 UpperTriangular{Float64,Array{Float64,2}}:
 1.0  1.05
  ⋅   0.25
 
```

**Comment by simonbyrne** [comment]
Would be good to also overload `SMatrix(::Cholesky)` and `AbstractMatrix(::Cholesky{_,<:SArray,_})` methods.

**Comment by mschauer** [comment]
Yes, independently of Triangular issues
