### ISSUE TITLE
New release 0.9.0

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#522]
Hi guys,

I want the fix from #515 in a release, so I'm planning a new one. Here's the changelog for PRs which affect the code:

#484 - Fixed MMatrix boundshecks, faster getindex
#491 - add propagate_inbounds for SArray getindex
#503 - Fix various inference issues; avoid calling `Core.Compiler.return_type()`
#515 - Reinstate read(::IO, Type{<:StaticArray})
#511 - Optimized methods for Triangular * Triangular
#507 - Improve performance of Iteators.flatten with arrays of static arrays.
#519 - Fix missing size error for constructors

All of these are minor fixes and improvements, with the exception of #503 which is enough of a wildcard that I think we need to bump the version number to v0.9.0 ... hopefully it won't break many things but I guess we're not going to be sure until we try.

Actually perhaps we should go version 1.0 and stop pretending this package is in pre-release ;-)  Then we can start using semver properly.

@andyferris mentioned deprecating some old compatibility shims in #503. For that I've just created #521 which we could deal with before release. ~~Is there anything else?~~

## TODO 0.9
* [x] Deprecate old fixed size interfaces (#512)
* [x] Decide whether #525 goes in here (resolution: no)

**Comment by andyferris** [comment]
Thanks Chris, sounds perfect. I’d love to deprecate those modules before v1. 

We could add depreciations to v0.9.0 and immediately remove them for v1.0.0?

**Comment by fredrikekre** [comment]
I suggest removing all deprecations for this release too.

**Comment by andyferris** [comment]
> all deprecations

Are we happy to drop v0.7 support at this stage?

**Comment by andyferris** [comment]
> Is there anything else?

I think #518 (and potentially #520) will have breaking changes, too. (We can make a release without these, but resolving #518 before v1.0.0 would be nice. I'm thinking of deprecating the one-argument constructors in a v0.9 and get people to use `convert`, which we should fix up to work more robustly (i.e. fix #520)).

**Comment by c42f** [comment]
I added TODO to the issue description for 0.9 and 1.0. Feel free to edit and update as required.

**Comment by andyferris** [comment]
Looks good to me. Let's do v0.9, then.

**Comment by c42f** [comment]
> I'm thinking of deprecating the one-argument constructors in a v0.9 and get people to use convert

Just noticed this as I was about to tag & release but I noticed this comment.  Do you want me to hold off? I suggest there's no problem with just fixing it in 1.0 and leaving in the associated depwarns for the 1.x.y series. It's potentially somewhat breaking and people could do with a good chunk of time to fix it up anyway.

**Comment by andyferris** [comment]
Good question.

It seems like the kind of thing to do slowly and correctly rather than in a rush, so tag and release sounds good. :)

**Comment by c42f** [comment]
Yes!  Ok I'll do that.

**Comment by c42f** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/19043

**Comment by c42f** [comment]
I'm closing this issue as it's largely 0.9.0 focussed, will open a new one for 1.0.0 and put the TODO over there.
