### ISSUE TITLE
`one` method is undefined for `MArray` and `SArray`

### ISSUE THREAD

**Issue by YingboMa** [JuliaArrays/StaticArrays.jl#535]
```julia
julia> zero(@SVector rand(5));

julia> one(@SVector rand(5))
ERROR: MethodError: no method matching one(::SArray{Tuple{5},Float64,1,5})
...

julia> zero(@MVector rand(5));

julia> one(@MVector rand(5))
ERROR: MethodError: no method matching one(::MArray{Tuple{5},Float64,1,5})
...
```
This doesn't seem to be intentional.

**Comment by andyferris** [comment]
`one` is for identity matrices.

**Comment by YingboMa** [comment]
Could you elaborate a bit more? Thanks!

**Comment by fredrikekre** [comment]
Multiplicative identity, so `x * one(x) == x`, which does not hold for vectors.

**Comment by andyferris** [comment]
Sorry, yes - `ones` fills a vector with ones, while `one` creates the multiplicative identity.

**Comment by andyferris** [comment]
Sorry, yes - `ones` fills a vector with ones, while `one` creates the multiplicative identity.
