### ISSUE TITLE
Drop subtyping of `DenseArray`

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#55]
I had originally defined

``` julia
abstract StaticArray{T,N} <: DenseArray{T,N}
```

with the thought that a lot of functionality could be shared with `Base.LinAlg` functions, such as automatically calling out to BLAS functions and so-on.

In the end, I don't feel this has been as successful as I hoped. Most of the functions lack type-stability because `Base` makes a habit of calling `similar` (with the same size). So not only do users not get, e.g., an `SMatrix` back (they get an `MMatrix`), the code inside the functions (and sometimes the output) is frequently not type-stable and is probably much slower than just using `Base.Array`.

Further, most of the decompositions actually fail. Only `eig` seems to work well, and it is also not type stable internally.

And finally, we already have `StaticArray`s which are not dense, like `Rotation` and probably in the future things like static unit ranges and so-on.

So the proposal is to change to

``` julia
abstract StaticArray{T,N} <: AbstractArray{T,N}
```

and to therefore drop some free functionality (and implement things ourselves).

**Comment by c42f** [comment]
:+1: from me, these reasons seem compelling.

**Comment by andyferris** [comment]
The question is then whether to do this separately from an attempt to add the size as a type parameter.

**Comment by andyferris** [comment]
Though I'm leaning towards traits for that.

**Comment by c42f** [comment]
The options for putting the size as a type parameter seem somewhat poor without better compiler support.  I think it'd be worth trying a traits-based version.

**Comment by andyferris** [comment]
See #57
