### ISSUE TITLE
qr computation seems wrong when using StaticArrays

### ISSUE THREAD

**Issue by ronisbr** [JuliaArrays/StaticArrays.jl#551]
Hi guys!

Take a look at this result:

```julia-repl
julia> using LinearAlgebra

julia> using StaticArrays

julia> D = [2 0 0; 0 2 0; 0 0 2]
3×3 Array{Int64,2}:
 2  0  0
 0  2  0
 0  0  2

julia> Ds = @SMatrix [2 0 0; 0 2 0; 0 0 2]
3×3 SArray{Tuple{3,3},Int64,2,9}:
 2  0  0
 0  2  0
 0  0  2

julia> qr(D).Q
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> qr(Ds).Q
3×3 SArray{Tuple{3,3},Float64,2,9}:
 -1.0   0.0  0.0
  0.0  -1.0  0.0
  0.0   0.0  1.0
```

I was expecting the same `Q` matrix from `qr` decomposition when using a `Matrix` and a `SMatrix`. Is it expected?

**Comment by andyferris** [comment]
There are some degrees of freedom between the Q and R matrices such that the result is not unique. Notably swapping the sign of a column of Q and row of R will not change the product QR. Different algorithms may make different choices. 

Does that make sense?

**Comment by ronisbr** [comment]
Yes totally. I thought the algorithm in both cases were the same, but it seems that StaticArrays has its own implementation of QR factorization. Sorry for the noise.
