### ISSUE TITLE
Proposal: Accessing Vector{SVector} with [:, n]

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#558]
Would you accept accessing Vector{SVector} with [:, n] , as in 
```
data[:, n] === [d[n] for d in data]
```
with `data <: Vector{SVector}` ? I am sure many people use this all the time, would be nice to have the shortcut.

**Comment by andyferris** [comment]
In theory, it would be nice to use broadcasting. `getindex.(array, integer)` works. But not so much for non-scalar indexing. 

There are competing (and compelling) proposals for the `a.[i]` syntax, but it *might* be suitable for this too. 

But I’d rather follow the `AbstractArray` interface to the letter, and open issues/PRs in base Julia when necessary. People need to access nested structures even without StaticArrays - even something seemingly unrelated like (broadcasted) JSON field getting might benefit.

**Comment by KristofferC** [comment]
That would be type-piracy (it probably wouldn't be very breaking here since it only makes code that used to error, not error) but still.

**Comment by Datseris** [comment]
Why? `SVector` comes exclusively from the module `StaticArrays`. Type piracy is when both the function name and structures used in dispatch are from a foreign module.

**Comment by KristofferC** [comment]
`SVector` comes from `StaticArrays` but you talked about extending `Vector{SVector}`.

**Comment by KristofferC** [comment]
> The problem with this kind of change is that much generic code is written to rely on particular interfaces guaranteed by AbstractArray

Not only is it breaking the `AbstractArray` interface but it also changes behavior for a `concrete` type, which is bad regardless of any interface.

**Comment by andyferris** [comment]
Well, sure, yes, that makes it slightly worse. It comes in degrees, though; `Vector{<:SVector}` is an abstract type. The layout of a concrete type depends on the system. And so-on.

**Comment by timholy** [comment]
@Datseris, you can create a package that supports custom index types, e.g., `data[nthitem(n)]`, and define the corresponding `getindex` implementation for any AbstractArray type. I did this recently for [Interpolations](https://github.com/JuliaMath/Interpolations.jl/blob/35de5f9bb6ef2c7516ff385402d225918eabc72c/src/Interpolations.jl#L145-L187) (see [implementation](https://github.com/JuliaMath/Interpolations.jl/blob/35de5f9bb6ef2c7516ff385402d225918eabc72c/src/Interpolations.jl#L241-L299), which is much more complicated than this would be).
