### ISSUE TITLE
Type-stability of constructors for static matrices with splat arguments

### ISSUE THREAD

**Issue by cdsousa** [JuliaArrays/StaticArrays.jl#56]
This

```
f() = SMatrix{4,4}(1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.)
@code_warntype f()
```

returns `Any`.

However this (notice the tuple)

```
f() = SMatrix{4,4}((1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.))
@code_warntype f()
```

nicely returns `SMatrix{4,4,Float64,16}`.
Such issue also happens for `SVector`s and for both it only happens for more than 14 elements.

Is this something that is easily fixable, or is it something we must have to learn to live with?

**Comment by SimonDanisch** [comment]
hardly :( Since splatted arguments don't let the function specialize on the number of arguments, this constructor is unrolled somewhere ( up to 14 arguments, it seems).

**Comment by SimonDanisch** [comment]
Although, we should at least be able to use the `{4,4}` better, no?

**Comment by andyferris** [comment]
I think a combination of an inlined generated function can solve this. It's yucky... but oh well. 

Unfortunately at some point the Julia compiler "approximates" type signatures to make sure compilation is provably feasible. Depending if you are a C++ programmer or a type theorist this is either annoying or awesome. :)

**Comment by andyferris** [comment]
Note the internal functions of StaticArrays use Tuples everywhere because of this, and outside of short vectors I recommend you do this too (think of a static array as a tuple with extra methods defined if that helps).

**Comment by cdsousa** [comment]
Well, I'm now using @SMatrix which both infers the type correctly and alows me to forget about memory column major layout. Thanks both!

**Comment by andyferris** [comment]
> Since splatted arguments don't let the function specialize on the number of arguments, this constructor is unrolled somewhere ( up to 14 arguments, it seems).

Actually I had definitions up to 16 in *core.jl*. I'm not sure what the problem with compilation over size 14 is (I get the same problem with matrix multiplication with one of the algorithms I tried, and that uses tuple input) but I suspect that it hits some limit in *inference.jl*.

**Comment by andyferris** [comment]
There's probably not much I can do here, so I'm going to close this one.

OTOH I plan to improve the syntax for the macros (maybe a new, more-powerful macro like `@SA`) and comprehensions (e.g. `collect(::Generator)`) and constructors involving `Generator`s and statically sized unit ranges, and I imagine moderately large arrays would be better initialized via these.
