### ISSUE TITLE
reverse(::SVector)

### ISSUE THREAD

**Issue by tpapp** [JuliaArrays/StaticArrays.jl#566]
Currently it uses the generic fallback in `Base`, so
```julia
julia> using StaticArrays

julia> reverse(SVector(1, 2))
2-element MArray{Tuple{2},Int64,1,2}:
 2
 1
```

Would getting an `SVector` be feasible?

**Comment by andyferris** [comment]
Yes, that shouldn’t be too hard. 

Is this something you would be interested in trying to implement?

**Comment by mschauer** [comment]
Yes, up to length 30 and a bit.
