### ISSUE TITLE
Release 0.10.2

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#574]
With the intent of getting some fixes out for the julia-1.1.0 release, here's some release notes for the changes since 0.10.1. I think these are all API-stable bug fixes and performance improvements.

* Ensure dot is recursive like Base (#559)
* Fix broken `setindex` with vector indices (#562)
* Fix `{h,v,hv}cat` of wrapped static matrices to return static matrices (#565)
* Make `reverse(::StaticVector)` faster (#567)
* Additional `propagate_inbounds` anntations (#564)
* Fixes for indexing with `SOneTo` (#569)

@timholy we might also want to get the following PR merged?
* Clean up indexing and dispatch https://github.com/JuliaArrays/StaticArrays.jl/pull/571

**Comment by timholy** [comment]
I think it's all good to go now. (#571 and #570 are both in).

**Comment by timholy** [comment]
I'll tag it.
