### ISSUE TITLE
SVector type signature is reversed compared to Base array constructors

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaArrays/StaticArrays.jl#577]
edit: `SVector{2,Float64}` but `zeros(Float64,2)`. This is unfortunate, and increases the mental burden one has to take into account; is it too late to change?

**Comment by ChrisRackauckas** [comment]
Vector doesn't have an integer with it. You are thinking of Array, buy SArray puts the dimension in the same spot.

**Comment by antoine-levitt** [comment]
Oops, sorry, that's a bad issue title and description. Yes, I was thinking of Arrays. It makes sense that SVector should match with SArrays, what I don't get is why SArray is backwards compared to Array. E.g. this looks weird:

`zeros(SVector{3,Float64},n)`

**Comment by antoine-levitt** [comment]
To be clear, the action point here would be to redefine the whole family (SArray, MArray, SVector and friends) to put the type on the first argument. I think this is more consistent, but of course very disruptive.

**Comment by fredrikekre** [comment]
But it is not inconsistent; `Array` doesn't have a size parameter. The order for `StaticArrays` is `{size, eltype, dim}` and for `Array` the order is (the same but missing size parameter): ` {eltype, dim}`.

**Comment by antoine-levitt** [comment]
For SArray I guess the two conventions make sense; but SVector cannot be consistent with both that definition of StaticArrays and with Vector.

**Comment by antoine-levitt** [comment]
OK, that's true, but `zeros(SVector{3,Float64},n)` still looks weird. Base generally puts type information first (`zeros`,`Array`,etc), and it is strange that `Svector` doesn't. It looks to me like the most logical solution would be `SArray{eltype,dim,size,numel}`; it is an `Array` first, with then some extra information. Then `SVector` can logically be `{T,N}`. The other solution is to leave `SArray` like it is, and make `Svector{T,N}`, trading consistency with `SArray` with consistency with Base.

**Comment by KristofferC** [comment]
When you write generic functions with StaticArrays arguments you most often want the size to match. Having it first means you can just write something like `::SVector{3}` instead of `SVector{<:Any, 3}`

**Comment by timholy** [comment]
Your title is still wrong, because it's `Vector{Float64}`. How can anything be reversed compared to that when there's only one parameter? (There is no `Vector{Float64,2}`.)

**Comment by antoine-levitt** [comment]
Yes, I was wrong (as pointed out by @ChrisRackauckas above). Edited the OP and title to reflect it.

**Comment by c42f** [comment]
Unfortunately, changing the type parameters like this would imply a reasonably epic amount of breakage of other packages, and there's no obvious way to make the transition smooth or backward compatible. It would really split the ecosystem into pre- and post- StaticArrays-2.0.0 (a made-up future version number in which we did this change).

Perhaps this could be viewed as a limitation of the deprecation system as it currently exists, that there's no real way to rearrange type parameters without breaking everything.

---

Having said that, I've personally experienced the same confusion with the ordering and I remember the annoyance even though I've gotten used to the ordering. Arguably, I think it would be coherent to have the current "static dimension tuple" sit in the place of the `Array` `ndims` like you suggest if the `ndims` could be removed from the concrete type paramters completely. That is, if we could have the *concrete* type of `@SMatrix[1 2; 3 4]` be

```julia
SArray{Int, (2,2)}
# rather than the current type, which has the redundant trailing {2,4} and funky `Tuple` type forced on us
SArray{Tuple{2,2}, Int, 2, 4}
```

then rearranging the type parameters might be worth considering. With the current state of the compiler technology this isn't possible though, as we can't make `SVector` or `SMatrix` be aliases for low dimensional `SArray`s and would need separate types for that. We did this in the past and there was a whole pile of types. It was nasty.

---

On the other hand, changing the order is somewhat likely to just be *really inconvenient* even though it looks more coherent on the surface. Having a short way to specify the size independently of the element type is quite handy, and I feel rather more common than wanting to specify the element type independently of the size (it would be interesting to know if this was true by measuring it). Even then, it would be neat to eventually be able to use `SArray{(2,2), Int}`.

Maybe one day the deprecation system will support us in these kind of changes and the compiler will allow "computed types" to free us from the weird `Tuple`s of integers and redundant type parameters :-)

**Comment by antoine-levitt** [comment]
Thanks for taking the time to post this! Let's revisit this issue if at some point it becomes feasible to get rid of the extra type parameters.

**Comment by c42f** [comment]
Agreed. I think I'll close this for now because the current design is a reasonable tradeoff given the constraints of what can be expressed with the current compiler and syntax.
