### ISSUE TITLE
Indexing of zero-dimensional MArrays

### ISSUE THREAD

**Issue by TheBB** [JuliaArrays/StaticArrays.jl#580]
Zero-dimensional mutable arrays must implement an "empty" indexing method to work with some other functions, e.g. `show`:

    julia> v = MArray{Tuple{},Int,0,1}(1)
    0-dimensional MArray{Tuple{},Int64,0,1}:
    Error showing value of type MArray{Tuple{},Int64,0,1}:
    ERROR: ArgumentError: invalid index: () of type Tuple{}

This works for `SArrays` because they are specialized as "scalars", and this method is defined for them, but `MArrays` aren't.

**Comment by andyferris** [comment]
Good catch.
