### ISSUE TITLE
Minimum value over a dimension

### ISSUE THREAD

**Issue by JoshChristie** [JuliaArrays/StaticArrays.jl#59]
Is there a better way to get the minimum value over a dimension for a Vector{SVector{3,Float64}} (e.g. `minimum(points, 2)`)? 
I have been doing this:
```julia
julia> points = [SVector{3, Float64}(rand(3)) for i = 1:5] 
5-element Array{StaticArrays.SVector{3,Float64},1}:
 [0.936339,0.268263,0.583008] 
 [0.564575,0.412917,0.469693] 
 [0.802534,0.699801,0.0992835]
 [0.379413,0.952707,0.229424] 
 [0.309086,0.335721,0.168284] 

julia> min_val = SVector{3, Float64}(minimum(map(x->x[1], points)), minimum(map(x->x[2], points)), 0)
3-element StaticArrays.SVector{3,Float64}:
 0.309086
 0.268263
 0.0
```

**Comment by c42f** [comment]
If you don't mind getting the z min as well, you could try `reduce(min, points)`?

In FixedSizeArrays we had `destructure()` which would also have worked by turning points into a matrix.  It had some caveats, could potentially port it over though.

**Comment by andyferris** [comment]
In any case I would suggest writing some code. If you want to find the minimums of the first two dimensions then you could use an anonymous function:

```julia
(minx, miny) = reduce((a,b) -> (min(a[1], b[1]), min(a[2], b[2])), points)
```

Sorry but other than what @c42f suggests I'm not sure what would help here.

**Comment by JoshChristie** [comment]
Okay thanks for the suggestions!
