### ISSUE TITLE
Nested SVectors not correctly inferred?

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#593]
It seems that nesting SVectors does not type infer correctly:
```jl
julia> using StaticArrays

julia> v = SVector(SVector(3, 2), SVector(5, 7))
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:
 [3, 2]
 [5, 7]

julia> v + v
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:
 [6, 4]
 [10, 14]

julia> @code_warntype v + v
Body::SArray{Tuple{2},_1,1,2} where _1
1 ─ %1 = StaticArrays.:+::Core.Compiler.Const(+, false)
│   %2 = invoke StaticArrays._map(%1::typeof(+), $(QuoteNode(Size(2,)))::Size{(2,)}, _2::SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}, _3::SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2})::SArray{Tuple{2},_1,1,2} where _1
└──      return %2

julia> using BenchmarkTools
@btime
julia> @btime $v + $v
  8.706 ns (1 allocation: 48 bytes)
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:
 [6, 4]
 [10, 14]
```
(Note the allocation here.)

**Comment by c42f** [comment]
Looks to be a bug in julia, perhaps? I can repro your example above, but the following (discovered by mistake!) in a clean session shows that it depends on what has been inferred already.

```julia
julia> using StaticArrays
m
julia> v = SVector(SVector(3, 2), SVector(5, 7))
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:
 [3, 2]
 [5, 7]

julia> map(+, v, v)
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:
 [6, 4]  
 [10, 14]

julia> @code_warntype v+v
Body::SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}
1 ─ %1  = (Base.getfield)(a, :data)::Tuple{SArray{Tuple{2},Int64,1,2},SArray{Tuple{2},Int64,1,2}}
│   %2  = (Base.getfield)(%1, 1, false)::SArray{Tuple{2},Int64,1,2}
│   %3  = (Base.getfield)(b, :data)::Tuple{SArray{Tuple{2},Int64,1,2},SArray{Tuple{2},Int64,1,2}}
│   %4  = (Base.getfield)(%3, 1, false)::SArray{Tuple{2},Int64,1,2}
│   %5  = (Base.getfield)(%2, :data)::Tuple{Int64,Int64}
│   %6  = (Base.getfield)(%5, 1, false)::Int64
│   %7  = (Base.getfield)(%4, :data)::Tuple{Int64,Int64}
```

This is a bit reminiscent of the inconsistencies in inference which led to https://github.com/JuliaLang/julia/issues/29923. Any thoughts @martinholters @vtjnash?

**Comment by martinholters** [comment]
I think this is just the recursion of `+` (or one of the methods called thereis, like `map`), where `+(::SVector{...,SVector{...,Int,...},...}, ::SVector{...,SVector{...,Int,...},...})` calls `+(::SVector{...,Int,...}, ::SVector{...,Int,...})`, which hits the same method, but the argument types are not recognized as less complex (in the limiting heuristics sense), hence inference stops. However, if `+(::SVector{...}, ::SVector{...})` has been inferred before, the cached result will be used.

**Comment by dpsanders** [comment]
Yes, that seems to be what's happening, thanks. Is there anything to be done / that should be done about this?

**Comment by c42f** [comment]
@martinholters thanks! So not inconsistent behavior from the compiler, simply inefficient.

@dpsanders you can use `v .+ v` and that is inferred. Wouldn't that be more consistent anyway?

**Comment by martinholters** [comment]
On second thought, as the element type is part of the container type (as one of its parameters), I thought  that should be ok. I might be missing something here.

**Comment by dpsanders** [comment]
My actual use case is for a polynomial type that wraps an `SVector` (or actually can just be a tuple, which I later realised also has the same issue), for which I need to define a more complicated multiplication function.

**Comment by c42f** [comment]
Hmm, I can guess at what you mean with the polynomial, but do you have a link to the code?

**Comment by dpsanders** [comment]
It's basically
https://github.com/tkoolen/StaticUnivariatePolynomials.jl, 
nesting one polynomial inside another.

**Comment by martinholters** [comment]
So the problem seems to be the `Size` argument of `_map`. In general, that makes sense, as it may vary arbitrarily when `map` calls itself recursively as for the `+` here. However, in this particular case, I don't quite get it as it is a `Size{(2,)}` for both the outer and the inner `SVector`s. Anyway, this (not particularly elegant) patch solves the present issue for me:
```diff
diff --git a/src/mapreduce.jl b/src/mapreduce.jl
index 42ff923..e914255 100644
--- a/src/mapreduce.jl
+++ b/src/mapreduce.jl
@@ -8,16 +8,26 @@
 # `map(f, as::Union{<:StaticArray,AbstractArray}...)` which included at least one `StaticArray`
 # this is not the case on 0.7 and we instead hope to find a StaticArray in the first two arguments.
 @inline function map(f, a1::StaticArray, as::AbstractArray...)
-    _map(f, same_size(a1, as...), a1, as...)
+    same_size(a1, as...)
+    _map(f, a1, as...)
 end
 @inline function map(f, a1::AbstractArray, a2::StaticArray, as::AbstractArray...)
-    _map(f, same_size(a1, a2, as...), a1, a2, as...)
+    same_size(a1, a2, as...)
+    _map(f, a1, a2, as...)
 end
 @inline function map(f, a1::StaticArray, a2::StaticArray, as::AbstractArray...)
-    _map(f, same_size(a1, a2, as...), a1, a2, as...)
+    same_size(a1, a2, as...)
+    _map(f, a1, a2, as...)
 end
 
-@generated function _map(f, ::Size{S}, a::AbstractArray...) where {S}
+@generated function _map(f, a::AbstractArray...)
+    local S
+    for ai in a
+        if ai <: StaticArray
+            S = Size(ai)
+            break
+        end
+    end
     exprs = Vector{Expr}(undef, prod(S))
     for i ∈ 1:prod(S)
         tmp = [:(a[$j][$i]) for j ∈ 1:length(a)]
@@ -27,7 +37,7 @@ end
     return quote
         @_inline_meta
         @inbounds elements = tuple($(exprs...))
-        @inbounds return similar_type(typeof(_first(a...)), eltype(elements), Size(S))(elements)
+        @inbounds return similar_type(typeof(_first(a...)), eltype(elements), $S)(elements)
     end
 end
 
```
```
