### ISSUE TITLE
Static Array/Vector isn't isbits

### ISSUE THREAD

**Issue by cshenton** [JuliaArrays/StaticArrays.jl#598]
One thing I'd like to do with static arrays is use them as fields in other struct types. For example:

```julia
using StaticArrays

Vec3 = StaticVector{3, Float64}

struct Ray
    origin::Vec3
    direction::Vec3
end
```

However, it seems that `Vec3` as defined above isn't an isbits type. So the Ray isn't. Which presumably means origin and direction are boxed pointers to Vec3s on heap, which is super slow.

```julia
isbitstype(Vec3) == false
isbitstype(Ray) == false

isbitstype(Tuple{Float64, Float64, Float64}) == true
```

Is there some way to ensure that static arrays are bits types? The corresponding tuple type is. Is there some extra data/generic params hiding there?

**Comment by KristofferC** [comment]
```
julia> Vec3 = SVector{3, Float64}
SArray{Tuple{3},Float64,1,3}

julia> struct Ray
           origin::Vec3
           direction::Vec3
       end

julia> isbitstype(Vec3)
true

julia> isbitstype(Ray)
true
```
