### ISSUE TITLE
vcat(::SVector, ::Number) should return an SVector

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/StaticArrays.jl#602]
I assume this behaviour is just an oversight:
```julia
julia> vcat(SVector(1), 2)
2-element Array{Int64,1}:
 1
 2
```
Shall I make a PR overriding `vcat`(and possibly `hcat`)?

**Comment by c42f** [comment]
I suspect that these methods don't exist because it was tricky to deal with the resulting ambiguities without support from `Base`. However if you can figure that out a PR would be most welcome.

**Comment by c42f** [comment]
To explain, a combinatoric explosion of ambiguities for varargs functions like `vcat` can arise when `Base` doesn't include extra machinery required to make it easy to override the output container type. This extra machinery is very well developed for broadcast (see the `Base.Broadcast.BroadcastStyle` trait) but for many other functions taking multiple containers it's not so easy.

**Comment by dlfivefifty** [comment]
Yes I understand. It might be easier to use LazyArrays.jl and use `SVector(Vcat(SVector(1), 2))`, though I'll have to figure out how to get it tell that this is an `SVector{2}`.

**Comment by c42f** [comment]
Well, if you just want a workaround there's plenty of options. Just wrapping the scalar in an `SVector` of length 1 for instance.

**Comment by dlfivefifty** [comment]
Ah, I see, it's only missing on the scalar case:
```julia

julia> vcat(SVector(1), SVector(2))
2-element SArray{Tuple{2},Int64,1,2}:
 1
 2
```
The benefit of the LazyArrays.jl approach is we can use `ApplyStyle` to determine that it should be an `SVector` automatically even for very complicated types. But I probably won't look at this anytime soon as there was an even simpler work around for my use case: `SVector(x.... y...)`.

**Comment by c42f** [comment]
Should be mitigated (to the extent which is easily possible) by #768

**Comment by c42f** [comment]
Interesting XRef which would have fixed this in Base: https://github.com/JuliaLang/julia/pull/20815
