### ISSUE TITLE
isnan and isinf on SVectors return Arrays

### ISSUE THREAD

**Issue by danielmatz** [JuliaArrays/StaticArrays.jl#61]
I'm trying to use `isinf` and `isnan`, and those functions are returning `Array`s instead of `SVector`s.

```julia
julia> a = SVector(1.0, NaN)
2-element StaticArrays.SVector{2,Float64}:
   1.0
 NaN

julia> isnan(a)
2-element Array{Bool,1}:
 false
  true

julia> a = SVector(1.0, Inf)
2-element StaticArrays.SVector{2,Float64}:
   1.0
 Inf

julia> isinf(a)
2-element Array{Bool,1}:
 false
  true
```

**Comment by andyferris** [comment]
I'm shocked these still work in Base. I doubt they will behave like that in 0.6. 

The correct solution for both `Array` and `SVector` is `isnan.(a)` and `isinf.(a)`. Embrace the dot-call elementwise syntax - it is your friend :smiley:

Does that solve the issue for you?

**Comment by danielmatz** [comment]
Yes, that does fix it.  Thanks!
