### ISSUE TITLE
Deprecate ::Number +/- ::StaticArray ?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaArrays/StaticArrays.jl#627]
This is inconsistent with `::Number +/- ::Array`:
```julia
julia> using StaticArrays

julia> SA = @SMatrix rand(2,2); A = Matrix(SA);

julia> 1 + SA
2×2 SArray{Tuple{2,2},Float64,2,4}:
 1.75609  1.63302
 1.98185  1.06612

julia> 1 + A
ERROR: MethodError: no method matching +(::Int64, ::Array{Float64,2})
```

**Comment by c42f** [comment]
Thanks for the bug report. We should certainly deprecate this in the next release.

**Comment by andyferris** [comment]
Agreed - thanks.

**Comment by c42f** [comment]
@fredrikekre it looks like you've got a commit which addresses this. Is it ready for a PR?

Once this is deprecated I think we should mark the next version v0.12.0; deprecation warnings are expensive enough to emit that they likely count as a breaking change for users of StaticArrays.

**Comment by fredrikekre** [comment]
Yea, its finished. While fixing it there was something that made me hesitant about the change which is why I didn't make a PR, but I have forgotten about the reason now so I'll just put up the PR :)
