### ISSUE TITLE
.^ produces an MVector

### ISSUE THREAD

**Issue by stevengj** [JuliaArrays/StaticArrays.jl#63]
```jl
julia> SVector(1,2,3) .^ 2
3-element StaticArrays.MVector{3,Int64}:
 1
 4
 9

julia> @which SVector(1,2,3) .^ 2
.^{T}(A::AbstractArray{T,N<:Any}, B::Number) at arraymath.jl:77
```
Probably there should be a specialized `.^` method?

**Comment by andyferris** [comment]
Bugger... I know I missed some of these (I see `.%` and `.\` are defined - what else is there?).

On the other hand, I can blame you for this!! :stuck_out_tongue: I followed closely the dot-call syntax upgrades and eagerly await `.op` broadcasting the same. :smile: (Dot-call is super cool btw, especially the fusion)
