### ISSUE TITLE
static sparse array

### ISSUE THREAD

**Issue by Roger-luo** [JuliaArrays/StaticArrays.jl#660]
I'm wondering if it is a good idea to PR our static sparse array to upstream: https://github.com/QuantumBFS/LuxurySparse.jl/blob/master/src/SSparseMatrixCSC.jl

it is faster than `SparseArrays.SparseMatrixCSC` sometimes.

**Comment by c42f** [comment]
Thanks for the suggestion! I think `LuxurySparse` is a better home so that `StaticArrays` can remain focused on doing the dense case well.

What benefit do you see in having it here?

**Comment by Roger-luo** [comment]
no, I'm committing patches in LuxurySparse to upstream. just checking if there is one.

**Comment by c42f** [comment]
Oh right. The natural place to upstream this is probably `stdlib/SparseArrays`, by making the `colptr` `rowval` and `nzval` of `SparseArrays.SparseMatrixCSC` parametric on the array type.  This is like what was done with `LinearAlgebra.Diagonal` a while back to make it capable of holding a static array.  (Before that, we needed a special type `SDiagonal`.)

**Comment by Roger-luo** [comment]
but will we need a `SSparseMatrixCSC` after `SparseArrays` supports this feature for backward compatibility reason (to make it work on v1.0 as well)?

**Comment by c42f** [comment]
Yes, you'll need something like that if you want backward compatibility.
