### ISSUE TITLE
Releases 0.11.1

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#673]
Apparently need an issue to trigger JuliaRegistrator... see #672 

@JuliaRegistrator register branch=release-0.11

**Comment by tkoolen** [comment]
You can also comment on a commit. I usually comment on the commit that sets the new version number, e.g. https://github.com/JuliaRobotics/RigidBodyDynamics.jl/commit/1f6986b05cf458eb4e5b5ab982039876f99015c4.

**Comment by c42f** [comment]
Thanks, that's a bit more lightweight maybe I'll do that next time. Though I don't entirely like that the act of registering and the JuliaRegistrator feedback is then attached to some random commit in the github UI.  Ah well :man_shrugging:

**Comment by c42f** [comment]
On second thoughts it's not so bad given it's attached to the actual commit to be registered. Will definitely try that out.
