### ISSUE TITLE
MArray is not isbitstype

### ISSUE THREAD

**Issue by tkonolige** [JuliaArrays/StaticArrays.jl#680]
Is there are reason `SArray` is a bits type and `MArray` is not?
```julia
julia> isbitstype(MVector{1,Float64})
false

julia> isbitstype(SVector{1,Float64})
true
```

**Comment by c42f** [comment]
Yes: to be mutable, `MArray` must contain a *reference* to the (immutable) data tuple so that the tuple can be replaced to modify the content of the array. Containing a reference means that `MArray` is not a bits type (see the docs for `isbitstype`).
