### ISSUE TITLE
SA not defined

### ISSUE THREAD

**Issue by homocomputeris** [JuliaArrays/StaticArrays.jl#687]
The readme file gives this example:
```julia
using LinearAlgebra
using StaticArrays

# Use the convenience constructor type `SA` to create vectors and matrices
SA[1, 2, 3]     isa SVector{3,Int}
```
however it gives
```
UndefVarError: SA not defined

Stacktrace:
 [1] top-level scope at In[1]:3
```

```julia
(v1.2) pkg> status StaticArrays
    Status `~/.julia/environments/v1.2/Project.toml`
  [90137ffa] StaticArrays v0.11.1
```

**Comment by fredrikekre** [comment]
You need at least version 0.12 for that, see https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.12.0.

**Comment by homocomputeris** [comment]
@fredrikekre 
When I execute `]add StaticArrays` Pkg only downloads 0.11.1.
Is 0.12 already updated in the package registry?

**Comment by fredrikekre** [comment]
Maybe you already have StaticArrays in your env? In that case, `pkg> update StaticArrays`. Otherwise you probably have something else in your env that restricts StaticArrays to 0.11. Try to explicitly `pkg> add StaticArrays@0.12` which should show you the problem.

**Comment by homocomputeris** [comment]
Thanks, it's OrdinaryDiffEq that lags behind.
