### ISSUE TITLE
Eigendecomposition of 3x3 symmetric Float64 matrices is not very accurate

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaArrays/StaticArrays.jl#696]
While working on the SPD manifold for Manifolds.jl we discovered some numerical accuracy problems that appear when using `MMatrix` but not `Matrix`. I've been able to identify one source of this problem, that is eigendecomposition of symmetric 3x3 matrices with Float64 elements. It's static implementation is much less accurate then what `LinearAlgebra` has. Example:

```julia
julia> using LinearAlgebra, StaticArrays

julia> x = @MArray [1.0 0.0 0.0; 0.0 1.7500000000000002 -0.4330127018922193; 0.0 -0.4330127018922193 1.25]
3×3 MArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 1.0   0.0        0.0     
 0.0   1.75      -0.433013
 0.0  -0.433013   1.25    

julia> meig = eigen(Symmetric(x))
Eigen{Float64,Float64,SArray{Tuple{3,3},Float64,2,9},SArray{Tuple{3},Float64,1,3}}
eigenvalues:
3-element SArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 0.9999999929755253
 1.0000000070244748
 2.0               
eigenvectors:
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 1.0  -0.0        0.0     
 0.0   0.5        0.866025
 0.0   0.866025  -0.5     

julia> eig = eigen(Symmetric(Array(x)))
Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
3-element Array{Float64,1}:
 1.0               
 1.0000000000000009
 2.0               
eigenvectors:
3×3 Array{Float64,2}:
 1.0  0.0        0.0     
 0.0  0.5        0.866025
 0.0  0.866025  -0.5     

julia> norm(x - meig.vectors * Diagonal(meig.values) * meig.vectors')
9.934107421073401e-9

julia> norm(x - eig.vectors * Diagonal(eig.values) * eig.vectors')
7.406111315403549e-16
```
For now we just disabled problematic tests but I think this issue should at least be known to other users of this functionality.

**Comment by c42f** [comment]
Thanks for the report. I do think we could strike a better (or certainly more consistent) balance in speed vs numerical robustness across the library as a whole. Some of the specialized small matrix algorithms were implemented with speed more than robustness in mind, but I'm not sure this is the best tradeoff for a general purpose library. I'd support efforts to make things more robust at the cost of a little speed.

**Comment by CarpeNecopinum** [comment]
Would be cool to have something more accurate indeed. My current use-case (PCA for normal estimation) blew up horribly as I end up with invalid/NaN normals for 10% of points.

Using `eigen(Array(smat))` gives me the accuracy I need, but causes a slowdown of > 2x.

**Comment by c42f** [comment]
That's surprising in a way: when `StaticArrays` was originally implemented we were particularly interested in PCA for normal estimation in noisy point clouds. Because of the noise we felt there was no point having a high accuracy method. But at least I would not expect NaNs out of `eigen`... indeed that's a bug rather than a case of "it happens to be inaccurate".

As always, it would be helpful if you could identify some test cases which are problematic for you and we can make sure they are fixed when this next gets worked on.

**Comment by CarpeNecopinum** [comment]
Yeah sure, have this file containing 10k lines of matrices that act weird when plugged into StaticArray's `eigen`, but work fine in the regular LinearAlgebra `eigen`.

[mats_short.txt](https://github.com/JuliaArrays/StaticArrays.jl/files/3959645/mats_short.txt)

(Weird thing: I identified these matrices by computing the normals of a point cloud and saving the covariance matrices in case the normal turns up NaN. If I run `eigen` on these after the fact, some of them don't come up NaN again. Yet the normals are at least horribly wrong there.)

Covariance matrices with zero variance in the z-axis appear to be particularly problematic:

```
for line in readlines(open("mats.txt"))
    smat = SMatrix{3,3,Float64}(eval(Meta.parse(line)))
    ela = eigen(Array(smat)).vectors[:,1]
    esa = eigen(smat).vectors[:,1]
    println("$esa -> $ela")
end
```

outputs a lot along the lines of

```
[0.06474165736274887, 0.9979020582211083, -0.0] -> [0.0, 0.0, 1.0]
[0.07986793607809453, -0.9968054538306987, 0.0] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
[NaN, NaN, NaN] -> [0.0, 0.0, 1.0]
```

**Comment by CarpeNecopinum** [comment]
Update, this doesn't appear to be linked to the z-axis in particular, switching the z and y components like 
```
flipmat = @SMatrix [1 0 0; 0 0 1; 0 1 0]
eigen(flipmat * smat * flipmat).vectors[:,1]
```
still gives me a non-sensical result of ~ `[0.99, 0.0, -0.14]`

**Comment by CarpeNecopinum** [comment]
If anyone knows of some resource about a better method in terms of precision, I could have a swing at it...

**Comment by mateuszbaran** [comment]
Implementation of the 3x3 symmetric eigendecomposition references some work of David Eberly, which may be this document: https://www.geometrictools.com/Documentation/RobustEigenSymmetric3x3.pdf (or an older version of this document), licensed CC BY 4.0 . It's possible that adaptation to Julia is incorrect.

**Comment by CarpeNecopinum** [comment]
Looks like it's a different method than the one in the PDF linked above.

Nevertheless, I implemented the method of the PDF in https://gist.github.com/CarpeNecopinum/61ae227ca7b0f1ecf393ae1daa009be5 (feel free to tell me when I messed something up) and it appears to work in my first few test cases (that is covariance matrices with no variance in the z direction). I'll test it out on my point clouds shortly and if it works clean up the implementation to make it merge-worthy.

**Comment by CarpeNecopinum** [comment]
While I feel reasonably certain that I implemented the non-iterative variant of the algorithm correctly, the results are still underwhelming... it doesn't have outright NaNs or similar nastiness in there, but the resulting normals come out much worse than using `eigen(::Array)` :disappointed:

**Comment by c42f** [comment]
Feel free to make a PR by the way if that makes it easier to try out the changes.  You can always title it "WIP: ..." if you feel it's not ready to merge :-)

**Comment by CarpeNecopinum** [comment]
I reimplemented the iterative version of the algorithm from the PDF and the results are pretty pleasing... my working variant is even faster than the `_eig(::Size{(3,3})...)` that we currently have, while also producing results that are basically identical to `eigen(::array)` :smile: 

Will cook up a PR for this soon...

**Comment by mateuszbaran** [comment]
PR #714 fixed this AFAICT.
