### ISSUE TITLE
Three-argument mul! behaves differently for Array and MArray

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaArrays/StaticArrays.jl#697]
Another issue spotted while debugging problems with SPD manifolds and `MMatrix`. A short sample code:
```julia
julia> using LinearAlgebra, StaticArrays

julia> A = randn(3,3)
3×3 Array{Float64,2}:
 -0.588885  -0.44014   -1.38506  
 -1.78098   -0.549597  -0.0071884
 -0.907166   0.673764   0.050497 

julia> AS = MMatrix{3,3}(A)
3×3 MArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 -0.588885  -0.44014   -1.38506  
 -1.78098   -0.549597  -0.0071884
 -0.907166   0.673764   0.050497 

julia> mul!(A, A, A')
3×3 Array{Float64,2}:
 2.4589    1.30065  0.167725
 1.30065   3.474    1.24498 
 0.167725  1.24498  1.27946 

julia> mul!(AS, AS, AS')
3×3 MArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 2.4589    -4.12739   -5.08146 
 1.30065   -2.01432   -2.53744 
 0.167725  -0.669376  -0.600606
```
I'd expect `mul!(A, A, A')` and `mul!(AS, AS, AS')` to be equal. In Manifolds.jl the error happens in this line: https://github.com/JuliaNLSolvers/Manifolds.jl/blob/4315b14dd16edb1249c6bc6d17a0b7bb0e2acdde/src/SymmetricPositiveDefinite.jl#L218 .

**Comment by mateuszbaran** [comment]
After reading docstring for this function I realized that this isn't supposed to work and we just have a bug in `Manifolds.jl`. Sorry for opening an invalid issue.

**Comment by c42f** [comment]
No problem at all. I assume the bug was that `y` and `z` may alias?

**Comment by mateuszbaran** [comment]
Yes, they actually point at the same array in the code I've linked. I've changed that to allocate a temporary array and it's fine now.

**Comment by andyferris** [comment]
Yeah there’s some machinery these days for fast conservative alias detection... from memory I believe we expose any parent pointers (of `MArray` and `SizedArray`) to the API, but don’t make use of it ourselves. It’s annoying how much impact a run-time check can have when crunching e.g. 2-vectors...
