### ISSUE TITLE
Add LabelledArrays.jl to docs

### ISSUE THREAD

**Issue by juliohm** [JuliaArrays/StaticArrays.jl#707]
`SVector` addresses all my computing needs when I have a `Tuple` of `Number` in mind. It defines all the operations to do the math with tuples statically. I wonder if there is a similar type in StaticArrays.jl that would be the equivalent for `NamedTuple`? Something like `SNVector` for "static named vector"?

The type would be such that `(a=1,b=2) .- (a=3,b=4)` returns `(a=-2,b=-2)` and `(a=1,b=2) .- (c=3,d=4)` throws an error because the variable names mismatch.

**Comment by c42f** [comment]
Have you seen https://github.com/JuliaDiffEq/LabelledArrays.jl? That might serve your needs?

**Comment by juliohm** [comment]
Thanks for sharing. I had only seen NamedArrays.jl. Perhaps `SLArray` and `SLVector` could be merged into StaticArrays.jl? Could they be part of the project goals? cc: @ChrisRackauckas

It would be nice to have these statically-compiled arrays in a single place to depend upon.

**Comment by c42f** [comment]
I often feel there's enough code here to maintain without adding to it ;-)

Perhaps the best thing to do here would simply be to link to LabelledArrays from the documentation.

**Comment by juliohm** [comment]
But depending on two separate packages with very similar functionality is
not ideal :/ maybe the maintainers of the two packages could join efforts
into one single package? SLArray seems like a good fit to StaticArrays.jl

**Comment by ChrisRackauckas** [comment]
Are they similar? I think the whole package is about handling names which is somewhat a tricky sideshow.

**Comment by juliohm** [comment]
Arent they static arrays as well but with labels ? I'm talking specifically
about SLArray and SLVector

**Comment by ChrisRackauckas** [comment]
They are static arrays with labels, and a bunch of generated functions to make that work without overhead. It also has non-static arrays: would that go to StaticArrays.jl or stay in LabelledArrays.jl? But if LArray is in a separate package from SLArray that's weird since they share naming structures and helper functions, so LArray would need to go to StaticArrays.jl, even though it's not a static array?

**Comment by juliohm** [comment]
I tend to interpret SVector as Tuple for math. Similarly I tend to think of
SLVector as NamedTuple for math. That is why I thought they deserve a
common package. I understand however that there is some shared
functionality. If there is a way to split SLVector out and move it to
StaticArrays.jl i think they would be most used. The use cases for labeled
arrays in general may be different than those use cases requiring fast
NamedTuple for math.

**Comment by ChrisRackauckas** [comment]
Then what do you do with LArray? That has more shared functionality than the StaticArray part, so that needs to stay together? And SLArray? It just seems very shortsighted.

**Comment by juliohm** [comment]
You know better the codebase. Thanks for considering the change anyways. I
just feel that a math-ready NamedTuple is missing in StaticArrays.jl and
SLVector looked like a perfect fit. Maybe reimplement the type here and
leave the nonstatic version in the LabelledArrays.jl package? I'm just
sharing thoughts.

**Comment by ChrisRackauckas** [comment]
SLArray is way more similar to LArray than it is to a StaticArray in implementation, so that really doesn't make sense without copy-pasting a bunch of code and trying to maintain in two repos what was previously in 1. SLArray doesn't really use anything about StaticArrays other than the fact that they exist.

**Comment by juliohm** [comment]
Thank you for the discussion, I am closing the issue.

**Comment by c42f** [comment]
Yes I don't think we'll add more code to `StaticArrays` to address this, but I do think we can keep this issue open as a documentation task. Generally it would be helpful to point out useful companion libraries such as `LabelledArrays` and `HybridArrays`.

**Comment by juliohm** [comment]
Closing again as it is too old, and no one is bumping into this doc issue it seems. I think that people can distinguish between LabelledArrays.jl and StaticArrays.jl nowadays.
