### ISSUE TITLE
adjoint(::SMatrix) fails unless eltype is unchanged

### ISSUE THREAD

**Issue by marius311** [JuliaArrays/StaticArrays.jl#708]
If `adjoint` changes the type of `SMatrix` elements, then `adjoint`ing the whole `SMatrix` fails, e.g.:

```julia
struct Elem end
struct AdjointElem end
Base.adjoint(::Elem) = AdjointElem()
adjoint(@SMatrix[Elem() Elem(); Elem() Elem()]) # errors
```

Or another example which fails for the same underlying reason:

```julia
adjoint(@SMatrix[[1,2] [1,2]; [1,2] [1,2]]) # errors
```

This is Julia 1.3 and StaticArrays 0.12.1.

**Comment by c42f** [comment]
Thanks for the report, should be fixed now.

**Comment by marius311** [comment]
Thanks for the quick fix!
