### ISSUE TITLE
Addition broadcast much slower

### ISSUE THREAD

**Issue by benmatwil** [JuliaArrays/StaticArrays.jl#713]
Using Julia 1.3.1 and StaticArrays 0.12.1, I've been adding together elementwise some position vectors but shouldn't these two additions be essentially the same? Yet there's quite a time difference time wise.
```
julia> x, y = SVector{3}(rand(3)), SVector{3}(rand(3))
julia> @btime x+y
  23.293 ns (1 allocation: 32 bytes)
julia> @btime x.+y
  213.645 ns (3 allocations: 160 bytes)
```
I'd also like to elementwise multiply (`.*`) the two vectors but it's also as slow as the second.
```
julia> @btime x .+ y
  213.271 ns (3 allocations: 160 bytes)
```

**Comment by tkoolen** [comment]
This is probably just an artifact of the way you're benchmarking (referencing globals):

```julia
julia> @btime x + y setup = (x = rand(SVector{3}); y = rand(SVector{3}));
  1.527 ns (0 allocations: 0 bytes)

julia> @btime x .+ y setup = (x = rand(SVector{3}); y = rand(SVector{3}));
  1.540 ns (0 allocations: 0 bytes)
```

**Comment by benmatwil** [comment]
Ah yes probably! Been trying to speed a couple of functions up and I removed all the dots from them (after testing my initial comment) and suddenly everything was running >2x faster so maybe I've done something else.

**Comment by tkoolen** [comment]
Yeah, I'm not saying it's impossible for there to be performance differences between code that uses `broadcast` and code that uses `map` (used under the hood in `+`), for certain sizes and in certain cases (especially multi-argument broadcast calls as in `x .+ y .+ sin.(z)`). See also https://github.com/JuliaArrays/StaticArrays.jl/issues/701 and the response I just added to that. But this case is too simple to show any of those differences.

I'll close this, but feel free to open a new issue if you find performance differences in slightly more complicated code that are interesting / hard to explain.
