### ISSUE TITLE
typo of setindex()

### ISSUE THREAD

**Issue by githubtomtom** [JuliaArrays/StaticArrays.jl#717]
the [see setindex(::MArray, val, i) in MArray.jl](https://juliaarrays.github.io/StaticArrays.jl/stable/pages/api/#Implementing-your-own-types-1) should be corrected to `setindex!`

**Comment by githubtomtom** [comment]
I failed to create pull request... do I need some special rights to do so?

**Comment by KristofferC** [comment]
Nope.

**Comment by c42f** [comment]
No. Though note that you need to fork the repo to a place where you have write access, make the changes there, and then create the pull request based on your fixed version.

**Comment by c42f** [comment]
Fixed in #718
