### ISSUE TITLE
Implement Singular Value Decomposition

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#72]
The `svd()` function should work on statically sized arrays. A first attempt would simply convert to `Array` and wrap the output in a `SizedArray`.

**Comment by anish18sun** [comment]
Hi, I'm willing to try my hands at this. `Base.linalg.svd` uses `LAPACK` module which internally calls blasfunc(blas library). I assume that static `svd()` would have its own SVD implementation for `StaticMatrix`(no library usage). I just wanted to know if the community had any preferences about which method should be used to implement SVD as there are several methods available(such as Jacobi, QR decomposition, matrix transpose, etc).

**Comment by andyferris** [comment]
Welcome - and cool!

Yes, we are aiming for native Julia code here. We don't have strong preferences for techniques here, so long as they are faster than LAPACK for small matrices. Accuracy is nice but some other algorithms we use prioritise speed which I find understandable. We can also upgrade code over time, if we find a competing approach is better later.

Of that list, we also would like a QR method, so that approach appears to solve two issues. Up to you of course!

For implementation, you can either write a few different methods that work for just one size each, or you can try write a generated function for all sizes. Whatever is most practical. 

(This is very exciting!)

**Comment by anish18sun** [comment]
Okay, so would you want the static QR method to be implemented first and then used in static SVD. No problem with that as I would have anyway tried that issue(QR) after writing SVD.

**Comment by andyferris** [comment]
Sounds great to me, as QR seems really useful for lots of reasons.

**Comment by c42f** [comment]
This was done in #231 (and #596; #618) by wrapping `LinearAlgebra` and propagating the static sizes in an inferrable way. The implementation could be improved, but I think we can close this issue for now.
