### ISSUE TITLE
Implement LU matrix factorization

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#73]
The `lu()` function should work on statically sized arrays. A first attempt would simply convert to `Array` and wrap the output in a `SizedArray`.

A fuller version of this would generate size-specialized code and be interfaced with `inv`.

**Comment by bshall** [comment]
I decided to have a go at this and I have a working implementation [here](https://gist.github.com/bshall/b567dfba58d5ba66841f7e55bd5cf761). Before I open a PR I wanted to know if there are any better solutions to a problem I had.

If you want to include pivoting, the index of the pivot row can only be computed at runtime. So if I want to swap row 1 with row p (where p is the index of the pivot row) I have to generate a branch for each possible value of p.

**Comment by c42f** [comment]
I don't know of any nice way to dynamically reorder the rows while avoiding memory allocations.

This is a bit of a generic problem in StaticArrays - even something as simple as `StaticArrays.insert()` uses a bunch of `ifelse`, one for each element to branch on the insertion index.

I imagine the real solution to these woes will come once something like https://github.com/JuliaLang/julia/pull/21912 is merged.

**Comment by andyferris** [comment]
Keep in mind that`setindex` is pretty fast. Also for very small matrix you can branch and have explicit layouts for each branch. Ugly I know but probably optimal. The branch itself is inevitable (unless you know e.g it's `Symmetric` or something) and thus OK, but the trick is to avoid allocations.

**Comment by c42f** [comment]
@bshall I've wrapped the Base version of `lu` in #231, so once that's merged there will be a place to slot in your work if you like.

Did you make any more progress on the static LU?

**Comment by bshall** [comment]
Great. I've gotten a bit waylaid recently so I haven't really done any work on it. I'll hopefully get back to it soon though.

**Comment by bshall** [comment]
I've started working on this again and wanted a quick bit of advise from @c42f and @andyferris. In the Base `LU` struct the pivot elements are stored in a `Vector{BlasInt}`. This isn't really ideal for `StaticArrays` since using a `Vector` to index into a `SMatrix` outputs a non-static `Matrix`. My question is: should we change the Base `LU` struct to work with an `AbstractVector`?

**Comment by fredrikekre** [comment]
FWIW I don't think it is worth having more parameters for `Base.LU`. Note also that `LU` is not even exported from `Base`, and I don’t see any drawback of defining `StaticArrays.LU` instead of relying on the `Base` implementation?

**Comment by andyferris** [comment]
> Note also that `LU` is not even exported from Base, and I don’t see any drawback of defining `StaticArrays.LU` instead of relying on the `Base` `struct`?

Agreed. If we implement something which makes sense for us *and* it is a strict improvement on `Base`, then we can make a PR to them.

Also, it's my personal opinion some of `Base`'s "factorization"  types are more-or-less optimizations for when dealing with large amounts of data and interacting with LAPACK. I'd personally be happy with `lu` not `lufact`, etc (not saying that suites everyone, but hey). Not sure if pivoting is an obvious exception...

**Comment by c42f** [comment]
Agreed.  The `Base` factorization types seem far from ideal, as the official interface seems to be `getindex()`, with a symbol, which isn't even type stable for `Array`, and has even less chance of working with `StaticArray`. I expect with some work in `Base` this could be improved, but for now I think we just go our own way.

**Comment by fredrikekre** [comment]
The individual factors should not be extracted with `getindex` anyway, so the type stable part should not be a problem.

**Comment by c42f** [comment]
What then, are functions such as `getindex(::SVD, ::Symbol)` for, and why are they clearly documented as the way to access the factors? I assume you mean that if you want the individual factors, you should use the decomposition functions, such as `qr` instead of `qrfact`?  And leave the factorizations as efficient standins for the original matrix when used with backdivide, etc.

I'm not disagreeing, just a little confused by the documentation.

**Comment by fredrikekre** [comment]
> leave the factorizations as efficient standins for the original matrix when used with backdivide, etc.

Yeah, that's what I meant. I was sure I have read somewhere in the documentation that extracting the factors like that should be avoided, but I can not find it now.

**Comment by c42f** [comment]
This was fixed in #368 thanks to Martin Holters.

**Comment by gszep** [comment]
would it be worth extending `LinearAlgebra.factorize` to point to this functionality?
```
factorize(A::StaticMatrix) = lu(A)
```
