### ISSUE TITLE
Indexing an SArray with SOneTo returns MArray instead of SArray

### ISSUE THREAD

**Issue by lassepe** [JuliaArrays/StaticArrays.jl#756]
I was surprised to find that something like this:

```julia
A = @SMatrix rand(2,2)
B = A[axes(A)...]
```
results in `B` begin an `MArray` rather than an `SArray`. IMHO, indexing with `axes` should be an identity, `B===A`. Is there any reason why indexing with `SOneTo` (a `Tuple` of which is returned by `axes(::SMatrix)`) needs to return an `MArray`?

**Comment by mateuszbaran** [comment]
Which version of `StaticArrays` do you use? 0.12.1 returns `SArray`:
```julia
julia> using StaticArrays

julia> A = @SMatrix rand(2,2)

2×2 SArray{Tuple{2,2},Float64,2,4} with indices SOneTo(2)×SOneTo(2):
 0.0711083  0.305146
 0.0919116  0.875324

julia> B = A[axes(A)...]
2×2 SArray{Tuple{2,2},Float64,2,4} with indices SOneTo(2)×SOneTo(2):
 0.0711083  0.305146
 0.0919116  0.875324
```

**Comment by c42f** [comment]
Thanks for the report. I think we're moving toward a model where static array types are preserved as much as possible, so I think this is a bug in an older version.

I'm going to close this but feel free to continue the discussion.

**Comment by lassepe** [comment]
Thank you for your quick reply. You are right, I tested with the wrong version (0.11.1). I am sorry for the confusion.
