### ISSUE TITLE
No method to convert from UniformScaling

### ISSUE THREAD

**Issue by danielmatz** [JuliaArrays/StaticArrays.jl#758]
If I have a struct such as

```julia
struct Foo
    x::SMatrix{3, 3, Float64}
end
```

and I want to initialize it using `I` (`UniformScaling{Bool}`), the following does not work:

```julia
Foo(I)
```

The constructor that Julia creates calls convert, but there isn't a matching method. Instead, I have to do

```julia
Foo(SMatrix{3, 3, Float64}(I))
```

Could we add a convert method? Perhaps one that just forwards to the constructor.

**Comment by c42f** [comment]
Yes, we should make this work by adding an appropriate `convert` method.

By the way, `SMatrix{3, 3, Float64}` is not a concrete type; you want `SMatrix{3,3,Float64,9}` instead.

**Comment by c42f** [comment]
#759 should fix this for you

**Comment by danielmatz** [comment]
> By the way, SMatrix{3, 3, Float64} is not a concrete type; you want SMatrix{3,3,Float64,9} instead.

Argh, I keep forgetting about that. Thank you.

And thank you for the fix!

**Comment by c42f** [comment]
> Argh, I keep forgetting about that.

Yeah it's really unfortunate that it's required :-(

I'm fairly sure there's nothing we can do about it though. Not until we have compiler support for doing something better.

**Comment by c42f** [comment]
Thanks for the bug report anyway :-)

**Comment by andyferris** [comment]
This is indeed an annoying case, @danielmatz. I am sympathetic. But I should refer to my post on #759:

> Umm, sorry, but I really think we shouldn't do this! If you are transforming an object by adding or removing information (e.g. `size`), you should use a constructor not `convert`.
> 
> `convert` relies on a whole bunch of assumptions. Or rather, methods in `Base` rely on a bunch of assumptions about `convert`. The `hash` should be the same before and after the convert. They must be `isequal`, and `isless` has to define the same ordering. It should conserve the transitivity of `isequal`, for example if you define this than `isequal(convert(SMatrix{2,2}, I), convert(SMatrix{3,3}, I))` shouldn't differ from `isequal(I, I)`, which must be `true`. It's also typically bi-directional/information conserving. (There are some accommodations made for converting `Float64` to `Float32` but even these are annyoing - and they are a different "flavour" of information change compared to adding/removing a `size`).
> 
> We can't do any of these with `I` and an `AbstractArray`, because the `size`/`axes` features in `isequal`, `hash`, `isless`, etc. Users currently can't use `convert(Matrix{Float64}, I)` so I don't see it as terribly surprising/going to change anyones generic code.

So.. unfortunately I'm not sure we should be fixing this here. If your `struct` is a `StaticArray` you should be be able to get the conversion for free (if that doesn't work let us know and we'll patch that). If your `struct` is not a `StaticArray`, it's unfortunate but overall I think it's better to define your own constructors that accept `I`.

**Comment by danielmatz** [comment]
Thanks for the explanation!

**Comment by c42f** [comment]
Haha, bummer. On the plus side, I goaded you into participating here Andy :-P

We can easily revert the fix, it wasn't a lot of work. (One of those rare times I though "hey yeah, a StaticArrays issue which is actually easy to fix and won't be hours of distraction")

**Comment by andyferris** [comment]
> I goaded you into participating here Andy :-P

lol

![image](https://user-images.githubusercontent.com/2974526/78209750-3eebd180-74eb-11ea-8878-a65d8f9cfda0.png)

**Comment by c42f** [comment]
Haha :joy: exactly that!
