### ISSUE TITLE
For all JuliaArrays collaborators: please enable two factor auth (2FA)

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#761]
Hi everyone @JuliaArrays, I plan to enable 2FA on JuliaArrays in **two weeks time** as a general matter of good security hygiene, as @viralbshah recently mentioned at https://discourse.julialang.org/t/enabling-2fa-on-major-github-orgs/31957/6. Two-factor authentication is a simple but high value security mitigation and I believe we need to take action on this soon. Indeed, I'm surprised the setting is not already enabled.

However I can see quite a few org members and collaborators have not enabled it @dlfivefifty @Evizero @oschulz @tkoolen @EvertSchippers @gordstephen @lindahua @mateuszbaran @milktrader @vincentcp. If we do this organization-wide, github will boot people without 2FA from the organization which is certainly not what we want.

I have included the deadline of two weeks for this, in order to take some near-term action and because I don't want to be held up indefinitely by inactive members we can't contact.

Note that if anyone is accidentally removed, we can easily re-add you later! Please do feel free to voice any concerns (or encouragement :-) )

(Finally, sorry to open this in the StaticArrays issues list. I wanted to be quite sure all collaborators could see it and the github discussions feature left me in doubt.)

**Comment by EvertSchippers** [comment]
Without your mention of me here, I would indeed not be aware! Thanks! 2fa enabled!

**Comment by dlfivefifty** [comment]
Enabled!

**Comment by mateuszbaran** [comment]
Thanks! I've enabled it.

**Comment by oschulz** [comment]
Thanks for initiative, @c42f, should have done this a while ago. Enabled now.

**Comment by fredrikekre** [comment]
I am sure GitHub warns you about this when enabling 2FA, but please make sure you have some kind of backup (https://help.github.com/en/github/authenticating-to-github/recovering-your-account-if-you-lose-your-2fa-credentials) otherwise you might lock yourself out of your account if you lose your 2FA device.

**Comment by c42f** [comment]
Thanks to everyone who's done this so far, much appreciated!

I think there's a few inactive members who we may loose, but as mentioned it's easy to re-add people again later. @Evizero @tkoolen @GordStephen @lindahua @milktrader — bump!

**Comment by ViralBShah** [comment]
I think we haven't seen many of those folks in a while.

**Comment by c42f** [comment]
Yep. Nevertheless, I'll give them the rest of the proposed two weeks to respond unless people think I should act on this sooner.

**Comment by c42f** [comment]
Ugh 2FA was still not required on JuliaArrays... did I never follow through on this !?

I'm just going to enable it now. I think the selection of folks who might be booted from the org are long gone, with the possible exception of @jishnub and @GordStephen - guys let me know if enabling this caused you any problems and we can fix them.

**Comment by c42f** [comment]
Sure, done!

It turns out github has a "reinstate previous permissions" option which is usable once people have enabled 2FA so I went with that.
