### ISSUE TITLE
`zeros` does not allocate memory for each instance.

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaArrays/StaticArrays.jl#767]
The memory is shared. Is it expected or a bug?

```julia repl
julia> vl = zeros(MVector{3, Float64}, 3)
3-element Array{MArray{Tuple{3},Float64,1,3},1}:
 [0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0]

julia> vl[1] .= 2
3-element MArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 v2.0l
 2.0
 2.0

julia> vl
3-element Array{MArray{Tuple{3},Float64,1,3},1}:
 [2.0, 2.0, 2.0]
 [2.0, 2.0, 2.0]
 [2.0, 2.0, 2.0]
```

**Comment by tkf** [comment]
Yeah, it is "expected" given how `zeros` work. Though I agree it's counter-intuitive.

I think this is more like a problem in `Base.zeros`: https://github.com/JuliaLang/julia/issues/29168

**Comment by c42f** [comment]
Great, thanks for that cross-ref to the Base issue, this is definitely an issue which would need to be resolved in `Base`.

`zeros(MVector{3, Float64}, 3)` just calls the Base implementation of `zeros` and I don't think it would be helpful for StaticArrays to depart from how other mutable types are treated when passed to `zeros`.
