### ISSUE TITLE
`Scalar(1, 2) === Scalar((1, 2))`?

### ISSUE THREAD

**Issue by tkf** [JuliaArrays/StaticArrays.jl#809]
Currently,

```julia
julia> Scalar(1, 2) === Scalar((1, 2))
true
```

But I guess disallowing `Scalar(1, 2)` is sensible?  It's a subset of #518 but I think just throwing a method error or augment error here is an easy fix.

ref #774

**Comment by c42f** [comment]
Yeah, definitely seems like a bug.  Let's disallow it before releasing 1.0.
