### ISSUE TITLE
Uncallable method of `_mul`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaArrays/StaticArrays.jl#813]
This method of `_mul`: https://github.com/JuliaArrays/StaticArrays.jl/blob/ad583c99768f3a381ba20b1a0782c9ca50890b50/src/matrix_multiply.jl#L87 can't be called because the first type argument of `SizedMatrix` etc. is not element type but a size. Should we just delete it? Apparently we are doing fine without using it.

**Comment by andyferris** [comment]
Yes cleaning up that code should be fine (it hasn’t been looked at thoroughly for years).
