### ISSUE TITLE
Support combination with FillArrays.jl

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/StaticArrays.jl#815]
It comes up pretty naturally to combine StaticArrays.jl with FillArrays.jl, e.g., `Fill(SVector(1,2), 10)`. This can support more specialised behaviour, for example, we could support
```julia
Fill(SVector(1,2), 10) .* Zeros(10) === Zeros{SVector{2,Float64},1}(10)
```
This raises a couple questions:
1. Should FillArrays.jl depend on StaticArrays.jl or the other way around? An argument that FillArrays.jl should depend on StaticArrays.jl is that the tests already do, and its currently more prone to breaking tags. 
2. Should we add a static version of `Fill`? Ref https://github.com/JuliaArrays/FillArrays.jl/issues/104

If we decide on FillArrays.jl depending on StaticArrays.jl, I can close this issue as there's nothing to do here, but just wanted to raise the question first.

**Comment by c42f** [comment]
> Should FillArrays.jl depend on StaticArrays.jl?

Yes, this seems like the right way around.

> Should we add a static version of Fill?

I don't know about this one. Probably best discussed at FillArrays :)

**Comment by dlfivefifty** [comment]
> Should we add a static version of Fill? Ref JuliaArrays/FillArrays.jl#104

Ha, just realised it already works!
```julia
julia> Fill(1, (SOneTo{2}(),))
2-element Fill{Int64,1,Tuple{SOneTo{2}}} with indices SOneTo(2): entries equal to 1
```

**Comment by c42f** [comment]
Nice!
