### ISSUE TITLE
Add `pointer` or `parent` method for `SizedArray`?

### ISSUE THREAD

**Issue by chriselrod** [JuliaArrays/StaticArrays.jl#822]
I'd like to support `StaticArrays.SizedArray` with LoopVectorization following its move toward using ArrayInterface.jl.

The two most convenient means of doing so would be to label it as either defining `pointer`, or that it should call `parent` and try again.
Currently, neither approach work:
```julia
julia> pointer(S)
ERROR: conversion to pointer not defined for SizedMatrix{3,4,Float64,2}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] unsafe_convert(#unused#::Type{Ptr{Float64}}, a::SizedMatrix{3,4,Float64,2})
   @ Base ./pointer.jl:67
 [3] pointer(x::SizedMatrix{3,4,Float64,2})
   @ Base ./abstractarray.jl:1065
 [4] top-level scope
   @ REPL[13]:1

To edit a specific method, type the corresponding number into the REPL and press Ctrl+Q

julia> parent(S) === S
 true
```

**Comment by mateuszbaran** [comment]
I think `SizedArray` should implement `pointer`. And `parent` should actually return the wrapped array. The second thing is somewhat breaking. PR #783 is a bit related.
