### ISSUE TITLE
Outer product of MVector returns SMatrix

### ISSUE THREAD

**Issue by pkofod** [JuliaArrays/StaticArrays.jl#828]
```
julia> x0m
3-element MArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 -1.0
  0.0
  0.0

julia> x0m*x0m'
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
  1.0  -0.0  -0.0
 -0.0   0.0   0.0
 -0.0   0.0   0.0
```
I would have expected MArray as the output type.

**Comment by mateuszbaran** [comment]
This stems from the problem that `similar_type`, when confronted with array wrappers like `Adjoint`, just returns `SArray`. Are there any reasons why it does that? This looks like an easy fix.

**Comment by c42f** [comment]
> Are there any reasons why it does that?

I don't think there's any reason for this. Your fix looks good.
