### ISSUE TITLE
Operations using a ReshapedArray 

### ISSUE THREAD

**Issue by rvignolo** [JuliaArrays/StaticArrays.jl#835]
Hi!
If:
```julia
v = @SVector ones(4)
m = reshape(v, (2,2))
a = @SVector ones(2)
```
Then:
```julia
julia> m * a
2-element Array{Float64,1}:
 2.0
 2.0
```
returns a `Vector` instead of a `SVector`. Is this behaviour expected?

**Comment by mateuszbaran** [comment]
Hi! I'm not sure if it's intended but you can always use `reshape(v, Size(2,2))` instead of `reshape(v, (2,2))` to get a statically sized reshaped array.

**Comment by mateuszbaran** [comment]
By the way, while looking into this issue I've discovered #836 .

**Comment by rvignolo** [comment]
Hi! Thanks for your suggestions, it is great. Does issue #836 relates to `SArray` as well? Because I am getting allocations when using `reshape(v, Size(2, 2))`, so I believe it is making a new copy as well as `MArray` does.

**Comment by mateuszbaran** [comment]
No, #836 does not affect `SArray`. `reshape(v, Size(2, 2))` should not allocate though when `v` is `SArray`. Your allocation could come from some other piece of code.

**Comment by rvignolo** [comment]
I believe the problem was that in my function I am using `reshape(v, Size(N, N))` with `N` a function parameter. Then, this makes the function type unstable.

**Comment by rvignolo** [comment]
great!
