### ISSUE TITLE
diff(A::SArray, [dim])?

### ISSUE THREAD

**Issue by wsshin** [JuliaArrays/StaticArrays.jl#84]
Is there a plan to implement `diff(A::SArray, [dim])`?  This should be doable, because the size of the result can be predicted from `size(A)`.

**Comment by andyferris** [comment]
All the reducer and cumulative methods (and `diff`) require both `size(A)` and `dim` to infer the size, and unfortunately there is no way to get at the (probably constant value) `dim` during compilation time. If you want to do this on vectors, then no problem, but in general we have to do something a bit different.

I was thinking `Val{dim}` might make sense for these functions, in place of `dim`. Does this sound reasonable?

PS - We welcome PRs :)

**Comment by andyferris** [comment]
See #65 for related discussion

**Comment by wsshin** [comment]
Your answer in #65 is great.  Thanks!

Yes, I think being able to pass `Val{dim}` will be useful.  Motivated by your encouragement to do PR, I have actually implemented `diff(::StaticArray{T,N}, ::Type{Val{D}})`.  Which source file do you think this function should go?  Maybe `mapreduce.jl`?

**Comment by wsshin** [comment]
Generated a PR: https://github.com/JuliaArrays/StaticArrays.jl/pull/86.

**Comment by andyferris** [comment]
Merged.
