### ISSUE TITLE
Unexpected (Incorrect?) Broadcasting with Tuples of Heterogeneous Type

### ISSUE THREAD

**Issue by jacobadenbaum** [JuliaArrays/StaticArrays.jl#841]
I ran into the following behavior when broadcasting addition between a tuple and a static vector, which is unexpected to say the least.  Is this a bug in how StaticArrays implements broadcasting?  

```julia
julia> using StaticArrays
julia> (1.0, 2) .- @SVector [0.0, 0.0]
2-element SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 1.0
 1.0

julia> (1.0, 2.0) .- @SVector [0.0, 0.0]
2-element SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 1.0
 2.0

julia> (1.0, 2) .- [0.0, 0.0]
2-element Array{Float64,1}:
 1.0
 2.0
```

**Comment by andyferris** [comment]
It took me a while staring at it to figure out what’s wrong (I was looking at they types not the values). That does seem like a bug!

**Comment by andyferris** [comment]
Tracking through all the broadcast dispatch machinery (which is correct), the problem is finally somewhere in `_broadcast` itself:

```julia
julia> StaticArrays._broadcast(-, Size(2), (Size(), Size(2)), (1.0, 2), SVector(0.0, 0.0))
2-element SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 1.0
 1.0
```

**Comment by andyferris** [comment]
I take that back, the first `Size` is incorrect:

```
julia> StaticArrays.broadcast_size((1, 2.0))
Size()

julia> StaticArrays.broadcast_size((1.0, 2.0))
Size(2,)
```

I think such tuples should have the same `broadcast_size`.

**Comment by andyferris** [comment]
This doesn't work
```julia
@inline broadcast_size(a::NTuple{N}) where N = Size(N)
```
because of this:
```
julia> (1, 2.0) isa NTuple{2}
false
```

I should change it to `broadcast_size(a::Tuple) = length(a)`.

**Comment by andyferris** [comment]
@jacobadenbaum thanks for the report, see #842.
