### ISSUE TITLE
vcat static arrays

### ISSUE THREAD

**Issue by rvignolo** [JuliaArrays/StaticArrays.jl#846]
Is this the desire behaviour when performing concatenation along dimension 1, i.e. when using `vcat`:
```julia
julia> vcat(SVector(1,2,3), 4)
4-element Array{Int64,1}:
 1
 2
 3
 4
```
returns a `Vector` instead of a `SVector`. To solve this I have to convert the scalar value to a static vector:
```julia
julia> vcat(SVector(1,2,3), SVector(4))
4-element SArray{Tuple{4},Int64,1,4} with indices SOneTo(4):
 1
 2
 3
 4
```

Notice that, for `Array`s there is no need to convert the scalar value to an `Array`:
```julia
julia> vcat([1,2,3], 4)
4-element Array{Int64,1}:
 1
 2
 3
 4
```
i.e. there is no need to:
```julia
julia> vcat([1,2,3], [4])
4-element Array{Int64,1}:
 1
 2
 3
 4
```

Thanks!

**Comment by mateuszbaran** [comment]
This has already been fixed on master: https://github.com/JuliaArrays/StaticArrays.jl/pull/768 , although it won't be in 0.12.5.

**Comment by rvignolo** [comment]
Thank you!
