### ISSUE TITLE
A / lu(A) returns Array when A is an SArray

### ISSUE THREAD

**Issue by dmillard** [JuliaArrays/StaticArrays.jl#851]
This is related to https://github.com/JuliaArrays/StaticArrays.jl/issues/796 but I think it's a different issue.

Here's an example:
```
julia> A = @SMatrix [1.0 2 3; 4 99 6; 22 8 9]
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
  1.0   2.0  3.0
  4.0  99.0  6.0
 22.0   8.0  9.0

julia> A / lu(A)
3×3 Array{Float64,2}:
 1.0  3.46945e-18  0.0
 0.0  1.0          0.0
 0.0  0.0          1.0
```

I would expect that this right hand solve would in fact produce an SArray, like in 

```
julia> A / A
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
  1.0  -0.0  -0.0
 -0.0   1.0  -0.0
 -0.0  -0.0   1.0
```

I'm not actually interested in `A/A`, I have a problem `A/B`, but I thought this demonstrated the type issues well.

Am I missing something that would help me get what I want? Thanks!

**Comment by mateuszbaran** [comment]
I think this was accidentally fixed on master in this PR: https://github.com/JuliaArrays/StaticArrays.jl/pull/837 . If you don't want to use master you can just add this method definition: `@inline Base.:/(A::StaticMatrix, B::StaticArrays.StaticULT) = transpose(transpose(B) \ transpose(A))`.

**Comment by dmillard** [comment]
Perfect. Thanks!

**Comment by c42f** [comment]
Nice!
