### ISSUE TITLE
Large union causes large allocations when compiling Julia 1.0.x

### ISSUE THREAD

**Issue by odow** [JuliaArrays/StaticArrays.jl#857]
This (very large) union is causing problems for JuMP (see https://github.com/jump-dev/JuMP.jl/pull/2390 for the full story): 
https://github.com/JuliaArrays/StaticArrays.jl/blob/0e431022954f0207eeb2c4f661b9f76936105c8a/src/StaticArrays.jl#L97
because we also pull in [MutableArithmetics.jl](https://github.com/jump-dev/MutableArithmetics.jl), which extends much of `LinearAlgebra` in the same way as StaticArrays. 

After this commit (https://github.com/JuliaArrays/StaticArrays.jl/commit/1b94778cda9e8d06cd5d56a8324dea8fd51dfa2c#diff-b899cd68e303f333bd6341af9c63b3717cbd50ae3a20d884de7c1822e2ddcfb3L52-R73), JuMP now takes more than 4 GiB to compile on Julia 1.0.5, and so our Github action CI gets killed:
https://github.com/jump-dev/JuMP.jl/runs/1471402527#step:6:8

This effectively makes JuMP unusable on Julia 1.0 with StaticArrays 1.0. 

Here's the script to run that gets at the root cause
```
#!/bin/bash

rm -rf src
rm Project.toml
rm Manifest.toml

mkdir src

echo """name = \"Foo\"

[deps]
LinearAlgebra = \"37e2e46d-f89d-539d-b4ee-838fcccc9c8e\"""" > Project.toml

echo """module Foo

import LinearAlgebra

# What MutableArithmetics does

abstract type A end
const B = AbstractMatrix{<:A}
const C = LinearAlgebra.Adjoint

LinearAlgebra.mul!(::B, ::Any, ::C) = 1
LinearAlgebra.mul!(::B, ::C, ::Any) = 2
LinearAlgebra.mul!(::B, ::Any, ::Any) = 3

# What StaticArrays does

abstract type D{M, T} <: AbstractMatrix{T} end
const D2{M, N, T} = D{Tuple{M, N}, T}

E{T} = Union{
    D{<:Int, T},
    D{<:Any, T},
    LinearAlgebra.Transpose{T,           <:D2{<:Any, <:Any, T}},
    LinearAlgebra.Adjoint{T,             <:D{<:Any, T}},
    LinearAlgebra.Symmetric{T,           <:D{<:Any, T}},
    LinearAlgebra.Hermitian{T,           <:D{<:Any, T}},
    LinearAlgebra.Diagonal{T,            <:D{<:Any, T}},
    LinearAlgebra.UpperTriangular{T,     <:D{<:Any, T}},
    LinearAlgebra.LowerTriangular{T,     <:D{<:Any, T}},
    LinearAlgebra.UnitUpperTriangular{T, <:D{<:Any, T}},
    LinearAlgebra.UnitLowerTriangular{T, <:D{<:Any, T}},
}

LinearAlgebra.mul!(::E{T1}, ::E{T2}, ::E{T3}) where {T1,T2,T3} = 4

end""" > src/Foo.jl

julia --project=. -e 'import Pkg; Pkg.instantiate(); Pkg.status(Pkg.PKGMODE_MANIFEST)'
julia --project=. -e 'using InteractiveUtils; versioninfo()'
rm -rf ~/.julia/compiled/v1.0/Foo
julia --project=. -e '@time using Foo'
```

It is informative watching the memory usage as you comment in/out methods 1, 2, and 3 in the script below.

- `4`: 0.1 GiB
- `1 + 4`: 1.3 GiB
- `1 + 2 + 4`: 2.6 GiB
- `1 + 2 + 3 + 4`: 4 GiB 

In contrast, `1 + 2 + 3 + 4` only takes 42 MiB to compile on Julia 1.5.

If you split the large `E` union in half and define
```
E{T} = Union{
    D{<:Int, T},
    D{<:Any, T},
    LinearAlgebra.Transpose{T,           <:D2{<:Any, <:Any, T}},
    LinearAlgebra.Adjoint{T,             <:D{<:Any, T}},
    LinearAlgebra.Symmetric{T,           <:D{<:Any, T}},
    LinearAlgebra.Hermitian{T,           <:D{<:Any, T}},
}
LinearAlgebra.mul!(::E{T1}, ::E{T2}, ::E{T3}) where {T1,T2,T3} = 4

E2{T} = Union{
    LinearAlgebra.Diagonal{T,            <:D{<:Any, T}},
    LinearAlgebra.UpperTriangular{T,     <:D{<:Any, T}},
    LinearAlgebra.LowerTriangular{T,     <:D{<:Any, T}},
    LinearAlgebra.UnitUpperTriangular{T, <:D{<:Any, T}},
    LinearAlgebra.UnitLowerTriangular{T, <:D{<:Any, T}},
}
LinearAlgebra.mul!(::E2{T1}, ::E2{T2}, ::E2{T3}) where {T1,T2,T3} = 4
```
The memory usage is only 0.3 GiB.

## Options

I see three potential resolutions:

1. JuMP bounds StaticArrays to `<=0.12.5`
2. JuMP drops support for 1.0 or gets reports of crashing peoples Julia instances
3. StaticArrays is refactored to break-apart the large union.

At present, I've gone for the first one, https://github.com/jump-dev/JuMP.jl/pull/2390, but this is probably going to cause compatibility issues as packages bump their lower bounds on static arrays. Options 2 and 3 aren't very attractive though, especially as this issue is fixed on later versions of Julia.

Thoughts?

x-ref: https://github.com/JuliaLang/julia/issues/38634
cc @mlubin

**Comment by mateuszbaran** [comment]
Thanks for looking into this issue. I was aware that Julia has problems with the `mul!` function (it has a lot of methods with complicated signatures, ref. https://github.com/JuliaArrays/StaticArrays.jl/pull/825) but this particular issue is new to me.

One problem with refactoring `StaticArrays` like that is that after splitting `mul!` is much more restrictive (you can't mix arguments of types from `E` and `E2` while now in StaticArrays.jl 1.0.0 you can). I guess if you added all possible combinations of `E` and `E2` memory consumption would go back to about 4 GiB.

**Comment by mateuszbaran** [comment]
I've checked this and actually writing these 8 methods covering all possible cases makes it consume less RAM on Julia 1.0 (1.2 GiB in this case). On the other hand on Julia 1.5 it has the opposite effect: having 8 methods instead of 1 significantly increases time and memory usage. What do you think about defining 8 methods on Julia 1.0 and just one on Julia >=1.1?

cc @c42f

**Comment by mateuszbaran** [comment]
It's a relatively simple and non-breaking change so I think we could do this in StaticArrays 1.0.1.

**Comment by odow** [comment]
Do you have a PR I can't test? Otherwise I can make one.

**Comment by mateuszbaran** [comment]
I didn't edit StaticArrays for these tests, just your example. If you could make a PR it would be great :slightly_smiling_face: .

**Comment by odow** [comment]
Okay, great. I'll have a play with some different options.
