### ISSUE TITLE
Feature proposition: matrix-vector product between SMatrix and NTuple (CartesianIndex)

### ISSUE THREAD

**Issue by Gregstrq** [JuliaArrays/StaticArrays.jl#864]
I propose to define matrix-vector products between `SMatrix` and `NTuple`, `SMatrix` and `CartesianIndex`. Of course, one can simply convert `NTuple` or `CartesianIndex` to `SVector` and do the multiplication, but it leads to extra memory allocations (albeit, not very large). On the other hand, it seems quite easy to reuse the existing code for `NTuple` and `CartesianIndex`, because this types are very similar to `SVector`.

I have the following use case for such extension.
Currently I am writing some code to work with Lattices (regular arrangement of nodes in space).
The basis of the lattice is given by `B::SMatrix{D,D}`. The typical task is calculation of the coordinate of lattice node with index `I::CartesianIndex{D}`. With the help of the extension I can simply write the coordinate as `B*I`.

Overall, since `NTuple` of `CartesianIndex` are quite similar to `SVector`, it does not sound as a totally bad idea to reinterpret them as `SVector` when they appear in some contexts together with other `StaticArray`s.

What do you think about it?
If you do not oppose this idea, I am ready to make a PR myself.

**Comment by mateuszbaran** [comment]
> it leads to extra memory allocations (albeit, not very large)

Are you sure it does? Converting tuples to `SVector` shouldn't cause any allocations. The only exception I can think of are `SVector`s of non-isbits types on Julia < 1.5.

**Comment by Gregstrq** [comment]
You are absolutely right. I did not take into account the allocation of the result of matrix vector product. There is no difference in timing and allocations between matrix vector product with existing SVector vs with conversion of NTuple.
