### ISSUE TITLE
Error in error message

### ISSUE THREAD

**Issue by kpamnany** [JuliaArrays/StaticArrays.jl#866]
Using v0.12.5, I saw:
```
UndefVarError: newsize not defined
```
In a stacktrace. It doesn't seem fixed in [`master`](https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/indexing.jl#L353).

**Comment by c42f** [comment]
Do you have the rest of the stacktrace?  That would help a lot in narrowing this down.

**Comment by kpamnany** [comment]
I linked to the offending line in the issue.

**Comment by c42f** [comment]
Ah, I missed the link in your finely crafted markdown.  Sorry!
