### ISSUE TITLE
Fail deploying documents since switching to GitHub Actions

### ISSUE THREAD

**Issue by hyrodium** [JuliaArrays/StaticArrays.jl#870]
There are no deployed documents on `gh-pages` branch since the PR #752.
https://github.com/JuliaArrays/StaticArrays.jl/tree/gh-pages

I think, this is because `Documenter.auto_detect_deploy_system()` is failing to detect GitHub Actions, and the function is detecting `Travis` mistakenly.

Here's a screenshot from GitHub Actions.
![image](https://user-images.githubusercontent.com/7488140/104831153-8bad6700-58c9-11eb-8a50-6baa5331ac65.png)

It should be like this:
![image](https://user-images.githubusercontent.com/7488140/104831184-d6c77a00-58c9-11eb-8c7d-ac4f3e5a4a63.png)

The functions `auto_detect_deploy_system()` is detecting the system from environment variables, so we should check them.
https://github.com/JuliaDocs/Documenter.jl/blob/master/src/deployconfig.jl#L825

**Comment by fredrikekre** [comment]
Very old Documenter.jl version https://github.com/JuliaArrays/StaticArrays.jl/blob/master/docs/Project.toml#L5

**Comment by hyrodium** [comment]
Okay, I'll make a PR.
