### ISSUE TITLE
Initialize takes long time

### ISSUE THREAD

**Issue by xijiang** [JuliaArrays/StaticArrays.jl#882]
```julia
@btime m = SVector{10000}(rand(10000));
# 0.000026 seconds (2 allocations: 78.203 KiB)
# 31s wall clock.
```

Is there a special way to declare a, e.g., 10k x 10k SMatrix? a 300x300 one seems to take infinite time already.

**Comment by mateuszbaran** [comment]
StaticArrays.jl is designed to work with arrays of up to about 100-1000 elements (depending on the operation). With matrices that large you should just use normal arrays.
