### ISSUE TITLE
`float(::StaticArray)` returns `::MArray`

### ISSUE THREAD

**Issue by wsshin** [JuliaArrays/StaticArrays.jl#89]
`float(::StaticArray)` returns an `MArray`:
```
julia> a = @SVector [1,2,3]
3-element StaticArrays.SVector{3,Int64}:
 1
 2
 3

julia> float(a)
3-element StaticArrays.MVector{3,Float64}:
 1.0
 2.0
 3.0
```
Shouldn't this return a `StaticArray`?

**Comment by andyferris** [comment]
I really wish `Base` would make better use of things like `map`. Or not define auto-vectorized functions like this one. Oh well.

`MVector` is a `StaticArray` but it is mutable (and therefore heap-allocated). `Base` is clearly using `similar` to make the new array. 

You could try `float.(a)` as a workaround (IMO this makes *much* more sense anyway).

**Comment by wsshin** [comment]
Thanks for the answer!  Agree with using `float.()`.
