### ISSUE TITLE
Allocations in broadcasting with views of StaticArrays

### ISSUE THREAD

**Issue by jishnub** [JuliaArrays/StaticArrays.jl#892]
```julia
julia> s = SMatrix{3,3}(ones(3,3));

julia> @btime $s[:,1] + $s[:,1];
  3.199 ns (0 allocations: 0 bytes)

julia> sv = @view s[:,1];

julia> @btime $sv + $sv;
  49.112 ns (1 allocation: 112 bytes)

julia> sv + sv |> typeof
SizedVector{3, Float64, Vector{Float64}} (alias for SizedArray{Tuple{3}, Float64, 1, 1, Array{Float64, 1}})
```

Perhaps views of `StaticArray`s may return other `StaticArray`s to avoid this allocation and slowdown?

**Comment by mateuszbaran** [comment]
Views of `StaticArray`s do return `StaticArray`s (specifically `SizedArray` in this case). Allocation comes from allocating the result of addition. For consistency, addition of two `SizedArray`s returns a new `SizedArray`, and the default container wrapped by `SizedArray` is `Array`.

In this case what we could do is making `similar_type` for `SizedArrays` wrapping `SubArray`s of `SArray`s return `SArray` of the right size. I'm not sure though why would you need to take views of `SArray`s?

**Comment by jishnub** [comment]
The reason for constructing views may be that the array is accepted as an argument to a function that does not assume that it is a `StaticArray`. In any case, for `SArray`s perhaps views might be implemented through indexing, as there is no need for the `SubArray` wrapper in this case? For example:

```julia
julia> using StaticArrays

julia> s = SMatrix{3,3}(ones(3,3));

julia> Base.view(s::SArray, I...) = getindex(s, I...) # implement views using indexing

julia> sv = @view s[:,1]
3-element SVector{3, Float64} with indices SOneTo(3):
 1.0
 1.0
 1.0
```

I'm not familiar with the internals of this package, so I'm not sure if this is the best idea. Open to suggestions.

**Comment by mateuszbaran** [comment]
Right, making views of `SArray`s like that could make sense. Let's wait until other people comment on that.
