### ISSUE TITLE
zeros(Size) does not work

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaArrays/StaticArrays.jl#923]
The docstring of `Size` suggests to use `zeros(Size(3,3))` to construct a StaticArray rather than a normal array.

Running this with StaticArrays v1.2.2 gives
```julia
julia> zeros(Size(3,3))
ERROR: MethodError: no method matching zeros(::Size{(3, 3)})
Closest candidates are:
  zeros(::Union{Integer, AbstractUnitRange}...) at array.jl:498
  zeros(::Tuple{Vararg{Union{Integer, AbstractUnitRange}, N} where N}) at array.jl:500
  zeros(::Type{MVector{N, T} where T}) where N at /home/schrist/.julia/packages/StaticArrays/uH2MB/src/MVector.jl:25
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[16]:1
```

**Comment by mateuszbaran** [comment]
You can always use `zeros(SMatrix{3,3})` so I don't know if this is a missing feature or an incorrect docstring.

**Comment by hyrodium** [comment]
https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/traits.jl#L28

>For example, to create a static matrix of zeros, use `zeros(Size(3,3))` (rather than `zeros(3,3)`, which constructs a `Base.Array`).
