### ISSUE TITLE
No versioned docs since v0.12.1

### ISSUE THREAD

**Issue by hyrodium** [JuliaArrays/StaticArrays.jl#938]
There's no versioned docs since v0.12.1.
https://github.com/JuliaArrays/StaticArrays.jl/tree/gh-pages

I can't find any triggered actions [here](https://github.com/JuliaArrays/StaticArrays.jl/actions/workflows/ci.yml), so there may be some problems with `ci.yml` or ssh key, I guess.

related: https://github.com/JuliaArrays/StaticArrays.jl/issues/870

**Comment by martinholters** [comment]
Not sure if helpful, but reminds me of https://github.com/JuliaDSP/DSP.jl/issues/434.

**Comment by hyrodium** [comment]
@fredrikekre Do you have permission to add the `DOCUMENTER_KEY` to this repository?
https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions

**Comment by c42f** [comment]
It seems that Documenter isn't successfully committing to the `gh-pages` branch? For example the following build succeeds and reports that it's going to deploy:

https://github.com/JuliaArrays/StaticArrays.jl/runs/4673830835?check_suite_focus=true

```
 ┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaArrays/StaticArrays.jl" occurs in repo="github.com/JuliaArrays/StaticArrays.jl"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push"
│ - ✔ ENV["GITHUB_REF"] matches devbranch="master"
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["DOCUMENTER_KEY"] exists and is non-empty
└ Deploying: ✔
```

But the `gh-pages` branch is still empty except for a couple of ancient commits from years ago.  `DOCUMENTER_KEY` is already set in the secrets (though I'm not sure it's required anymore anyway?)

**Comment by hyrodium** [comment]
>It seems that Documenter isn't successfully committing to the gh-pages branch? For example the following build succeeds and reports that it's going to deploy:

The github action was triggered when the PR was merged to `master`, and it succeed to deploy to https://juliaarrays.github.io/StaticArrays.jl/dev, not https://juliaarrays.github.io/StaticArrays.jl/v1.3.0.

The `DOCUMENTER_KEY` was required to trigger the github action with a new tag. If the key is set correctly, the action will run when adding a new tag, Documenter.jl detects the action was triggered by the new tag (e.g. `v1.3.0`), and will deploy docs to https://github.com/JuliaArrays/StaticArrays.jl/tree/gh-pages/v1.3.0 (this returns 404).

This behavior is documented in Documenter.jl documentation.
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

![image](https://user-images.githubusercontent.com/7488140/148386044-5027e805-92b3-42be-994a-fc78cccda8ac.png)

>But the `gh-pages` branch is still empty except for a couple of ancient commits from years ago. `DOCUMENTER_KEY` is already set in the secrets (though I'm not sure it's required anymore anyway?)

Hmm, I'm not sure, but I think the `DOCUMENTER_KEY` is not correct, or missing a [deploy key](https://github.com/JuliaArrays/StaticArrays.jl/settings/keys).
I have some experience of fixing this problem in other packages such as Rotations.jl, so I can solve this issue if you add me more permission.

**Comment by fredrikekre** [comment]
I believe the only problem is that the ssh key is missing from the tagbot config

**Comment by hyrodium** [comment]
Ah, thanks for the PR #984!

**Comment by hyrodium** [comment]
I've pushed some tags such as `v1.3.0+doc1`, and now these links are up to date:tada:
https://juliaarrays.github.io/StaticArrays.jl/stable/
https://juliaarrays.github.io/StaticArrays.jl/v1.3.0/
