### ISSUE TITLE
Subtracting empty vectors of SMatrix gives result of unexpected type

### ISSUE THREAD

**Issue by tpgillam** [JuliaArrays/StaticArrays.jl#965]
Suppose I have two empty vectors of `Float64`, and take a difference, I get an empty vector of `Float64`:
```julia
julia> Float64[] - Float64[]
Float64[]
```

All good if I use an `SVector` too:
```julia
julia> SVector{2,Float64}[] - SVector{2,Float64}[]
SVector{2, Float64}[]
```

But with an `SMatrix` the result is a vector of `Any`:
```julia
julia> SMatrix{2,2,Float64}[] - SMatrix{2,2,Float64}[]
Any[]
```

For non-static matrices I get the expected behaviour:
```julia
julia> Matrix{Float64}[] - Matrix{Float64}[]
Matrix{Float64}[]
```

I observed this on Julia 1.6.3, with StaticArrays 1.2.13

(Context: I ran into this when writing a test that was using `isapprox` on vectors of static matrices; internally this takes a difference of the two vectors, which then failed on trying to compute a `norm` of a `Vector{Any}`)

**Comment by mateuszbaran** [comment]
`SMatrix{2,2,Float64}` is an abstract type, if you use `SMatrix{2,2,Float64,4}` the type of the difference should be correctly inferred.

**Comment by tpgillam** [comment]
Ah, indeed so — thank you. Sorry about that!
