### ISSUE TITLE
Multiplication involving transpose of a `Matrix{<:SMatrix}`

### ISSUE THREAD

**Issue by maltezfaria** [JuliaArrays/StaticArrays.jl#966]
Hi,

I ran into the following (wrong?) behaviour when trying to multiply the following matrices of `SMatrix`:

```julia
using StaticArrays

A = @SMatrix rand(3, 3)
B = @SMatrix rand(3, 3)

blockA = fill(A, 3, 2)
blockB = fill(B, 3, 2)

val1 = blockA * transpose(blockB)
val2 = blockA * collect(transpose(blockB))

val1 ≈ val2 # false, by a lot
```

On my machine, the difference goes away if either `A` or `B` is changed to an `MMatrix`, which I found a bit puzzling. Here is some info on my version:

```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

Thanks!

**Comment by mateuszbaran** [comment]
I think this may be an issue with Julia matmul code here: https://github.com/JuliaLang/julia/blob/1b93d53fc4bb59350ada898038ed4de2994cce33/stdlib/LinearAlgebra/src/matmul.jl#L831 . `SMatrix` is an isbits type so it tries to do that tiled thing and fails.

Ref https://github.com/JuliaLang/julia/issues/26008 .

**Comment by maltezfaria** [comment]
Fixed in https://github.com/JuliaLang/julia/issues/51804
