### ISSUE TITLE
Simple test with BenchmarksTools locks up REPL

### ISSUE THREAD

**Issue by nicknack23** [JuliaArrays/StaticArrays.jl#98]
While testing some basics with StaticArrays I noticed that the following code consistently hangs the REPL (CTRL-c is unresponsive, but the close button works).

```
using StaticArrays, BenchmarkTools  
s1 = @SMatrix [rand() for i=1:100, j=1:100]  
s2 = @SMatrix [rand() for i=1:100, j=1:100]  
@benchmark s3 = @SMatrix [s1[i,j]*s2[i,j] for i=1:100, j=1:100]
```

I'm running Julia 0.5.0 on Windows 10.

**Comment by SimonDanisch** [comment]
100x100 is huge for a static array.
I think optimal working range is between ~1-7 elements and then maybe up to ~100.
Check out [SizedArray](https://github.com/JuliaArrays/StaticArrays.jl#sizedarray-a-decorate-size-wrapper-for-array) for your use case.
But it might make no sense to use StaticArrays for such big matrices.
The only advantage it has compared to normal arrays is, that operations can be unrolled and allocation can happen on the stack. Those two don't do much for such big matrices.
I'm not sure what happens in your case, but trying to unrole these plus some additional performance penalties might just lead to crazy slow code. You might even hit the function length limit, which introduces additional stutters.

@andyferris should we include warnings/errors for static arrays sizes, which can't possibly be useful?

**Comment by nicknack23** [comment]
Thanks! Most of my arrays are much smaller, so I'll limit my use of SA to those.

**Comment by c42f** [comment]
Yes, StaticArrays is for small matrices only at the moment (up to roughly 10x10 maybe?). It would be great to make it behave better for larger sizes, but we'd need an efficient way of iterating over and mutating the elements of a `Ref` to a `StaticArray` (needs changes to julia itself - perhaps in 1.0 beta :-) )

**Comment by andyferris** [comment]
I don't trust StaticArrays for large arrays. I'm not surprised that 100x100 would kill the compiler. Apart from putting 10,000 elements onto the stack, we also have 10,000 operations to do anything with it, and I'm pretty sure compilation in Julia is worse than O(N) in the number of instructions. 

PS the benchmark should probably have been `@benchmark s3 = s1.*s2`. That comprehension probably wouldn't be optimal compared to that.

**Comment by andyferris** [comment]
Some cutoffs or warnings or something might be a good idea, but certain operations seem to work well with large-ish `SizedArray`s (where well = not broken, `Array` can often be faster) so I have left it alone for now. At least a prominent warning in the README?

**Comment by c42f** [comment]
Yes, that's true; we should definitely have a clear warning about this.

**Comment by c42f** [comment]
I did a quick benchmark for matmul.  The crossover point seems to be about 11x11 for default optimizations, or 14x14 with `-O3`.  Here's the script, I didn't have time to make this into a PR yet

```julia
using BenchmarkTools

function bench(M, MS)
    b1 = @benchmark M*M
    @show b1

    b2 = @benchmark MS*MS
    @show b2

    @show judge(median(b2), median(b1))
end


const N = 11
M = rand(N,N)
MS = SMatrix{N,N}(M)
bench(M, MS)
```

**Comment by c42f** [comment]
I've included a rough rule of thumb in the README, that for arrays > 100 elements you should start thinking about using Base.Array instead - https://github.com/JuliaArrays/StaticArrays.jl#speed
