### ISSUE TITLE
reduce(f, ::SVector) allocates

### ISSUE THREAD

**Issue by tpapp** [JuliaArrays/StaticArrays.jl#986]
In JuliaStats/LogExpFunctions.jl#33 the following allocates:

```julia
using StaticArrays, LogExpFunctions, BenchmarkTools
x = randn(10);
s = SVector(x...);
@btime logsumexp($x)
@btime logsumexp($s)
```
while for the vector `x` we get zero allocations.

We have narrowed it down to `reduce` for `SVector` and `foldl` is a workaround, but I have no clear idea why `reduce` does this.

**Comment by mateuszbaran** [comment]
Seems like Julia fails at inlining a call with keyword arguments. There is quite a lot that can be done to force inlining of non-keyword functions but keywords still cause issues.

**Comment by tpapp** [comment]
But it works for `foldl`. Why are `(map)reduce` and `(map)foldl` implemented differently?

**Comment by mateuszbaran** [comment]
Hm, thanks for the question -- I thought there were no significant differences but there indeed was one. I think this should be easily fixable now that I see this.

**Comment by mateuszbaran** [comment]
Could you check if this branch fixes the problem for you: https://github.com/JuliaArrays/StaticArrays.jl/tree/mbaran/reduce-inlining ?

**Comment by tpapp** [comment]
Yes, this fixes the issue fully. Thanks!
